// SPDX-License-Identifier: Apache-2.0
//! The CH-form stabilizer state: a Clifford kernel that **keeps the global
//! phase**.
//!
//! A state is stored as
//!
//! ```text
//! |φ⟩ = ω · U_C · U_H · |s⟩
//! ```
//!
//! with `ω ∈ ℂ`, `U_H = ⊗_q H^{v_q}`, `s ∈ F_2^n` a computational basis
//! string, and `U_C` a Clifford drawn from the subgroup generated by
//! `{CX, CZ, S}` — the "control type" Cliffords, every one of which fixes
//! `|0…0⟩`. `U_C` is stored by its conjugation action, in the binary
//! symplectic layout this workspace already uses:
//!
//! ```text
//! U_C† X_p U_C = i^{γ_p} ⊗_q X_q^{F_pq} Z_q^{M_pq}
//! U_C† Z_p U_C =         ⊗_q Z_q^{G_pq}
//! ```
//!
//! `F G^T = I` over `F_2` (conjugation preserves the commutation of `X_p`
//! with `Z_r`), and `γ_p ≡ F_p·M_p (mod 2)` (the image of a Hermitian
//! operator is Hermitian). Both are checked by [`ChForm::check_invariants`].
//!
//! # Why not the Aaronson–Gottesman tableau
//!
//! `omega-backend-pauli`'s tableau is the right structure for sampling and
//! for `⟨P⟩` on a single state, and it is deliberately **not** reused here:
//! it stores the stabilizer group, which determines `|φ⟩` only up to a
//! global phase. Stabilizer-rank readout is a sum `Σ_ij c̄_i c_j ⟨φ_i|O|φ_j⟩`
//! over *distinct* states, where a per-state phase is not global and does
//! not cancel. Dropping it would turn every cross term into a magnitude.
//! That is the whole reason this file exists.
//!
//! What *is* reused is the convention and the arithmetic: the one copy of
//! the Aaronson–Gottesman `g` table lives in
//! `omega-backend-pauli::pauli_mult_phase` and this kernel calls it rather
//! than carrying a second one. The one adaptation is a convention shim —
//! see [`plain_mult_phase`].
//!
//! # Reference
//!
//! Bravyi, Browne, Calpin, Campbell, Gosset, Howard, "Simulation of quantum
//! circuits by low-rank stabilizer decompositions", Quantum 3, 181 (2019),
//! §4. The update rules below are re-derived in the doc comment of each
//! method rather than cited, because a transcription error in this table is
//! exactly the failure mode the mutation tests are aimed at.

use num_complex::Complex64;
use omega_backend_pauli::pauli_mult_phase;
use omega_core::executor::PauliOp;

/// Phase exponent (a power of `i`, mod 4) picked up by
/// `(X^a Z^b)·(X^f Z^m) = i^c · X^{a⊕f} Z^{b⊕m}` on one qubit.
///
/// This kernel stores Paulis as `X^x Z^z` with **no** `i^{xz}` prefactor,
/// while the shared table is written for `P(x,z) = i^{xz} X^x Z^z`. Since
/// `X^a Z^b = i^{-ab} P(a,b)`,
///
/// ```text
/// c = g(a,b,f,m) + (a⊕f)(b⊕m) − ab − fm   (mod 4).
/// ```
///
/// The alternative — writing `c = 2·b·f` directly — would be a second copy
/// of the same physics in a second convention, which is the duplication the
/// `pauli_mult_phase` doc comment forbids by name. Calling through means a
/// corrupted entry of that table corrupts amplitudes here too, which is what
/// `tests/mutation_phase_table.rs` documents.
pub(crate) fn plain_mult_phase(a: bool, b: bool, f: bool, m: bool) -> u32 {
    let bit = |x: bool| i32::from(x);
    let g = pauli_mult_phase(a, b, f, m);
    let shim = bit(a ^ f) * bit(b ^ m) - bit(a) * bit(b) - bit(f) * bit(m);
    (((g + shim) % 4 + 4) % 4) as u32
}

/// `i^k`.
fn pow_i(k: u32) -> Complex64 {
    match k % 4 {
        0 => Complex64::new(1.0, 0.0),
        1 => Complex64::new(0.0, 1.0),
        2 => Complex64::new(-1.0, 0.0),
        _ => Complex64::new(0.0, -1.0),
    }
}

/// `1/√2`, named so the two places that scale by it cannot drift apart.
const ISQRT2: f64 = std::f64::consts::FRAC_1_SQRT_2;

/// A stabilizer state in CH form, carrying its exact global phase.
#[derive(Clone, Debug)]
pub struct ChForm {
    n: usize,
    /// `F[p][q]`: X-part of `U_C† X_p U_C`.
    f: Vec<Vec<bool>>,
    /// `G[p][q]`: `U_C† Z_p U_C = ⊗_q Z^{G[p][q]}`.
    g: Vec<Vec<bool>>,
    /// `M[p][q]`: Z-part of `U_C† X_p U_C`.
    m: Vec<Vec<bool>>,
    /// `γ[p] ∈ Z_4`: the power of `i` on `U_C† X_p U_C`.
    gamma: Vec<u32>,
    /// `v[q]`: a Hadamard sits on wire `q` between `U_C` and `|s⟩`.
    v: Vec<bool>,
    /// The basis string under the Hadamard layer.
    s: Vec<bool>,
    /// Global phase. Unit modulus for any state this kernel produces.
    omega: Complex64,
}

impl ChForm {
    /// `|0…0⟩`: `U_C = U_H = I`, `ω = 1`.
    pub fn zero(n: usize) -> Self {
        let eye = |p: usize| (0..n).map(|q| p == q).collect::<Vec<bool>>();
        Self {
            n,
            f: (0..n).map(eye).collect(),
            g: (0..n).map(eye).collect(),
            m: vec![vec![false; n]; n],
            gamma: vec![0; n],
            v: vec![false; n],
            s: vec![false; n],
            omega: Complex64::new(1.0, 0.0),
        }
    }

    pub fn num_qubits(&self) -> usize {
        self.n
    }

    /// The global phase factor currently carried. Exposed so a caller can
    /// assert on it directly rather than inferring it from an amplitude.
    pub fn global_phase(&self) -> Complex64 {
        self.omega
    }

    /// Multiply `ω` by a scalar. The gate methods owe their own phases and
    /// pay them internally; this is for a caller composing a gate out of them
    /// — S1's Clifford-angle Pauli rotation is `e^{∓iπ/4}` times a conjugated
    /// `S`, and that leading scalar is a *per-branch* phase, not a global one.
    pub fn scale_phase(&mut self, z: Complex64) {
        self.omega *= z;
    }

    // ---------------------------------------------------------------- //
    // Amplitudes                                                       //
    // ---------------------------------------------------------------- //

    /// `⟨x|φ⟩`, exact phase included, in `O(n²)`.
    ///
    /// `U_C† |x⟩ = U_C† (∏_p X_p^{x_p}) U_C |0⟩ = i^e |xF⟩`, because `U_C`
    /// fixes `|0…0⟩` and every `Z` in the accumulated product dies on it.
    /// The accumulation is a plain Pauli product, so it runs through
    /// [`plain_mult_phase`]. Then `⟨x|U_C = conj(i^e) ⟨xF|`, and
    /// `⟨t|U_H|s⟩` factorises wire by wire: a `v = 0` wire is a Kronecker
    /// delta, a `v = 1` wire contributes `(-1)^{t_q s_q}/√2`.
    pub fn amplitude(&self, x: &[bool]) -> Complex64 {
        assert_eq!(x.len(), self.n, "amplitude: bitstring width mismatch");
        let n = self.n;
        let mut xpart = vec![false; n];
        let mut zpart = vec![false; n];
        let mut e = 0u32;
        for p in 0..n {
            if !x[p] {
                continue;
            }
            e = (e + self.gamma[p]) % 4;
            for q in 0..n {
                e = (e + plain_mult_phase(xpart[q], zpart[q], self.f[p][q], self.m[p][q])) % 4;
                xpart[q] ^= self.f[p][q];
                zpart[q] ^= self.m[p][q];
            }
        }

        let mut sign = false;
        let mut hadamards = 0u32;
        for q in 0..n {
            if self.v[q] {
                hadamards += 1;
                sign ^= xpart[q] && self.s[q];
            } else if xpart[q] != self.s[q] {
                return Complex64::new(0.0, 0.0);
            }
        }
        let mag = ISQRT2.powi(hadamards as i32) * if sign { -1.0 } else { 1.0 };
        self.omega * pow_i((4 - e % 4) % 4) * mag
    }

    /// Every amplitude, in computational-basis order with wire `q` at bit
    /// `q` — the indexing `omega-backend-statevector` uses. `O(4^n)`; for
    /// tests and small cross-checks only.
    pub fn to_statevector(&self) -> Vec<Complex64> {
        (0..1usize << self.n)
            .map(|i| {
                let x: Vec<bool> = (0..self.n).map(|q| (i >> q) & 1 == 1).collect();
                self.amplitude(&x)
            })
            .collect()
    }

    // ---------------------------------------------------------------- //
    // Left multiplication: applying a gate to the state                //
    // ---------------------------------------------------------------- //

    /// `S_q`. `S† X S = −Y = i³ X Z`, so row `q` of the X-image picks up
    /// `i³` and absorbs the Z-image: `M_q ⊕= G_q`, `γ_q += 3`. `S† Z S = Z`
    /// leaves `G` alone.
    pub fn s_gate(&mut self, q: usize) {
        self.gamma[q] = (self.gamma[q] + 3) % 4;
        for j in 0..self.n {
            let gq = self.g[q][j];
            self.m[q][j] ^= gq;
        }
    }

    /// `S†_q`. `S X S† = +Y = i¹ X Z` — the same row update with `γ_q += 1`.
    /// Note this is NOT `s_gate` with a blanket sign flip.
    pub fn sdg_gate(&mut self, q: usize) {
        self.gamma[q] = (self.gamma[q] + 1) % 4;
        for j in 0..self.n {
            let gq = self.g[q][j];
            self.m[q][j] ^= gq;
        }
    }

    /// `Z_q = S_q²`: `Z† X Z = −X`, nothing else moves.
    pub fn z_gate(&mut self, q: usize) {
        self.gamma[q] = (self.gamma[q] + 2) % 4;
    }

    /// `CZ(a,b)`. `CZ X_a CZ = X_a Z_b`, so row `a` absorbs `G_b` and row
    /// `b` absorbs `G_a`. No phase: `a ≠ b` means `F_a·G_b = 0`.
    pub fn cz_gate(&mut self, a: usize, b: usize) {
        assert_ne!(a, b, "cz: control and target must differ");
        for j in 0..self.n {
            let (ga, gb) = (self.g[a][j], self.g[b][j]);
            self.m[a][j] ^= gb;
            self.m[b][j] ^= ga;
        }
    }

    /// `CX(c → t)`. `CX X_c CX = X_c X_t` multiplies row `c` of the X-image
    /// by row `t` — a genuine Pauli product, hence the phase accumulation
    /// through [`plain_mult_phase`]. `CX Z_t CX = Z_c Z_t` gives
    /// `G_t ⊕= G_c`.
    pub fn cx_gate(&mut self, c: usize, t: usize) {
        assert_ne!(c, t, "cx: control and target must differ");
        let mut e = (self.gamma[c] + self.gamma[t]) % 4;
        for j in 0..self.n {
            e = (e + plain_mult_phase(self.f[c][j], self.m[c][j], self.f[t][j], self.m[t][j])) % 4;
        }
        self.gamma[c] = e;
        for j in 0..self.n {
            let (ft, mt, gc) = (self.f[t][j], self.m[t][j], self.g[c][j]);
            self.f[c][j] ^= ft;
            self.m[c][j] ^= mt;
            self.g[t][j] ^= gc;
        }
    }

    /// `X_q`. `X` cannot be folded into `U_C`: it maps `Z_q ↦ −Z_q`, and the
    /// `G` rows have no sign bit (by design — `U_C ∈ ⟨CX, CZ, S⟩` fixes
    /// `|0…0⟩`). So it is pushed through instead:
    /// `X_q|φ⟩ = ω U_C (U_C† X_q U_C) U_H |s⟩`, and the resulting Pauli acts
    /// on the product state `U_H|s⟩` by flipping bits and emitting a sign.
    /// On a `v = 1` wire the Pauli commutes past the Hadamard with X and Z
    /// exchanged, which is why `F` and `M` swap roles there.
    pub fn x_gate(&mut self, q: usize) {
        let mut beta = false;
        for j in 0..self.n {
            if self.v[j] {
                beta ^= self.f[q][j] && self.s[j];
                beta ^= self.f[q][j] && self.m[q][j];
                self.s[j] ^= self.m[q][j];
            } else {
                beta ^= self.m[q][j] && self.s[j];
                self.s[j] ^= self.f[q][j];
            }
        }
        self.omega *= pow_i(self.gamma[q]) * if beta { -1.0 } else { 1.0 };
    }

    /// `Y_q = i X_q Z_q` — the `i` is the point, so it is written out.
    pub fn y_gate(&mut self, q: usize) {
        self.z_gate(q);
        self.x_gate(q);
        self.omega *= Complex64::new(0.0, 1.0);
    }

    /// `√X = H S H` exactly, matrix for matrix — not up to phase. (Both
    /// sides equal ½[[1+i, 1−i], [1−i, 1+i]].)
    pub fn sx_gate(&mut self, q: usize) {
        self.h_gate(q);
        self.s_gate(q);
        self.h_gate(q);
    }

    /// `√X† = H S† H`, by conjugate transpose of [`ChForm::sx_gate`].
    pub fn sxdg_gate(&mut self, q: usize) {
        self.h_gate(q);
        self.sdg_gate(q);
        self.h_gate(q);
    }

    /// `SWAP(a,b)` as three CNOTs.
    pub fn swap_gate(&mut self, a: usize, b: usize) {
        self.cx_gate(a, b);
        self.cx_gate(b, a);
        self.cx_gate(a, b);
    }

    /// `CY(c,t) = (I⊗S) CX (I⊗S†)` — forward order puts `S†` first.
    pub fn cy_gate(&mut self, c: usize, t: usize) {
        self.sdg_gate(t);
        self.cx_gate(c, t);
        self.s_gate(t);
    }

    /// `H_q`, the one gate that leaves `⟨CX, CZ, S⟩`.
    ///
    /// `H_q U_C = U_C (U_C† H_q U_C)` and
    /// `U_C† H_q U_C = (P + Q)/√2` with `P = i^{γ_q} X^{F_q} Z^{M_q}` and
    /// `Q = Z^{G_q}`. Each of `P` and `Q` maps the product state `U_H|s⟩` to
    /// a signed product state `U_H|u⟩`, `U_H|t⟩`, so the whole gate reduces
    /// to a two-term superposition over the *same* Hadamard layer.
    ///
    /// When `t == u` the two terms land on one string and the result is a
    /// scalar. That scalar always has unit modulus: `t == u` forces
    /// `F_{qj} = 0` wherever `v_j = 0` and `M_{qj} = G_{qj}` wherever
    /// `v_j = 1`, so `F_q·M_q = F_q·G_q = 1` and the invariant
    /// `γ_q ≡ F_q·M_q` makes `γ_q` odd — the two terms are `±1` and `±i`,
    /// never equal. The debug assertion below pins that.
    ///
    /// Otherwise [`ChForm::desuperpose`] folds the two-term superposition
    /// back into the form.
    pub fn h_gate(&mut self, q: usize) {
        let n = self.n;

        // Q = Z^{G_q}: flips s on Hadamard wires, signs on the others.
        let mut t = self.s.clone();
        let mut alpha = false;
        for j in 0..n {
            if !self.g[q][j] {
                continue;
            }
            if self.v[j] {
                t[j] ^= true;
            } else {
                alpha ^= self.s[j];
            }
        }

        // P = i^{γ_q} X^{F_q} Z^{M_q}, with X and Z exchanged on Hadamard
        // wires because the Pauli is commuted past `U_H`.
        let mut u = self.s.clone();
        let mut beta = false;
        for j in 0..n {
            if self.v[j] {
                beta ^= self.f[q][j] && self.s[j];
                beta ^= self.f[q][j] && self.m[q][j];
                u[j] ^= self.m[q][j];
            } else {
                beta ^= self.m[q][j] && self.s[j];
                u[j] ^= self.f[q][j];
            }
        }

        if t == u {
            debug_assert_eq!(
                self.gamma[q] % 2,
                1,
                "h on wire {q}: the two branches collapsed with an even γ, which \
                 would scale the state by √2 — the CH-form invariants are broken"
            );
            let sa = if alpha { -1.0 } else { 1.0 };
            let sb = if beta { -1.0 } else { 1.0 };
            self.omega *= (Complex64::new(sa, 0.0) + pow_i(self.gamma[q]) * sb) * ISQRT2;
            // The surviving string is `t`, which is `s` only when the Pauli
            // part of `U_C† H_q U_C` happened to fix it.
            self.s = t;
            return;
        }

        // (-1)^α (|t⟩ + i^δ |u⟩)/√2 with δ = γ_q + 2(α+β).
        let delta = (self.gamma[q] + 2 * u32::from(alpha) + 2 * u32::from(beta)) % 4;
        if alpha {
            self.omega = -self.omega;
        }
        self.desuperpose(t, u, delta);
    }

    /// Rewrite `U_H(|t⟩ + i^δ|u⟩)/√2`, `t ≠ u`, back as `ω' V U_H' |s'⟩`
    /// with `V ∈ ⟨CX, CZ, S⟩` absorbed into `U_C` on the right.
    ///
    /// Let `d = t ⊕ u`. Pick a pivot `q` with `d_q = 1`, preferring a wire
    /// with `v_q = 0`. Then the network
    ///
    /// * `v_q = 0`: `CX(q→j)` for every other `d_j = 1, v_j = 0`, and
    ///   `CZ(q,j)` for every `d_j = 1, v_j = 1`;
    /// * `v_q = 1`: `CX(j→q)` for every other `d_j = 1` (all of which have
    ///   `v_j = 1` in this branch),
    ///
    /// acts on `U_H|z⟩` as "flip `z` on `d ⊕ e_q` when `z_q = 1`", because
    /// a `CZ` whose target sits under a Hadamard, and a `CNOT` both of whose
    /// wires do, are each a `CNOT` in the frame the basis string lives in.
    /// That collapses the superposition to the single wire `q`, where
    /// `(|0⟩ + i^δ|1⟩)/√2` is `S^δ H|0⟩` (if `v_q = 0`, so the wire gains a
    /// Hadamard) or `H(|0⟩ + i^δ|1⟩)/√2` (if `v_q = 1`), the latter being
    /// `|0⟩`, `e^{iπ/4} S†H|0⟩`, `|1⟩`, `e^{−iπ/4} S H|0⟩` for
    /// `δ = 0,1,2,3`. The two `e^{±iπ/4}` are the only places the global
    /// phase leaves the group `{±1, ±i}` — and the reason `ω` is a complex
    /// float rather than a `Z_8` counter.
    fn desuperpose(&mut self, mut t: Vec<bool>, mut u: Vec<bool>, mut delta: u32) {
        let n = self.n;
        let d: Vec<bool> = (0..n).map(|j| t[j] ^ u[j]).collect();
        let pivot = (0..n)
            .find(|&j| d[j] && !self.v[j])
            .or_else(|| (0..n).find(|&j| d[j]))
            .expect("desuperpose called with t == u");

        // The pivot wire must carry the |0⟩ leg; swapping the two legs
        // conjugates the relative phase.
        if t[pivot] {
            std::mem::swap(&mut t, &mut u);
            self.omega *= pow_i(delta);
            delta = (4 - delta % 4) % 4;
        }

        if !self.v[pivot] {
            for j in 0..n {
                if j == pivot || !d[j] {
                    continue;
                }
                if self.v[j] {
                    self.right_cz(pivot, j);
                } else {
                    self.right_cx(pivot, j);
                }
            }
            for _ in 0..delta {
                self.right_s(pivot);
            }
            self.v[pivot] = true;
            self.s = t;
        } else {
            for j in 0..n {
                if j == pivot || !d[j] {
                    continue;
                }
                debug_assert!(self.v[j], "pivot branch chose a non-Hadamard wire");
                self.right_cx(j, pivot);
            }
            match delta {
                0 => {
                    self.v[pivot] = false;
                    self.s = t;
                }
                2 => {
                    self.v[pivot] = false;
                    t[pivot] = true;
                    self.s = t;
                }
                1 => {
                    self.omega *= Complex64::new(ISQRT2, ISQRT2);
                    self.right_s(pivot);
                    self.right_s(pivot);
                    self.right_s(pivot);
                    self.s = t;
                }
                _ => {
                    self.omega *= Complex64::new(ISQRT2, -ISQRT2);
                    self.right_s(pivot);
                    self.s = t;
                }
            }
        }
    }

    // ---------------------------------------------------------------- //
    // Right multiplication: U_C ← U_C · W                              //
    // ---------------------------------------------------------------- //
    //
    // These conjugate the *stored* images by W instead of transforming the
    // Pauli being imaged, so they are column operations where the gate
    // methods above are row operations.

    /// `U_C ← U_C S_q`. `S† X^f Z^m S = i^{3f} X^f Z^{m⊕f}`.
    fn right_s(&mut self, q: usize) {
        for p in 0..self.n {
            if self.f[p][q] {
                self.m[p][q] ^= true;
                self.gamma[p] = (self.gamma[p] + 3) % 4;
            }
        }
    }

    /// `U_C ← U_C CZ(q,r)`. Each `X_q` gains a `Z_r` and vice versa; the
    /// reordering back into `X…Z…` form costs `(−1)^{f_q f_r}`.
    fn right_cz(&mut self, q: usize, r: usize) {
        for p in 0..self.n {
            let (fq, fr) = (self.f[p][q], self.f[p][r]);
            if fq && fr {
                self.gamma[p] = (self.gamma[p] + 2) % 4;
            }
            self.m[p][r] ^= fq;
            self.m[p][q] ^= fr;
        }
    }

    /// `U_C ← U_C CX(c→t)`. `X_c ↦ X_c X_t` and `Z_t ↦ Z_c Z_t`, with no
    /// reordering sign; the `G` columns move the other way round from the
    /// `F` columns, which is what keeps `F G^T = I`.
    fn right_cx(&mut self, c: usize, t: usize) {
        for p in 0..self.n {
            let (fc, mt, gt) = (self.f[p][c], self.m[p][t], self.g[p][t]);
            self.f[p][t] ^= fc;
            self.m[p][c] ^= mt;
            self.g[p][c] ^= gt;
        }
    }

    // ---------------------------------------------------------------- //
    // Inner products                                                   //
    // ---------------------------------------------------------------- //

    /// `⟨φ|φ′⟩`, phase included.
    ///
    /// `⟨φ|φ′⟩ = conj(ω) ⟨s| U_H U_C† |φ′⟩` (`U_H† = U_H`), so the bra's
    /// Clifford is **applied to the ket** and the whole thing lands on one
    /// amplitude. `U_C†` factorises as a diagonal phase polynomial followed
    /// by a linear reversible map, both of which are gate sequences this
    /// kernel already applies:
    ///
    /// * `U_C†|x⟩ = i^{e(x)}|xF⟩` with
    ///   `e(x) = Σ_p γ_p x_p + 2 Σ_{p′<p} (M_{p′}·F_p) x_p x_{p′}` — read
    ///   straight off the accumulation in [`ChForm::amplitude`]. The linear
    ///   term is `S_p` applied `γ_p` times, the quadratic term is a `CZ`
    ///   per odd coefficient.
    /// * `|x⟩ ↦ |xF⟩` is a CNOT network ([`cx_network`]).
    ///
    /// `O(n³)` gate applications of `O(n)`–`O(n²)` each. No sum over basis
    /// states anywhere, and no magnitude: the result is complex.
    pub fn inner_product(&self, other: &ChForm) -> Complex64 {
        assert_eq!(self.n, other.n, "inner_product: width mismatch");
        self.bra_program().overlap(other)
    }

    /// The bra half of [`ChForm::inner_product`], built once so it can meet
    /// many kets — see [`BraProgram`]. The gate list is exactly the
    /// factorisation that method's doc comment derives.
    pub fn bra_program(&self) -> BraProgram {
        let n = self.n;
        let mut ops = Vec::new();
        for p in 0..n {
            for _ in 0..self.gamma[p] {
                ops.push(BraOp::S(p));
            }
        }
        for p in 0..n {
            for pp in 0..p {
                let coupling = (0..n).filter(|&j| self.m[pp][j] && self.f[p][j]).count();
                if coupling % 2 == 1 {
                    ops.push(BraOp::Cz(pp, p));
                }
            }
        }
        for (c, t) in cx_network(&self.f) {
            ops.push(BraOp::Cx(c, t));
        }
        for q in 0..n {
            if self.v[q] {
                ops.push(BraOp::H(q));
            }
        }
        BraProgram {
            n,
            ops,
            s: self.s.clone(),
            omega_conj: self.omega.conj(),
        }
    }

    /// `⟨φ|P|φ′⟩` for a Pauli string `P` given as `(wire, letter)` pairs.
    /// Each wire may appear at most once; the letters commute, so the order
    /// of the slice is irrelevant.
    pub fn pauli_matrix_element(&self, paulis: &[(usize, PauliOp)], other: &ChForm) -> Complex64 {
        let mut k = other.clone();
        for &(q, p) in paulis {
            match p {
                PauliOp::I => {}
                PauliOp::X => k.x_gate(q),
                PauliOp::Y => k.y_gate(q),
                PauliOp::Z => k.z_gate(q),
            }
        }
        self.inner_product(&k)
    }

    /// `⟨φ|P|φ⟩`, which is real for a Hermitian `P` on a normalised state.
    /// The imaginary part is returned to the caller's assertion rather than
    /// silently dropped.
    pub fn pauli_expectation(&self, paulis: &[(usize, PauliOp)]) -> Complex64 {
        self.pauli_matrix_element(paulis, self)
    }

    /// `F G^T = I` and `γ_p ≡ F_p·M_p (mod 2)`. Both hold for every state
    /// reachable by the gate methods; a violation means an update rule is
    /// wrong, not that the caller did something unusual.
    pub fn check_invariants(&self) -> Result<(), String> {
        let n = self.n;
        for p in 0..n {
            for r in 0..n {
                let dot = (0..n).filter(|&j| self.f[p][j] && self.g[r][j]).count() % 2 == 1;
                if dot != (p == r) {
                    return Err(format!("F·Gᵀ is not the identity at ({p},{r})"));
                }
            }
            let fm = (0..n).filter(|&j| self.f[p][j] && self.m[p][j]).count() % 2;
            if fm as u32 != self.gamma[p] % 2 {
                return Err(format!(
                    "γ[{p}] = {} contradicts F·M = {fm} (the image of X_{p} is not Hermitian)",
                    self.gamma[p]
                ));
            }
        }
        Ok(())
    }
}

/// One gate of a [`BraProgram`].
#[derive(Debug, Clone, Copy)]
enum BraOp {
    S(usize),
    Cz(usize, usize),
    Cx(usize, usize),
    H(usize),
}

/// Everything [`ChForm::inner_product`] derives from its **bra**, hoisted out
/// of the loop: the `U_C†` phase polynomial, the CNOT network of
/// [`cx_network`] and the Hadamard layer, as a gate list to be run on the ket.
///
/// S1's readout is the χ² double sum `Σᵢⱼ c̄ᵢcⱼ⟨φᵢ|O|φⱼ⟩`, so one bra meets χ
/// different kets. Building the list per pair would repeat `cx_network` and
/// the `M·F` coupling counts — both `O(n³)` — χ times for the same answer.
/// Nothing about the arithmetic changes: `inner_product` is this type's
/// [`overlap`](BraProgram::overlap) on a program of one use, which is what
/// keeps the two paths from drifting.
pub struct BraProgram {
    n: usize,
    ops: Vec<BraOp>,
    s: Vec<bool>,
    omega_conj: Complex64,
}

impl BraProgram {
    /// `⟨φ|k⟩` for the ket `k`, phase included.
    pub fn overlap(&self, ket: &ChForm) -> Complex64 {
        assert_eq!(self.n, ket.n, "overlap: width mismatch");
        let mut k = ket.clone();
        for &op in &self.ops {
            match op {
                BraOp::S(q) => k.s_gate(q),
                BraOp::Cz(a, b) => k.cz_gate(a, b),
                BraOp::Cx(c, t) => k.cx_gate(c, t),
                BraOp::H(q) => k.h_gate(q),
            }
        }
        self.omega_conj * k.amplitude(&self.s)
    }
}

/// A CNOT network realising `|x⟩ ↦ |xF⟩` for invertible `F` over `F_2`.
///
/// `CX(c→t)` is right multiplication of the row vector `x` by
/// `E_{ct} = I + e_c e_tᵀ`, and left multiplication of a matrix by `E_{ct}`
/// adds row `t` to row `c`. So reducing `F` to the identity with row
/// additions `L_m ⋯ L_1 F = I` gives `F = L_1 ⋯ L_m` (each `L` is its own
/// inverse over `F_2`), and the recorded operations are the gates **in the
/// order recorded**.
fn cx_network(f: &[Vec<bool>]) -> Vec<(usize, usize)> {
    let n = f.len();
    let mut a: Vec<Vec<bool>> = f.to_vec();
    let mut ops: Vec<(usize, usize)> = Vec::new();
    for col in 0..n {
        if !a[col][col] {
            // A pivot at or below the diagonal always exists: columns
            // `< col` are already `e_0 … e_{col−1}`, so the remaining block
            // is invertible.
            let r = (col + 1..n)
                .find(|&r| a[r][col])
                .expect("cx_network: F is singular, which the CH-form forbids");
            for j in 0..n {
                let bit = a[r][j];
                a[col][j] ^= bit;
            }
            ops.push((col, r));
        }
        for r in 0..n {
            if r != col && a[r][col] {
                for j in 0..n {
                    let bit = a[col][j];
                    a[r][j] ^= bit;
                }
                ops.push((r, col));
            }
        }
    }
    ops
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The convention shim is an identity, not a second table: for all 16
    /// input cells the AG `g` plus the correction equals `2·b·f`, the phase
    /// of `X^aZ^b · X^fZ^m` in this kernel's convention.
    #[test]
    fn the_convention_shim_reproduces_the_plain_product_phase() {
        for a in [false, true] {
            for b in [false, true] {
                for f in [false, true] {
                    for m in [false, true] {
                        let want = 2 * u32::from(b && f);
                        assert_eq!(
                            plain_mult_phase(a, b, f, m),
                            want,
                            "X^{} Z^{} · X^{} Z^{}",
                            u8::from(a),
                            u8::from(b),
                            u8::from(f),
                            u8::from(m)
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn cx_network_realises_the_linear_map() {
        // A fixed invertible 4×4 over F_2, plus the identity and a swap.
        let mats = [
            vec![
                vec![true, false, false, false],
                vec![false, true, false, false],
                vec![false, false, true, false],
                vec![false, false, false, true],
            ],
            vec![
                vec![false, true, false, false],
                vec![true, false, false, false],
                vec![false, false, false, true],
                vec![false, false, true, false],
            ],
            vec![
                vec![true, true, false, true],
                vec![false, true, true, false],
                vec![false, false, true, true],
                vec![true, false, false, true],
            ],
        ];
        for f in mats {
            let n = f.len();
            let ops = cx_network(&f);
            for i in 0..1usize << n {
                let x: Vec<bool> = (0..n).map(|q| (i >> q) & 1 == 1).collect();
                let mut y = x.clone();
                for &(c, t) in &ops {
                    let bit = y[c];
                    y[t] ^= bit;
                }
                let want: Vec<bool> = (0..n)
                    .map(|j| (0..n).filter(|&p| x[p] && f[p][j]).count() % 2 == 1)
                    .collect();
                assert_eq!(y, want, "cx_network mismatch on x = {x:?}");
            }
        }
    }
}
