//! Export circuits + annotations to Rocq/Coq for formal verification.

use super::annotation::*;
use super::nodes::*;

/// Export a Circuit to a Rocq/Coq source string.
pub fn to_rocq(circuit: &Circuit) -> String {
    let mut lines = vec![
        "(* Auto-generated by the Aria Quantum Language *)".to_string(),
        "(* Verify with: dune build *)".to_string(),
        String::new(),
        "Require Import Reals.".to_string(),
        "Require Import Lra.".to_string(),
        "Open Scope R_scope.".to_string(),
        String::new(),
    ];

    let n = circuit.n_qubits();

    // Circuit as gate list
    lines.push(format!(
        "(** Circuit '{}': {} qubits, {} gates, depth {} *)",
        circuit.name,
        n,
        circuit.gate_count(),
        circuit.depth()
    ));
    lines.push(format!("Definition {} :=", sanitize_coq(&circuit.name)));

    let gate_strs: Vec<String> = circuit
        .instructions
        .iter()
        .filter(|inst| !inst.gate.kind.is_meta())
        .filter_map(gate_to_rocq)
        .collect();

    if gate_strs.is_empty() {
        lines.push("  nil.".to_string());
    } else {
        for (i, g) in gate_strs.iter().enumerate() {
            if i == 0 {
                lines.push(format!("  ({}", g));
            } else {
                lines.push(format!("   :: {}", g));
            }
        }
        lines.push("   :: nil).".to_string());
    }
    lines.push(String::new());

    // Annotations → theorem stubs
    for ann in &circuit.annotations {
        match ann {
            Annotation::Assert(prop) => {
                let stmt = property_to_rocq(prop, &sanitize_coq(&circuit.name));
                lines.push(format!("(** Assert: {} *)", prop));
                lines.push(format!(
                    "Theorem assert_{} : {}.",
                    sanitize_coq(&format!("{prop}")),
                    stmt
                ));
                lines.push("Proof. Admitted.".to_string());
                lines.push(String::new());
            }
            Annotation::Prove { name, property } => {
                let stmt = property_to_rocq(property, &sanitize_coq(&circuit.name));
                lines.push(format!("(** Prove: {} *)", name));
                lines.push(format!("Theorem {} : {}.", sanitize_coq(name), stmt));
                lines.push("Proof. Admitted.".to_string());
                lines.push(String::new());
            }
            Annotation::Comment(s) => {
                lines.push(format!("(* {s} *)"));
            }
            _ => {}
        }
    }

    lines.join("\n") + "\n"
}

fn gate_to_rocq(inst: &Instruction) -> Option<String> {
    match inst.gate.kind {
        GateKind::H => Some(format!("H {}", inst.qubits[0].index)),
        GateKind::X => Some(format!("X {}", inst.qubits[0].index)),
        GateKind::Y => Some(format!("Y {}", inst.qubits[0].index)),
        GateKind::Z => Some(format!("Z {}", inst.qubits[0].index)),
        GateKind::S => Some(format!("S {}", inst.qubits[0].index)),
        GateKind::T => Some(format!("T {}", inst.qubits[0].index)),
        GateKind::CX => Some(format!(
            "CNOT {} {}",
            inst.qubits[0].index, inst.qubits[1].index
        )),
        GateKind::CZ => Some(format!(
            "CZ {} {}",
            inst.qubits[0].index, inst.qubits[1].index
        )),
        GateKind::RZ => {
            let theta = inst
                .gate
                .params
                .first()
                .and_then(|p| p.try_as_f64())
                .unwrap_or(0.0);
            Some(format!("Rz {} {}", inst.qubits[0].index, theta))
        }
        _ => None,
    }
}

fn property_to_rocq(prop: &Property, circuit_name: &str) -> String {
    match prop {
        Property::Unitary => format!("is_unitary (denote {})", circuit_name),
        Property::SelfInverse => format!("denote {0} * denote {0} = I", circuit_name),
        Property::Equiv { description } => {
            format!("denote {} = denote {}", circuit_name, description)
        }
        Property::Custom(expr) => expr.clone(),
        _ => format!("True (* {} *)", prop),
    }
}

fn sanitize_coq(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::CircuitBuilder;

    #[test]
    fn test_to_rocq_bell() {
        let mut circ = CircuitBuilder::new("bell", 2, 0).h(0).cx(0, 1).build();
        circ.annotate(Annotation::Assert(Property::Unitary));

        let coq = to_rocq(&circ);
        assert!(coq.contains("Require Import Reals"));
        assert!(coq.contains("Definition bell"));
        assert!(coq.contains("H 0"));
        assert!(coq.contains("CNOT 0 1"));
        assert!(coq.contains("is_unitary"));
        assert!(coq.contains("Admitted"));
    }

    #[test]
    fn test_to_rocq_with_prove() {
        let mut circ = CircuitBuilder::new("grover", 2, 0).h(0).h(1).build();
        circ.annotate(Annotation::Prove {
            name: "grover_correct".into(),
            property: Property::Custom("success_probability grover >= 0.99".into()),
        });

        let coq = to_rocq(&circ);
        assert!(coq.contains("Theorem grover_correct"));
        assert!(coq.contains("success_probability"));
    }
}
