//! Export circuits + annotations to Lean 4 for formal verification.
//!
//! Generates Lean 4 source files with:
//! - Circuit definition as a list of `GateApp` values
//! - Annotations as theorem stubs (sorry placeholders)
//! - Import of QuantumProofs modules

use super::annotation::{Annotation, CmpOp, Property};
use super::nodes::*;

/// Export a Circuit to a Lean 4 source string.
pub fn to_lean4(circuit: &Circuit) -> String {
    let mut lines = vec![
        "-- Auto-generated by the Aria Quantum Language".to_string(),
        "-- Verify with: lake build".to_string(),
        String::new(),
        "import QuantumProofs.CircuitSemantics".to_string(),
        "import QuantumProofs.Gates".to_string(),
        String::new(),
        format!("namespace Exported.{}", sanitize_lean(&circuit.name)),
        String::new(),
        format!("open QuantumProofs.CircuitSemantics"),
        String::new(),
    ];

    let n = circuit.n_qubits();

    // Circuit definition
    lines.push(format!(
        "/-- Circuit '{}': {} qubits, {} gates, depth {} -/",
        circuit.name,
        n,
        circuit.gate_count(),
        circuit.depth()
    ));
    lines.push(render_circuit_def(circuit));
    lines.push(String::new());

    // Resource metrics
    lines.push(format!("/-- Gate count: {} -/", circuit.gate_count()));
    lines.push(format!("/-- Circuit depth: {} -/", circuit.depth()));
    lines.push(String::new());

    // Annotations → theorem stubs
    for (idx, ann) in circuit.annotations.iter().enumerate() {
        match ann {
            Annotation::Assert(prop) => {
                let (stmt, _) = property_to_lean4(prop, "circuit", n);
                lines.push(format!("/-- Asserted: {} -/", prop));
                lines.push(format!(
                    "theorem assert_{}_{} : {} := by",
                    sanitize_lean(&format!("{prop}")),
                    idx,
                    stmt
                ));
                lines.push("  sorry".to_string());
                lines.push(String::new());
            }
            Annotation::Assume(prop) => {
                let (stmt, _) = property_to_lean4(prop, "circuit", n);
                lines.push(format!("/-- Assumed: {} -/", prop));
                lines.push(format!(
                    "axiom assume_{}_{} : {}",
                    sanitize_lean(&format!("{prop}")),
                    idx,
                    stmt
                ));
                lines.push(String::new());
            }
            Annotation::Requires(prop) => {
                let (stmt, _) = property_to_lean4(prop, "circuit", n);
                lines.push(format!("/-- Precondition: {} -/", prop));
                lines.push(format!(
                    "theorem requires_{}_{} : {} := by",
                    sanitize_lean(&format!("{prop}")),
                    idx,
                    stmt
                ));
                lines.push("  sorry".to_string());
                lines.push(String::new());
            }
            Annotation::Ensures(prop) => {
                let (stmt, _) = property_to_lean4(prop, "circuit", n);
                lines.push(format!("/-- Postcondition: {} -/", prop));
                lines.push(format!(
                    "theorem ensures_{}_{} : {} := by",
                    sanitize_lean(&format!("{prop}")),
                    idx,
                    stmt
                ));
                lines.push("  sorry".to_string());
                lines.push(String::new());
            }
            Annotation::Invariant(prop) => {
                let (stmt, _) = property_to_lean4(prop, "circuit", n);
                lines.push(format!("/-- Loop invariant: {} -/", prop));
                lines.push(format!(
                    "theorem invariant_{}_{} : {} := by",
                    sanitize_lean(&format!("{prop}")),
                    idx,
                    stmt
                ));
                lines.push("  sorry".to_string());
                lines.push(String::new());
            }
            Annotation::Prove { name, property } => {
                let (stmt, _) = property_to_lean4(property, "circuit", n);
                lines.push(format!("/-- Prove: {} — {} -/", name, property));
                lines.push(format!("theorem {} : {} := by", sanitize_lean(name), stmt));
                lines.push("  sorry".to_string());
                lines.push(String::new());
            }
            Annotation::ResourceBound { metric, bound } => {
                if let Some(b) = bound.try_as_f64() {
                    let b_int = b as usize;
                    let actual = compute_metric(circuit, metric);
                    lines.push(format!(
                        "/-- Resource bound: {} ≤ {} (actual: {}) -/",
                        metric, b_int, actual
                    ));
                    let metric_lean = sanitize_lean(metric);
                    // Decidable bound: emit a `decide` proof on the actual value.
                    lines.push(format!(
                        "theorem {}_bound_{} : {} ≤ {} := by decide",
                        metric_lean, idx, actual, b_int
                    ));
                    lines.push(String::new());
                }
            }
            Annotation::Comment(s) => {
                lines.push(format!("-- {s}"));
            }
        }
    }

    lines.push(format!("end Exported.{}", sanitize_lean(&circuit.name)));
    lines.join("\n") + "\n"
}

/// Emit just the `def circuit : Circuit n := [...]` block — the gate-model
/// circuit literal, without the file header / namespace / theorems. Opens
/// nothing itself; the caller must `open QuantumProofs.CircuitSemantics`.
pub fn render_circuit_def(circuit: &Circuit) -> String {
    let n = circuit.n_qubits();
    let gate_strs: Vec<String> = circuit
        .instructions
        .iter()
        .filter(|inst| !inst.gate.kind.is_meta())
        .filter_map(|inst| gate_to_lean4(inst, n))
        .collect();
    let body = if gate_strs.is_empty() {
        "  []".to_string()
    } else {
        format!("  [{}]", gate_strs.join(",\n   "))
    };
    format!("def circuit : Circuit {n} :=\n{body}")
}

fn gate_to_lean4(inst: &Instruction, _n: usize) -> Option<String> {
    let q_idx = |q: &Qubit| -> String {
        // We need to figure out the global qubit index
        // For simplicity, use the register index directly
        format!("⟨{}, by omega⟩", q.index)
    };

    match inst.gate.kind {
        GateKind::H => Some(format!(".h {}", q_idx(&inst.qubits[0]))),
        GateKind::X => Some(format!(".x {}", q_idx(&inst.qubits[0]))),
        GateKind::Y => Some(format!(".y {}", q_idx(&inst.qubits[0]))),
        GateKind::Z => Some(format!(".z {}", q_idx(&inst.qubits[0]))),
        GateKind::S => Some(format!(".s {}", q_idx(&inst.qubits[0]))),
        GateKind::T => Some(format!(".t {}", q_idx(&inst.qubits[0]))),
        GateKind::RZ => {
            let theta = inst
                .gate
                .params
                .first()
                .and_then(|p| p.try_as_f64())
                .unwrap_or(0.0);
            Some(format!(".rz {} {}", q_idx(&inst.qubits[0]), theta))
        }
        GateKind::RY => {
            let theta = inst
                .gate
                .params
                .first()
                .and_then(|p| p.try_as_f64())
                .unwrap_or(0.0);
            Some(format!(".ry {} {}", q_idx(&inst.qubits[0]), theta))
        }
        // `GateApp.cx`/`.cz` carry a `ctrl ≠ tgt` proof (CircuitSemantics, the
        // two-qubit well-formedness invariant); `by decide` discharges it for
        // the concrete distinct literal indices.
        GateKind::CX => Some(format!(
            ".cx {} {} (by decide)",
            q_idx(&inst.qubits[0]),
            q_idx(&inst.qubits[1])
        )),
        GateKind::CZ => Some(format!(
            ".cz {} {} (by decide)",
            q_idx(&inst.qubits[0]),
            q_idx(&inst.qubits[1])
        )),
        _ => None,
    }
}

fn property_to_lean4(prop: &Property, circuit_name: &str, _n: usize) -> (String, String) {
    match prop {
        Property::Unitary => (
            format!("is_unitary (denote {circuit_name})"),
            "unitary".to_string(),
        ),
        Property::SelfInverse => (
            format!("denote {circuit_name} * denote {circuit_name} = 1"),
            "self_inverse".to_string(),
        ),
        Property::Hermitian => (
            format!("(denote {circuit_name})† = denote {circuit_name}"),
            "hermitian".to_string(),
        ),
        Property::Equiv { description } => (
            format!("denote {circuit_name} = denote {description}"),
            format!("equiv_{description}"),
        ),
        Property::OutputState { input, expected } => (
            format!("apply (denote {circuit_name}) {input} = {expected}"),
            "output_state".to_string(),
        ),
        Property::Probability {
            qubit,
            outcome,
            op,
            bound,
        } => {
            let cmp = match op {
                CmpOp::Ge => "≥",
                CmpOp::Le => "≤",
                CmpOp::Eq => "=",
                CmpOp::Gt => ">",
                CmpOp::Lt => "<",
            };
            let b = bound.try_as_f64().unwrap_or(0.0);
            (
                format!("prob {circuit_name} {qubit} {outcome} {cmp} {b}"),
                "probability".to_string(),
            )
        }
        Property::Custom(_expr) => (
            // The raw expression is often a dumped token stream from the
            // Aria parser (e.g. `StringLit("foo") Ident("bar") ...`) — not
            // valid Lean. Emit a trivially-provable placeholder so the
            // file type-checks; the human raw body is kept in the
            // comment line above the theorem.
            "True".to_string(),
            "custom".to_string(),
        ),
    }
}

/// Compute the actual value of a circuit metric. Used to emit
/// `decide`-provable resource bounds.
fn compute_metric(circuit: &Circuit, metric: &str) -> usize {
    match metric {
        "gate_count" => circuit.gate_count(),
        "depth" => circuit.depth(),
        "n_qubits" | "qubits" => circuit.n_qubits(),
        "t_count" => circuit
            .instructions
            .iter()
            .filter(|i| matches!(i.gate.kind, GateKind::T | GateKind::Tdg))
            .count(),
        "cnot_count" | "cx_count" => circuit
            .instructions
            .iter()
            .filter(|i| matches!(i.gate.kind, GateKind::CX))
            .count(),
        _ => circuit.gate_count(),
    }
}

// ===========================================================================
// Gate-model spec emitter.
//
// KEEP IN SYNC with the upstream copy in `quantum-core/src/spec.rs`
// (`gate_model_cert` / `render_gate_model_spec` / `safe_lean_ident`). This is a
// hand-synced fork: the recognizer + ident guard are byte-identical to upstream;
// only the emitted header banner differs (`aria export` vs `quantum spec
// extract`). When changing recognition logic, the cert fields, or the emitted
// theorem bodies, update BOTH. The committed `Generated/GateModel/Bell_Spec.lean`
// + the `gate_model_spec_matches_committed_bell_file` drift test pin the OSS
// output; the upstream repo has its own equivalent.
// ===========================================================================

/// A recognized gate-model circuit whose state-prep semantics are *proved*
/// sorry-free in the `proofs/lean4/QuantumProofs` tree — the data needed to emit
/// a closed `GateModel/<Name>_Spec.lean`. Each field is a fully qualified Lean
/// name in that tree.
struct GateModelCert {
    import: &'static str,
    library_circuit: &'static str,
    state_prep_thm: &'static str,
    amp: &'static str,
    prove_name: String,
    unitary_thm: Option<&'static str>,
    has_unitary_assert: bool,
}

/// Recognize a circuit whose gate-model correctness is proved in the
/// `QuantumProofs` tree. Today: the **Bell** circuit (`H@0; CX@(0,1)` on 2
/// qubits), closed by `QuantumProofs.BellPrep.{bell_state_prep_correct,
/// bell_unitary}`. Returns `None` otherwise (caller warns, never emits `sorry`).
fn gate_model_cert(circuit: &Circuit) -> Option<GateModelCert> {
    let gates: Vec<_> = circuit
        .instructions
        .iter()
        .filter(|i| !i.gate.kind.is_meta())
        .collect();
    let has_unitary_assert = circuit
        .annotations
        .iter()
        .any(|a| matches!(a, Annotation::Assert(Property::Unitary)));
    let prove_name = |default: &str| {
        circuit
            .annotations
            .iter()
            .find_map(|a| match a {
                Annotation::Prove { name, .. } => Some(safe_lean_ident(name, default)),
                _ => None,
            })
            .unwrap_or_else(|| default.to_string())
    };
    let q = |g: &&Instruction, i: usize| g.qubits.get(i).map(|q| q.index);
    // Bell: H@0; CX(0→1) on 2 qubits.
    if circuit.n_qubits() == 2 {
        if let [h, cx] = gates.as_slice() {
            if h.gate.kind == GateKind::H
                && q(h, 0) == Some(0)
                && cx.gate.kind == GateKind::CX
                && q(cx, 0) == Some(0)
                && q(cx, 1) == Some(1)
            {
                return Some(GateModelCert {
                    import: "QuantumProofs.BellPrep",
                    library_circuit: "QuantumProofs.BellPrep.bell_circuit",
                    state_prep_thm: "QuantumProofs.BellPrep.bell_state_prep_correct",
                    amp: "QuantumProofs.BellPrep.bellAmp",
                    prove_name: prove_name("bell_state_prep"),
                    unitary_thm: Some("QuantumProofs.BellPrep.bell_unitary"),
                    has_unitary_assert,
                });
            }
        }
    }
    // GHZ: H@0; CX(0→1); CX(1→2) on 3 qubits. `ghz_unitary` is now proved
    // (compositional unitarity in CircuitSemantics → `denote_is_unitary`), so an
    // `@assert unitary` on a GHZ circuit is CLOSED sorry-free, not dropped.
    if circuit.n_qubits() == 3 {
        if let [h, cx1, cx2] = gates.as_slice() {
            if h.gate.kind == GateKind::H
                && q(h, 0) == Some(0)
                && cx1.gate.kind == GateKind::CX
                && q(cx1, 0) == Some(0)
                && q(cx1, 1) == Some(1)
                && cx2.gate.kind == GateKind::CX
                && q(cx2, 0) == Some(1)
                && q(cx2, 1) == Some(2)
            {
                return Some(GateModelCert {
                    import: "QuantumProofs.GHZPrep",
                    library_circuit: "QuantumProofs.GHZPrep.ghz_circuit",
                    state_prep_thm: "QuantumProofs.GHZPrep.ghz_state_prep_correct",
                    amp: "QuantumProofs.GHZPrep.ghzAmp",
                    prove_name: prove_name("ghz_state_prep"),
                    unitary_thm: Some("QuantumProofs.GHZPrep.ghz_unitary"),
                    has_unitary_assert,
                });
            }
        }
    }
    None
}

/// Emit a **sorry-free** gate-model spec for a recognized circuit. The emitted
/// `circuit` is the same gate-list literal `to_lean4`/`render_circuit_def`
/// produce, proved definitionally equal (`rfl`) to the library circuit, and the
/// `@prove`/`@assert unitary` obligations are discharged by proved theorems in
/// the `QuantumProofs` tree — *not* `sorry`. Returns `None` for unrecognized
/// circuits. NOTE: the `@prove` name is used only as the theorem label; the
/// statement is the toolkit's canonical state-prep, not the free-form body.
pub fn render_gate_model_spec(circuit: &Circuit, name: &str) -> Option<String> {
    let cert = match gate_model_cert(circuit) {
        Some(c) => c,
        // QFT, QPE and Grover are recognized separately: their obligations are
        // not column-0 state-preps. QFT is a full-unitary `equiv` (`denote =
        // dft_matrix n`); QPE is a counting-register measurement faithfulness
        // (`counting_marginal … = 1`); Grover is an amplitude-amplification
        // success bound (`normSq (amplitude …) ≥ 1 − 1/N`). Each delegates to
        // its proved library theorem (`qftLowered_correct` / `qpe_faithful` /
        // `grover_gate_optimal_success`).
        None => {
            if let Some(n) = qft_recognized(circuit) {
                return Some(render_qft_equiv_spec(circuit, name, n));
            }
            if let Some(n) = qpe_recognized(circuit) {
                return Some(render_qpe_faithful_spec(name, n));
            }
            if grover_recognized(circuit).is_some() {
                return Some(render_grover_spec(name));
            }
            return None;
        }
    };
    let nm = sanitize_lean(name);
    let n = circuit.n_qubits();
    let mut out = String::new();
    out.push_str("-- Auto-generated by `aria export --gate-model` — DO NOT EDIT.\n");
    out.push_str("-- Gate-model state-preparation obligation: the emitted circuit is\n");
    out.push_str("-- definitionally the library circuit, and the toolkit's *canonical*\n");
    out.push_str("-- state-prep (+ unitary) obligation is CLOSED sorry-free by a proved\n");
    out.push_str("-- theorem in proofs/lean4/QuantumProofs (no `sorry`). The `@prove` name\n");
    out.push_str("-- is the theorem label only, not a translation of the free-form body.\n\n");
    out.push_str("import QuantumProofs.CircuitSemantics\n");
    out.push_str("import QuantumProofs.Gates\n");
    out.push_str(&format!("import {}\n\n", cert.import));
    out.push_str(&format!("namespace Exported.GateModel.{nm}\n\n"));
    out.push_str("open QuantumProofs QuantumProofs.CircuitSemantics\n\n");
    out.push_str(&format!(
        "/-- Gate-model circuit for `{name}` ({n} qubits). -/\n"
    ));
    out.push_str(&render_circuit_def(circuit));
    out.push_str("\n\n");
    out.push_str(&format!(
        "/-- The emitted circuit is definitionally the library circuit. -/\n\
         theorem circuit_eq : circuit = {lib} := rfl\n\n",
        lib = cert.library_circuit
    ));
    out.push_str(&format!(
        "/-- **State-preparation correctness** — column 0 of `denote circuit`\n    \
         (its action on |0…0⟩) matches `{amp}`. Closed sorry-free. (Name from the\n    \
         `@prove` label; statement is the toolkit's canonical state-prep.) -/\n\
         theorem {pname} :\n    \
         ∀ i : Fin (2^{n}), denote circuit i 0 = {amp} i := by\n  \
         rw [circuit_eq]; exact {prep}\n\n",
        amp = cert.amp,
        pname = cert.prove_name,
        prep = cert.state_prep_thm,
    ));
    if cert.has_unitary_assert {
        match cert.unitary_thm {
            Some(unit) => out.push_str(&format!(
                "/-- **@assert unitary** — `denote circuit` is unitary. Closed sorry-free. -/\n\
                 theorem circuit_unitary : is_unitary (denote circuit) := by\n  \
                 rw [circuit_eq]; exact {unit}\n\n",
            )),
            // Honest trace: the circuit was recognized, but no unitarity theorem is
            // proved for it, so the `@assert unitary` is NOT discharged here. Emit a
            // visible note rather than silently omitting it (the reader must not
            // conclude unitarity was verified).
            None => out.push_str(
                "-- NOTE: this recognized circuit carries `@assert unitary`, but no\n\
                 -- unitarity theorem is proved for it in QuantumProofs — the assertion\n\
                 -- is NOT discharged here (omitted, not verified).\n\n",
            ),
        }
    }
    out.push_str(&format!("end Exported.GateModel.{nm}\n"));
    Some(out)
}

/// Recognize the **QFT** circuit on `n` qubits — the gate list
/// `CircuitBuilder::qft` / `examples/aria/qft.aria` lower to. Returns `Some(n)`
/// iff `circuit`'s non-meta gates match the canonical QFT(n) gate-for-gate
/// (kind, wires, angles within `1e-9`), proved correct by
/// `QuantumProofs.QFTExport.qftLowered_correct`.
fn qft_recognized(circuit: &Circuit) -> Option<usize> {
    use crate::ast::CircuitBuilder;
    let n = circuit.n_qubits();
    if n == 0 {
        return None;
    }
    let gates: Vec<_> = circuit
        .instructions
        .iter()
        .filter(|i| !i.gate.kind.is_meta())
        .collect();
    if gates.is_empty() {
        return None;
    }
    let mut b = CircuitBuilder::new("qft_ref", n, 0);
    b.qft(&(0..n).collect::<Vec<_>>());
    let reference = b.build();
    let refg: Vec<_> = reference
        .instructions
        .iter()
        .filter(|i| !i.gate.kind.is_meta())
        .collect();
    if gates.len() != refg.len() {
        return None;
    }
    for (g, r) in gates.iter().zip(refg.iter()) {
        if g.gate.kind != r.gate.kind {
            return None;
        }
        let gq: Vec<usize> = g.qubits.iter().map(|q| q.index).collect();
        let rq: Vec<usize> = r.qubits.iter().map(|q| q.index).collect();
        if gq != rq {
            return None;
        }
        if g.gate.params.len() != r.gate.params.len() {
            return None;
        }
        for (pg, pr) in g.gate.params.iter().zip(r.gate.params.iter()) {
            match (pg.try_as_f64(), pr.try_as_f64()) {
                (Some(a), Some(c)) => {
                    if (a - c).abs() > 1e-9 {
                        return None;
                    }
                }
                _ => {
                    if pg != pr {
                        return None;
                    }
                }
            }
        }
    }
    Some(n)
}

/// Emit a **sorry-free** gate-model `equiv` spec for a recognized QFT(n): the
/// obligation `denote circuit = dft_matrix n` is closed by the proved
/// `QuantumProofs.QFTExport.qftLowered_correct n`. `circuit` is the library
/// symbolic `qftLowered n` (angles `π/2^k`), so there is no `rfl`-equality to a
/// numeric gate-list — `qft_recognized`'s structural match ties this circuit to
/// QFT(n).
fn render_qft_equiv_spec(circuit: &Circuit, name: &str, n: usize) -> String {
    let nm = sanitize_lean(name);
    let prove_name = circuit
        .annotations
        .iter()
        .find_map(|a| match a {
            Annotation::Prove { name, .. } => Some(safe_lean_ident(name, "qft_equiv_dft")),
            _ => None,
        })
        .unwrap_or_else(|| "qft_equiv_dft".to_string());
    let mut out = String::new();
    out.push_str("-- Auto-generated by `aria export --gate-model` — DO NOT EDIT.\n");
    out.push_str("-- Gate-model EQUIV obligation: the recognized circuit is the exporter-\n");
    out.push_str("-- lowered QFT(n), whose denotation is the exact size-2^n DFT matrix —\n");
    out.push_str("-- `denote (qftLowered n) = dft_matrix n`, CLOSED sorry-free by\n");
    out.push_str("-- `QuantumProofs.QFTExport.qftLowered_correct` (no `sorry`). NOTE: the\n");
    out.push_str("-- obligation is stated for the library symbolic QFT(n) (angles π/2^k);\n");
    out.push_str("-- `qft_recognized` verified the emitted circuit matches\n");
    out.push_str("-- `CircuitBuilder::qft(n)` gate-for-gate, so it IS that QFT. The `@prove`\n");
    out.push_str("-- name is the theorem label only.\n\n");
    out.push_str("import QuantumProofs.QFTExport\n\n");
    out.push_str(&format!("namespace Exported.GateModel.{nm}\n\n"));
    out.push_str(
        "open QuantumProofs.QFTExport QuantumProofs.QFT QuantumProofs.CircuitSemantics\n\n",
    );
    out.push_str(&format!(
        "/-- Gate-model circuit for `{name}` ({n} qubits): the exporter-lowered QFT,\n    \
         the library model `qftLowered {n}` (faithful to `CircuitBuilder::qft`). -/\n\
         noncomputable def circuit : Circuit {n} := qftLowered {n}\n\n"
    ));
    out.push_str(&format!(
        "/-- **QFT equiv correctness** — `denote circuit` is the exact DFT matrix.\n    \
         Closed sorry-free. (Name from the `@prove` label; statement is the\n    \
         toolkit's canonical QFT≡DFT obligation.) -/\n\
         theorem {prove_name} : denote circuit = dft_matrix {n} := qftLowered_correct {n}\n\n"
    ));
    out.push_str(&format!("end Exported.GateModel.{nm}\n"));
    out
}

/// The canonical **eigenstate-first** QPE(n) circuit the Lean `qpeCircuit n θ`
/// models: `X` on qubit 0 (eigenstate `|1⟩`), `H` on the `n` counting qubits
/// `1..n`, the controlled-phase cascade (`CP(0, k+1, 2π·φ·2^(n-1-k))`), then the
/// inverse-QFT on the counting register. The reference `qpe_recognized` matches
/// against, and the circuit the drift test builds.
fn qpe_canonical_circuit(n: usize, phi: f64) -> Circuit {
    use crate::ast::CircuitBuilder;
    let mut b = CircuitBuilder::new("qpe_ref", n + 1, 0);
    b.x(0);
    for k in 0..n {
        b.h(k + 1);
    }
    for k in 0..n {
        let w = (1u64 << (n - 1 - k)) as f64;
        b.cp(0, k + 1, 2.0 * std::f64::consts::PI * phi * w);
    }
    b.inverse_qft(&(1..=n).collect::<Vec<_>>());
    b.build()
}

/// Recognize the **eigenstate-first** QPE(n) circuit on `n+1` qubits (eigenstate
/// on qubit 0, counting register on `1..n`) that the proved `qpeCircuit n θ`
/// models. Returns `Some(n)` (the counting-register width) iff the circuit
/// matches `qpe_canonical_circuit(n, φ)` gate-for-gate — `X` prep, `H` layer,
/// controlled-phase cascade with the `2^(n-1-k)` weights, and the inverse-QFT —
/// with `φ` read off the first cascade `CP`. Mirrors `qft_recognized`.
fn qpe_recognized(circuit: &Circuit) -> Option<usize> {
    let n_total = circuit.n_qubits();
    if n_total < 2 {
        return None;
    }
    let n = n_total - 1;
    let gates: Vec<_> = circuit
        .instructions
        .iter()
        .filter(|i| !i.gate.kind.is_meta())
        .collect();
    // Need at least X(0) + n·H + the first cascade CP to read φ.
    if gates.len() < n + 2 {
        return None;
    }
    // φ from the first cascade CP (index 1+n): angle = 2π·φ·2^(n-1).
    let cp0 = gates[1 + n];
    if cp0.gate.kind != GateKind::CP {
        return None;
    }
    let a0 = cp0.gate.params.first().and_then(|p| p.try_as_f64())?;
    let denom = 2.0 * std::f64::consts::PI * (1u64 << (n - 1)) as f64;
    if denom == 0.0 {
        return None;
    }
    let phi = a0 / denom;
    // Gate-for-gate structural match against the canonical reference.
    let reference = qpe_canonical_circuit(n, phi);
    let refg: Vec<_> = reference
        .instructions
        .iter()
        .filter(|i| !i.gate.kind.is_meta())
        .collect();
    if gates.len() != refg.len() {
        return None;
    }
    for (g, r) in gates.iter().zip(refg.iter()) {
        if g.gate.kind != r.gate.kind {
            return None;
        }
        let gq: Vec<usize> = g.qubits.iter().map(|q| q.index).collect();
        let rq: Vec<usize> = r.qubits.iter().map(|q| q.index).collect();
        if gq != rq {
            return None;
        }
        if g.gate.params.len() != r.gate.params.len() {
            return None;
        }
        for (pg, pr) in g.gate.params.iter().zip(r.gate.params.iter()) {
            match (pg.try_as_f64(), pr.try_as_f64()) {
                (Some(a), Some(c)) => {
                    if (a - c).abs() > 1e-9 {
                        return None;
                    }
                }
                _ => {
                    if pg != pr {
                        return None;
                    }
                }
            }
        }
    }
    Some(n)
}

/// Emit a **sorry-free** gate-model FAITHFULNESS spec for QPE(n): the obligation
/// `counting_marginal (denote (qpeCircuit n θ) *ᵥ basis0 (n+1)) m = 1` (for exact
/// `θ = m/2^n`) is closed by `QuantumProofs.QPEFaithful.qpe_faithful`. Like the
/// QFT equiv spec, `circuit` is the **library symbolic** `qpeCircuit n θ` — the
/// faithful `(n+1)`-qubit QPE (eigenstate on qubit 0, counting register on qubits
/// `1..n`): `X` eigenstate prep, `H^⊗n`, controlled-phase cascade, and the
/// explicit inverse-QFT gate list. The obligation re-exports the proved theorem,
/// no opaque matrix-adjoint caveat. `qpe_recognized` ties an emitted circuit to
/// this library model by a gate-for-gate structural match.
fn render_qpe_faithful_spec(name: &str, n: usize) -> String {
    let nm = sanitize_lean(name);
    let prove_name = "qpe_recovers_phase";
    let mut out = String::new();
    out.push_str("-- Auto-generated by `aria export --gate-model` — DO NOT EDIT.\n");
    out.push_str("-- Gate-model QPE FAITHFULNESS obligation (LEAN_EXPORT Track B): the actual\n");
    out.push_str("-- (n+1)-qubit QPE circuit — X eigenstate prep, H^⊗n, controlled-phase\n");
    out.push_str("-- cascade, and the explicit inverse-QFT GATE LIST — measured on the\n");
    out.push_str("-- counting register yields the phase m with probability 1 for exact\n");
    out.push_str("-- θ = m/2^n. CLOSED sorry-free by `QuantumProofs.QPEFaithful.qpe_faithful`\n");
    out.push_str("-- (no `sorry`, no `native_decide`, no opaque matrix-adjoint caveat).\n");
    out.push_str("-- NOTE: the library model `qpeCircuit n` carries the eigenstate on qubit 0;\n");
    out.push_str("-- `qpe_recognized` verified the emitted circuit matches it gate-for-gate.\n\n");
    out.push_str("import QuantumProofs.QPEFaithful\n\n");
    out.push_str(&format!("namespace Exported.GateModel.{nm}\n\n"));
    out.push_str("open Matrix QuantumProofs.QPEFaithful QuantumProofs.CircuitSemantics\n\n");
    out.push_str(&format!(
        "/-- Gate-model QPE circuit for `{name}` ({n}+1 qubits: eigenstate on qubit 0,\n    \
         {n} counting qubits): the library model `qpeCircuit {n} θ` (faithful to the\n    \
         X-prep + H-layer + controlled-phase cascade + inverse-QFT gate list). -/\n\
         noncomputable def circuit (θ : ℝ) : Circuit ({n} + 1) := qpeCircuit {n} θ\n\n"
    ));
    out.push_str(&format!(
        "/-- **QPE faithfulness** — for exact phase `θ = m/2^{n}`, measuring the counting\n    \
         register of `denote circuit` yields `m` with probability 1. Closed sorry-free.\n    \
         (Statement is the toolkit's canonical QPE phase-recovery obligation.) -/\n\
         theorem {prove_name} (m : Fin (2 ^ {n})) (θ : ℝ) (hθ : θ = ↑m.val / ↑(2 ^ {n})) :\n    \
         counting_marginal (denote (circuit θ) *ᵥ basis0 ({n} + 1)) m = 1 :=\n  \
         qpe_faithful {n} m θ hθ\n\n"
    ));
    out.push_str(&format!("end Exported.GateModel.{nm}\n"));
    out
}

/// The canonical **gate-model Grover(3)** circuit for the marked basis state
/// `marked` (the `grover3.aria` lowering): a uniform `H^⊗3` layer, then
/// `optimal_iterations 3 = 2` repetitions of (oracle · diffusion). The
/// multi-controlled `Z` is the standard `H₂ · CCX · H₂` MCZ decomposition (the
/// IR has no `CCZ` primitive); the oracle wraps it in `X`-masks on the wires
/// whose `marked`-bit is `0`. The reference `grover_recognized` matches against,
/// and the circuit the drift test builds.
fn grover_canonical_circuit(marked: usize) -> Circuit {
    use crate::ast::CircuitBuilder;
    let k = 2; // optimal_iterations 3 = floor(π·√8/4) = 2
    let mut b = CircuitBuilder::new("grover_ref", 3, 0);
    // Uniform superposition.
    b.h(0);
    b.h(1);
    b.h(2);
    // MCZ as H₂·CCX·H₂ with X-masks on the marked-bit-0 wires (oracle), then the
    // diffusion 2|s⟩⟨s|−I.
    let mask = |b: &mut CircuitBuilder| {
        for q in 0..3 {
            if (marked >> q) & 1 == 0 {
                b.x(q);
            }
        }
    };
    for _ in 0..k {
        // Oracle: phase-flip |marked⟩.
        mask(&mut b);
        b.h(2);
        b.ccx(0, 1, 2);
        b.h(2);
        mask(&mut b);
        // Diffusion: H^⊗3 · X^⊗3 · MCZ · X^⊗3 · H^⊗3.
        b.h(0);
        b.h(1);
        b.h(2);
        b.x(0);
        b.x(1);
        b.x(2);
        b.h(2);
        b.ccx(0, 1, 2);
        b.h(2);
        b.x(0);
        b.x(1);
        b.x(2);
        b.h(0);
        b.h(1);
        b.h(2);
    }
    b.build()
}

/// Recognize the **gate-model Grover(3)** circuit for the canonical marked item
/// `|111⟩` (index 7) that the proved `groverIterTopPow (optimal_iterations 3)`
/// models. Returns `Some(3)` (the register width) iff the circuit matches
/// `grover_canonical_circuit(7)` gate-for-gate — uniform `H^⊗3`, then 2 rounds
/// of (oracle · diffusion) with the `H₂·CCX·H₂` MCZ — proved correct by
/// `QuantumProofs.GroverCircuit.grover_gate_optimal_success`. The library uses
/// the `ccz` primitive for the same MCZ; only the all-ones marked state is
/// recognized (the only case the measurement certificate is proved for).
/// Mirrors `qpe_recognized`.
fn grover_recognized(circuit: &Circuit) -> Option<usize> {
    if circuit.n_qubits() != 3 {
        return None;
    }
    let gates: Vec<_> = circuit
        .instructions
        .iter()
        .filter(|i| !i.gate.kind.is_meta())
        .collect();
    // Gate-for-gate structural match against the canonical |111⟩ reference.
    let reference = grover_canonical_circuit(7);
    let refg: Vec<_> = reference
        .instructions
        .iter()
        .filter(|i| !i.gate.kind.is_meta())
        .collect();
    if gates.len() != refg.len() {
        return None;
    }
    for (g, r) in gates.iter().zip(refg.iter()) {
        if g.gate.kind != r.gate.kind {
            return None;
        }
        let gq: Vec<usize> = g.qubits.iter().map(|q| q.index).collect();
        let rq: Vec<usize> = r.qubits.iter().map(|q| q.index).collect();
        if gq != rq {
            return None;
        }
        if g.gate.params.len() != r.gate.params.len() {
            return None;
        }
        for (pg, pr) in g.gate.params.iter().zip(r.gate.params.iter()) {
            match (pg.try_as_f64(), pr.try_as_f64()) {
                (Some(a), Some(c)) => {
                    if (a - c).abs() > 1e-9 {
                        return None;
                    }
                }
                _ => {
                    if pg != pr {
                        return None;
                    }
                }
            }
        }
    }
    Some(3)
}

/// Emit a **sorry-free** gate-model MEASUREMENT spec for Grover(3): the obligation
/// `normSq (amplitude (apply_unitary (denote (groverIterTopPow (optimal_iterations
/// 3))) (uniform_state 3)) ⟨7⟩) ≥ 1 − 1/8` is closed by the proved
/// `QuantumProofs.GroverCircuit.grover_gate_optimal_success`. Like the QPE/QFT
/// specs, `circuit` is the **library symbolic** `groverIterTopPow
/// (optimal_iterations 3)` (using the `ccz` primitive); `grover_recognized` ties
/// an emitted circuit to this library model by a gate-for-gate structural match
/// against the `H₂·CCX·H₂` MCZ lowering.
fn render_grover_spec(name: &str) -> String {
    let nm = sanitize_lean(name);
    let prove_name = "grover_finds_marked";
    let mut out = String::new();
    out.push_str("-- Auto-generated by `aria export --gate-model` — DO NOT EDIT.\n");
    out.push_str("-- Gate-model GROVER measurement obligation (LEAN_EXPORT Track B): the actual\n");
    out.push_str("-- 3-qubit Grover circuit — uniform H^⊗3 layer then `optimal_iterations 3`\n");
    out.push_str("-- repetitions of (oracle · diffusion) for the canonical marked item |111⟩ —\n");
    out.push_str("-- run on the uniform state and measured yields the marked item with\n");
    out.push_str("-- probability ≥ 1 − 1/8. CLOSED sorry-free by\n");
    out.push_str("-- `QuantumProofs.GroverCircuit.grover_gate_optimal_success` (no `sorry`, no\n");
    out.push_str("-- `native_decide`).\n");
    out.push_str("-- NOTE: the library model `groverIterTopPow k` uses the `ccz` primitive for\n");
    out.push_str("-- the multi-controlled Z; the toolkit lowering (grover3.aria) emits the\n");
    out.push_str("-- standard `H · CCX · H` MCZ decomposition. `grover_recognized` verified the\n");
    out.push_str("-- emitted circuit matches the canonical gate-model Grover(3) for |111⟩.\n\n");
    out.push_str("import QuantumProofs.GroverCircuit\n\n");
    out.push_str(&format!("namespace Exported.GateModel.{nm}\n\n"));
    out.push_str(
        "open Matrix QuantumProofs.GroverCircuit QuantumProofs.Grover QuantumProofs.CircuitSemantics\n\n",
    );
    out.push_str(&format!(
        "/-- Gate-model Grover circuit for `{name}` (3 qubits): the library model\n    \
         `groverIterTopPow (optimal_iterations 3)` — the uniform H-layer followed by\n    \
         `optimal_iterations 3` Grover iterations (oracle · diffusion) for the\n    \
         canonical marked item |111⟩. -/\n\
         noncomputable def circuit : Circuit 3 := groverIterTopPow (optimal_iterations 3)\n\n"
    ));
    out.push_str(&format!(
        "/-- **Grover measurement correctness** — running `denote circuit` on the uniform\n    \
         state and measuring yields the marked item |111⟩ (index 7) with probability\n    \
         ≥ 1 − 1/8. Closed sorry-free. (Statement is the toolkit's canonical Grover\n    \
         amplitude-amplification success obligation.) -/\n\
         theorem {prove_name} :\n    \
         Complex.normSq\n        \
         (amplitude (apply_unitary (denote circuit) (uniform_state 3)) ⟨7, by norm_num⟩)\n      \
         ≥ 1 - 1 / (2 ^ 3 : ℕ) :=\n  \
         grover_gate_optimal_success\n\n"
    ));
    out.push_str(&format!("end Exported.GateModel.{nm}\n"));
    out
}

/// Like [`sanitize_lean`] but guarantees a *valid, non-reserved* Lean
/// identifier: falls back to `fallback` if sanitization yields an empty string,
/// a leading-digit name, or a Lean keyword (a malformed `@prove` name would
/// otherwise produce an uncompilable `theorem 2x :` / `theorem end :`).
fn safe_lean_ident(s: &str, fallback: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "end",
        "def",
        "theorem",
        "lemma",
        "namespace",
        "open",
        "import",
        "by",
        "exact",
        "let",
        "fun",
        "match",
        "with",
        "in",
        "do",
        "if",
        "then",
        "else",
        "structure",
        "inductive",
        "class",
        "instance",
        "example",
        "variable",
        "section",
        "where",
        "deriving",
        "axiom",
    ];
    let san = sanitize_lean(s);
    let first_ok = san
        .chars()
        .next()
        .map(|c| c.is_alphabetic() || c == '_')
        .unwrap_or(false);
    if san.is_empty() || !first_ok || KEYWORDS.contains(&san.as_str()) {
        fallback.to_string()
    } else {
        san
    }
}

fn sanitize_lean(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::CircuitBuilder;

    #[test]
    fn test_to_lean4_bell() {
        let mut circ = CircuitBuilder::new("bell", 2, 0).h(0).cx(0, 1).build();
        circ.annotate(Annotation::Assert(Property::Unitary));

        let lean = to_lean4(&circ);
        assert!(lean.contains("import QuantumProofs"));
        assert!(lean.contains("def circuit : Circuit 2"));
        assert!(lean.contains(".h"));
        assert!(lean.contains(".cx"));
        assert!(lean.contains("is_unitary"));
        assert!(lean.contains("sorry"));
    }

    #[test]
    fn test_to_lean4_with_prove() {
        let mut circ = CircuitBuilder::new("qft", 3, 0).qft(&[0, 1, 2]).build();
        circ.annotate(Annotation::Prove {
            name: "qft_correct".into(),
            property: Property::Equiv {
                description: "dft_matrix".into(),
            },
        });

        let lean = to_lean4(&circ);
        assert!(lean.contains("theorem qft_correct"));
        assert!(lean.contains("denote circuit = denote dft_matrix"));
    }

    #[test]
    fn test_to_lean4_resource_bound_decide() {
        use crate::ast::ParamExpr;
        let mut circ = CircuitBuilder::new("rb", 2, 0).h(0).cx(0, 1).build();
        circ.annotate(Annotation::ResourceBound {
            metric: "gate_count".into(),
            bound: ParamExpr::from(10.0),
        });
        circ.annotate(Annotation::ResourceBound {
            metric: "depth".into(),
            bound: ParamExpr::from(5.0),
        });

        let lean = to_lean4(&circ);
        assert!(lean.contains("gate_count_bound"));
        assert!(lean.contains("depth_bound"));
        assert!(lean.contains(":= by decide"));
        // The actual gate count is 2 → should appear in the inequality.
        assert!(lean.contains("2 ≤ 10"));
    }

    #[test]
    fn test_to_lean4_assume_invariant() {
        let mut circ = CircuitBuilder::new("loop", 1, 0).h(0).build();
        circ.annotate(Annotation::Assume(Property::Unitary));
        circ.annotate(Annotation::Invariant(Property::Custom("norm = 1".into())));
        circ.annotate(Annotation::Requires(Property::Custom("input ≠ 0".into())));

        let lean = to_lean4(&circ);
        assert!(lean.contains("axiom assume_"));
        assert!(lean.contains("theorem invariant_"));
        assert!(lean.contains("theorem requires_"));
    }

    #[test]
    fn gate_model_spec_bell_is_closed_sorry_free() {
        // The recognized Bell circuit emits a spec CLOSED by proved theorems,
        // never a `sorry` tactic.
        let mut circ = CircuitBuilder::new("Bell", 2, 0).h(0).cx(0, 1).build();
        circ.annotate(Annotation::Assert(Property::Unitary));
        circ.annotate(Annotation::Prove {
            name: "bell_correct".into(),
            property: Property::Custom("creates (|00> + |11>)/sqrt(2)".into()),
        });
        let spec = render_gate_model_spec(&circ, "Bell").expect("Bell recognized");
        assert!(spec.contains("import QuantumProofs.BellPrep"));
        assert!(spec
            .contains("theorem circuit_eq : circuit = QuantumProofs.BellPrep.bell_circuit := rfl"));
        assert!(spec.contains("theorem bell_correct")); // @prove name → label
        assert!(spec.contains("exact QuantumProofs.BellPrep.bell_state_prep_correct"));
        assert!(spec.contains("exact QuantumProofs.BellPrep.bell_unitary"));
        // No `sorry` *tactic* (prose may say "sorry-free").
        assert!(
            !spec.lines().any(|l| l.trim() == "sorry") && !spec.contains(":= by sorry"),
            "gate-model spec must be sorry-free: {spec}"
        );
    }

    #[test]
    fn gate_model_spec_matches_committed_bell_file() {
        // Guard against emitter drift: the committed canonical artefact
        // `proofs/lean4/QuantumProofs/Generated/GateModel/Bell_Spec.lean`
        // (CI-built under ARIA_LEAN=1) must be exactly what the emitter produces
        // from the same `examples/aria/bell.aria`. Both files are committed in
        // this repo, so a missing file is a RED test (a path move), not a skip —
        // otherwise the guard would silently pass exactly when drift is likeliest.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let spec_path =
            root.join("../../proofs/lean4/QuantumProofs/Generated/GateModel/Bell_Spec.lean");
        let aria_path = root.join("../../examples/aria/bell.aria");
        let committed = std::fs::read_to_string(&spec_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", spec_path.display()));
        let src = std::fs::read_to_string(&aria_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", aria_path.display()));
        let prog = crate::ast::parse_aria(&src).expect("bell.aria parses");
        let circuit = prog.instantiate("Bell", &[]).expect("Bell instantiates");
        let emitted = render_gate_model_spec(&circuit, "Bell").expect("Bell recognized");
        assert_eq!(
            emitted, committed,
            "emitter drifted from committed Bell_Spec.lean; regenerate with \
             `aria export examples/aria/bell.aria --circuit Bell --gate-model \
             > proofs/lean4/QuantumProofs/Generated/GateModel/Bell_Spec.lean`"
        );
    }

    #[test]
    fn gate_model_spec_recognizes_ghz() {
        // GHZ (H@0; CX 0→1; CX 1→2 on 3 qubits) is the second recognized circuit,
        // closed sorry-free by QuantumProofs.GHZPrep.ghz_state_prep_correct.
        let mut circ = CircuitBuilder::new("GHZ", 3, 0)
            .h(0)
            .cx(0, 1)
            .cx(1, 2)
            .build();
        circ.annotate(Annotation::Prove {
            name: "ghz_correct".into(),
            property: Property::Custom("creates (|000> + |111>)/sqrt(2)".into()),
        });
        // `@assert unitary` is now closeable for GHZ (ghz_unitary is proved).
        circ.annotate(Annotation::Assert(Property::Unitary));
        let spec = render_gate_model_spec(&circ, "GHZ").expect("GHZ recognized");
        assert!(spec.contains("import QuantumProofs.GHZPrep"));
        assert!(spec.contains("theorem ghz_correct"));
        assert!(spec.contains("exact QuantumProofs.GHZPrep.ghz_state_prep_correct"));
        // `ghz_unitary` is proved → the `@assert unitary` is CLOSED sorry-free.
        assert!(spec.contains("theorem circuit_unitary"), "{spec}");
        assert!(
            spec.contains("exact QuantumProofs.GHZPrep.ghz_unitary"),
            "{spec}"
        );
        assert!(!spec.contains("omitted, not verified"), "{spec}");
        assert!(
            !spec.lines().any(|l| l.trim() == "sorry") && !spec.contains(":= by sorry"),
            "gate-model spec must be sorry-free: {spec}"
        );
    }

    #[test]
    fn gate_model_spec_matches_committed_qft_file() {
        // Drift guard for the QFT equiv obligation: the committed
        // `Generated/GateModel/QFT_Spec.lean` must be exactly what the emitter
        // produces from qft.aria at n=3.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let spec_path =
            root.join("../../proofs/lean4/QuantumProofs/Generated/GateModel/QFT_Spec.lean");
        let aria_path = root.join("../../examples/aria/qft.aria");
        let committed = std::fs::read_to_string(&spec_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", spec_path.display()));
        let src = std::fs::read_to_string(&aria_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", aria_path.display()));
        let prog = crate::ast::parse_aria(&src).expect("qft.aria parses");
        let circuit = prog
            .instantiate("QFT", &[("n", 3)])
            .expect("QFT instantiates");
        let emitted = render_gate_model_spec(&circuit, "QFT").expect("QFT recognized");
        assert_eq!(
            emitted, committed,
            "emitter drifted from committed QFT_Spec.lean; regenerate with \
             `aria export examples/aria/qft.aria --circuit QFT --gate-model --int n=3 \
             > proofs/lean4/QuantumProofs/Generated/GateModel/QFT_Spec.lean`"
        );
        assert!(emitted.contains("qftLowered_correct 3"), "{emitted}");
    }

    #[test]
    fn gate_model_spec_recognizes_qft() {
        for n in 1..=4 {
            let mut b = CircuitBuilder::new("qft", n, 0);
            b.qft(&(0..n).collect::<Vec<_>>());
            assert_eq!(super::qft_recognized(&b.build()), Some(n), "QFT({n})");
        }
        let bell = CircuitBuilder::new("bell", 2, 0).h(0).cx(0, 1).build();
        assert_eq!(super::qft_recognized(&bell), None);
    }

    #[test]
    fn gate_model_spec_matches_committed_qpe_file() {
        // Drift guard for the QPE faithfulness obligation: the committed
        // `Generated/GateModel/QPE_Spec.lean` (CI-type-checked + axiom-clean under
        // mathlib) must be exactly what the emitter produces from the canonical
        // eigenstate-first QPE(3) circuit. qpe.aria is eigenstate-LAST (its own
        // example/numeric form); the recognizer/proof use the eigenstate-FIRST
        // canonical circuit, which is what we regenerate from here.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let spec_path =
            root.join("../../proofs/lean4/QuantumProofs/Generated/GateModel/QPE_Spec.lean");
        let committed = std::fs::read_to_string(&spec_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", spec_path.display()));
        let c = super::qpe_canonical_circuit(3, 0.125);
        let emitted = render_gate_model_spec(&c, "QPE").expect("QPE recognized");
        assert_eq!(
            emitted, committed,
            "emitter drifted from committed QPE_Spec.lean; regenerate"
        );
        assert!(emitted.contains("qpe_faithful 3 m θ hθ"), "{emitted}");
    }

    #[test]
    fn gate_model_spec_recognizes_qpe() {
        use crate::ast::expr::ParamExpr;
        use crate::ast::nodes::GateKind;
        // The canonical eigenstate-first QPE(n) is recognized for n = 1..=4.
        for n in 1..=4 {
            let c = super::qpe_canonical_circuit(n, 0.125);
            assert_eq!(super::qpe_recognized(&c), Some(n), "QPE({n})");
        }
        // Bell / QFT are NOT recognized as QPE.
        let bell = CircuitBuilder::new("bell", 2, 0).h(0).cx(0, 1).build();
        assert_eq!(
            super::qpe_recognized(&bell),
            None,
            "Bell wrongly recognized as QPE"
        );
        let mut b = CircuitBuilder::new("qft", 3, 0);
        b.qft(&[0, 1, 2]);
        assert_eq!(
            super::qpe_recognized(&b.build()),
            None,
            "QFT wrongly recognized as QPE"
        );
        // A QPE with one perturbed cascade angle is NOT recognized (structural guard).
        let mut c = super::qpe_canonical_circuit(3, 0.125);
        let mut perturbed = false;
        for inst in c.instructions.iter_mut() {
            if inst.gate.kind == GateKind::CP {
                inst.gate.params = vec![ParamExpr::Concrete(0.123)];
                perturbed = true;
                break;
            }
        }
        assert!(perturbed, "no CP gate to perturb");
        assert_eq!(
            super::qpe_recognized(&c),
            None,
            "perturbed-angle QPE wrongly recognized"
        );
    }

    #[test]
    fn gate_model_spec_skips_unrecognized_circuit() {
        // A circuit that is neither Bell nor GHZ has no proved gate-model theorem
        // → `None` (the CLI turns this into an honest error, never a `sorry`).
        let circ = CircuitBuilder::new("W3", 3, 0).h(0).h(1).h(2).build();
        assert!(render_gate_model_spec(&circ, "W3").is_none());
    }

    #[test]
    fn safe_lean_ident_guards_invalid_names() {
        assert_eq!(safe_lean_ident("bell_correct", "fb"), "bell_correct");
        assert_eq!(safe_lean_ident("2bell", "fb"), "fb"); // leading digit
        assert_eq!(safe_lean_ident("", "fb"), "fb"); // empty
        assert_eq!(safe_lean_ident("end", "fb"), "fb"); // keyword
    }

    #[test]
    fn gate_model_spec_matches_committed_grover_file() {
        // Drift guard for the Grover measurement obligation: the committed
        // canonical artefact `Generated/GateModel/Grover_Spec.lean` (CI-type-
        // checked + axiom-clean under mathlib) must be exactly what the emitter
        // produces from the canonical gate-model Grover(3) circuit for |111⟩.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let path =
            root.join("../../proofs/lean4/QuantumProofs/Generated/GateModel/Grover_Spec.lean");
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let c = super::grover_canonical_circuit(7);
        let emitted = render_gate_model_spec(&c, "Grover").expect("Grover recognized");
        assert_eq!(
            emitted, committed,
            "emitter output drifted from committed Grover_Spec.lean; regenerate with \
             `aria export examples/aria/grover3.aria --circuit Grover3 --gate-model --int marked=7 \
             > proofs/lean4/QuantumProofs/Generated/GateModel/Grover_Spec.lean`"
        );
        assert!(emitted.contains("grover_gate_optimal_success"), "{emitted}");
    }

    #[test]
    fn grover_recognized_only_for_canonical_grover() {
        // The canonical gate-model Grover(3) for |111⟩ is recognized.
        let c = super::grover_canonical_circuit(7);
        assert_eq!(
            super::grover_recognized(&c),
            Some(3),
            "Grover(3) |111⟩ not recognized"
        );
        // A different marked state (|011⟩, with X-masks) is NOT the proved case.
        let c011 = super::grover_canonical_circuit(3);
        assert_eq!(
            super::grover_recognized(&c011),
            None,
            "non-|111⟩ Grover wrongly recognized"
        );
        // QFT(3) is not Grover.
        let mut b = CircuitBuilder::new("qft", 3, 0);
        b.qft(&[0, 1, 2]);
        assert_eq!(
            super::grover_recognized(&b.build()),
            None,
            "QFT wrongly recognized as Grover"
        );
    }

    #[test]
    fn grover3_aria_lowering_is_recognized() {
        // The real `examples/aria/grover3.aria` example, instantiated for the
        // canonical marked item |111⟩ (index 7), lowers to exactly the circuit
        // `grover_recognized` accepts — so `aria export --gate-model` emits the
        // sorry-free Grover measurement obligation for the shipped example.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let aria_path = root.join("../../examples/aria/grover3.aria");
        let src = std::fs::read_to_string(&aria_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", aria_path.display()));
        let prog = crate::ast::parse_aria(&src).expect("grover3.aria parses");
        let circuit = prog
            .instantiate("Grover3", &[("marked", 7)])
            .expect("Grover3 instantiates");
        assert_eq!(
            super::grover_recognized(&circuit),
            Some(3),
            "grover3.aria lowering not recognized as canonical Grover(3)"
        );
        assert!(render_gate_model_spec(&circuit, "Grover").is_some());
    }
}
