#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write the pinned emulator-comparison workloads (PLAN-EMULATOR-COMPARISON §3).

ONE generator for the whole comparison, and ONE directory of artifacts
(`tools/emu_compare/qasm/`) that every lane ingests. The point is not
convenience: a per-lane reimplementation of "the HEA brickwall" is two
circuits with one name, and the comparison would be measuring different work
in each arm while printing a single row id. So the exported QASM2 file is the
contract, and a lane that wants the HEA reads the file.

stdlib only, so it runs under any Python on either box. LUCJ-16 is the one
exception: it is generated by the existing
`crates/omega-bridges/python/lucj_gen.py` (ffsim + qiskit), which this script
shells out to when `--lucj-python` is given, and otherwise records as pending.

  gen_workloads.py                         write every stdlib-only artifact
  gen_workloads.py --lucj-python PY        also regenerate LUCJ-16 through PY
  gen_workloads.py --check                 regenerate nothing; verify the
                                           committed artifacts still hash to
                                           MANIFEST.json

The manifest carries, per artifact, the exact generator invocation, the seed,
and the sha256 — so a row can name the file it ran AND prove it is the file
this script writes. §3 asks every row to fix "(circuit id, generator+seed or
file, qubits, depth, chi, shots, precision, hardware)"; this covers the first
three for every lane at once.
"""
import argparse
import hashlib
import json
import math
import os
import random
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
QASM_DIR = os.path.join(HERE, "qasm")
MANIFEST = os.path.join(HERE, "MANIFEST.json")

# --- the pinned parameters -------------------------------------------------
# Changing any number here invalidates every row already in
# docs/EMULATOR-COMPARISON.md, which is why they live in one block.

RANDOM1_DEPTH = 20
RANDOM1_SEED = 0
CLIFFORD_DEPTH = 100

# (file stem, qubits, depth). HEA: 14q x {4,12,24} and 20q x {12,24} are the
# MPS/dense-CPU shapes of §3 (the `mps_stage_profile` shapes, so our own
# baselines already exist); 24/26/28q x depth 24 are the GPU lane's, already
# committed on the E5 branch and reproduced here bit-for-bit.
HEA_SHAPES = [(14, 4), (14, 12), (14, 24), (20, 12), (20, 24), (24, 24), (26, 24), (28, 24)]
# RANDOM-1: 24q is the andromeda dense row, 26q the akilles one, 24/26/28q the
# GPU rows, and 20q is the single shots=1000 sampling row.
RANDOM1_QUBITS = [20, 24, 26, 28]
# Clifford brickwall, §3(a): "24q and 100q x depth 100".
CLIFFORD_QUBITS = [24, 100]

# LUCJ-16 (§3, the fermionic lane's one honest speed row): 16 modes is
# norb = 8 orbitals under spin-balanced Jordan-Wigner (nq = 2*norb).
# `--jastrow-scale 0.1` is not a tuning knob chosen after the fact: lucj_gen's
# own docstring records that ffsim.random draws O(1) diagonal-Coulomb phases,
# a regime where Majorana-propagation length truncation is NOT an estimator
# (it refuses at every L <= 8 at 12q), while optimised molecular LUCJ
# parameters sit at ~1e-1, where the same circuit converges to 3e-5 at L = 8.
# The comparison wants the regime real chemistry is in, and the choice is
# pinned here rather than discovered once the numbers exist.
LUCJ = {
    "id": "lucj16",
    "file": "lucj16_norb8_na4_r1_s0_j0.1.qasm",
    "norb": 8,
    "nalpha": 4,
    "reps": 1,
    "seed": 0,
    "jastrow_scale": 0.1,
    "qubits": 16,
    # LUCJ-16 is the one artifact where "every arm ingests the identical file"
    # does NOT hold, and the reason is structural rather than fixable here.
    # The file spells its hopping layers `rbs`, which is not in qelib1.inc, so
    # no Qiskit reader accepts it bare and our own reader needs the `lenient`
    # dialect. The obvious repair — ship a `gate rbs(t) a,b { ... }` definition
    # in the file so every reader inlines it — breaks our own arm: the
    # expansion contains `h`, which does not conserve particle number, so a
    # decomposed `rbs` is REFUSED by the `sector` backend, the one engine the
    # lane is built on (crates/omega-parser/src/lower.rs:1562-1568).
    #
    # So the pin for this artifact is the generator invocation, not the bytes,
    # and E6 owes the row a value gate at 16 modes (affordable) showing both
    # arms built the same operator. §5 already records the matching asymmetry
    # in the other direction: ffsim executes LUCJ layers as single fused
    # orbital rotations while we decompose to Givens.
    "dialect": "lenient",
    "ingestion": "rbs is bare, so our arms read this file in the `lenient` QASM2 dialect "
                 "and the ffsim arm does not read it at all — it builds the same ansatz "
                 "from ffsim's own operators, as lucj_gen.py did. The shared-file contract "
                 "is weaker here than for HEA/RANDOM-1/Clifford and the row must say so.",
}


def hea_qasm(n, depth):
    """`entangling_circuit` of `crates/omega-backend-mps/examples/
    mps_stage_profile.rs:82-108`, verbatim: an H layer, then per depth a
    brickwall of CX.Rz(0.25).CX bricks (offset = depth parity) and an Rx(0.15)
    on every qubit.

    This is a TRANSCRIPTION of Rust, so it can drift from its source. It is
    pinned against that source in Rust, not here:
    `crates/omega-emu-compare/tests/workload_artifacts.rs` lowers each
    committed file with `omega_parser::lower_to_ir` and asserts the result is
    op-for-op `entangling_circuit(n, depth)`. A drifting angle or a dropped
    layer reddens that test.
    """
    out = ["OPENQASM 2.0;", 'include "qelib1.inc";', f"qreg q[{n}];"]
    out += [f"h q[{q}];" for q in range(n)]
    for d in range(depth):
        for q in range(d & 1, n - 1, 2):
            out += [f"cx q[{q}],q[{q + 1}];", f"rz(0.25) q[{q + 1}];", f"cx q[{q}],q[{q + 1}];"]
        out += [f"rx(0.15) q[{q}];" for q in range(n)]
    return "\n".join(out) + "\n"


def random1_qasm(n, depth, seed):
    """RANDOM-1: per layer, rx(b) then rz(a) on every qubit with angles drawn
    uniformly from [0, 2*pi) by `random.Random(seed)` in (layer, qubit, rx, rz)
    order, then a CX brickwall with offset = layer parity. Angles are written
    with repr(), which round-trips an f64 exactly.

    The draw order is part of the pin: `random.Random` is a Mersenne Twister,
    so reordering the two `uniform` calls silently produces a different
    circuit under the same seed. Reproduced unchanged from the E5 branch so
    the 20/24/26/28q files are byte-identical to the ones the GPU lane has
    already run.
    """
    rng = random.Random(seed)
    out = ["OPENQASM 2.0;", 'include "qelib1.inc";', f"qreg q[{n}];"]
    for d in range(depth):
        for q in range(n):
            b = rng.uniform(0.0, 2.0 * math.pi)
            a = rng.uniform(0.0, 2.0 * math.pi)
            out += [f"rx({b!r}) q[{q}];", f"rz({a!r}) q[{q}];"]
        for q in range(d & 1, n - 1, 2):
            out.append(f"cx q[{q}],q[{q + 1}];")
    return "\n".join(out) + "\n"


def clifford_qasm(n, depth):
    """The Clifford-only brickwall of §3(a), H/S/CX: an H layer, then per depth
    a CX brickwall (offset = depth parity) and an S on every qubit.

    Deliberately the same skeleton as the HEA with the two rotations replaced
    by the one Clifford phase gate, so the stabilizer lane is not comparing a
    differently-shaped circuit: the only difference between this and
    `hea_qasm` is Rz(0.25) -> S and Rx(0.15) -> (nothing), which is what makes
    it expressible in a tableau at all. No parameters, so no seed.
    """
    out = ["OPENQASM 2.0;", 'include "qelib1.inc";', f"qreg q[{n}];"]
    out += [f"h q[{q}];" for q in range(n)]
    for d in range(depth):
        for q in range(d & 1, n - 1, 2):
            out.append(f"cx q[{q}],q[{q + 1}];")
        out += [f"s q[{q}];" for q in range(n)]
    return "\n".join(out) + "\n"


def sha256_of(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def gate_counts(text):
    counts = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith(("OPENQASM", "include", "qreg")):
            continue
        name = line.split("(")[0].split(" ")[0].rstrip(";")
        counts[name] = counts.get(name, 0) + 1
    return dict(sorted(counts.items()))


def stdlib_artifacts():
    """[(id, filename, text, metadata)] for everything this script can write
    without a venv."""
    out = []
    for n, d in HEA_SHAPES:
        out.append((
            f"hea-{n}q-d{d}", f"hea_{n}q_d{d}.qasm", hea_qasm(n, d),
            {"family": "hea", "qubits": n, "depth": d, "seed": None, "dialect": "legacy",
             "source": "crates/omega-backend-mps/examples/mps_stage_profile.rs:82-108 "
                       "(entangling_circuit), exported once",
             "generator": f"gen_workloads.py -> hea_qasm({n}, {d})"},
        ))
    for n in RANDOM1_QUBITS:
        out.append((
            f"random1-{n}q-d{RANDOM1_DEPTH}", f"random1_{n}q_d{RANDOM1_DEPTH}_s{RANDOM1_SEED}.qasm",
            random1_qasm(n, RANDOM1_DEPTH, RANDOM1_SEED),
            {"family": "random1", "qubits": n, "depth": RANDOM1_DEPTH, "seed": RANDOM1_SEED,
             "dialect": "legacy", "source": "generated",
             "generator": f"gen_workloads.py -> random1_qasm({n}, {RANDOM1_DEPTH}, {RANDOM1_SEED})"},
        ))
    for n in CLIFFORD_QUBITS:
        out.append((
            f"clifford-{n}q-d{CLIFFORD_DEPTH}", f"clifford_{n}q_d{CLIFFORD_DEPTH}.qasm",
            clifford_qasm(n, CLIFFORD_DEPTH),
            {"family": "clifford", "qubits": n, "depth": CLIFFORD_DEPTH, "seed": None,
             "dialect": "legacy", "source": "generated",
             "generator": f"gen_workloads.py -> clifford_qasm({n}, {CLIFFORD_DEPTH})"},
        ))
    return out


def lucj_command(python):
    gen = os.path.join(HERE, "..", "..", "crates", "omega-bridges", "python", "lucj_gen.py")
    return [
        python, os.path.normpath(gen), str(LUCJ["norb"]), str(LUCJ["nalpha"]),
        os.path.join(QASM_DIR, LUCJ["file"]),
        "--seed", str(LUCJ["seed"]), "--reps", str(LUCJ["reps"]),
        "--jastrow-scale", str(LUCJ["jastrow_scale"]),
    ]


def regenerate(lucj_python):
    os.makedirs(QASM_DIR, exist_ok=True)
    entries = {}
    for rid, fname, text, meta in stdlib_artifacts():
        path = os.path.join(QASM_DIR, fname)
        with open(path, "w") as f:
            f.write(text)
        entries[rid] = dict(meta, file=f"tools/emu_compare/qasm/{fname}",
                            gates=gate_counts(text), sha256=sha256_of(path))
        print(f"wrote qasm/{fname}")

    prev = {}
    if os.path.exists(MANIFEST):
        with open(MANIFEST) as f:
            prev = json.load(f).get("artifacts", {})
    if lucj_python:
        cmd = lucj_command(lucj_python)
        info = json.loads(subprocess.run(cmd, capture_output=True, text=True,
                                         check=True).stdout.strip().splitlines()[-1])
        path = os.path.join(QASM_DIR, LUCJ["file"])
        with open(path) as f:
            text = f.read()
        if info["qubits"] != LUCJ["qubits"]:
            raise SystemExit(f"REFUSE: lucj_gen emitted {info['qubits']} qubits, LUCJ-16 wants 16")
        entries[LUCJ["id"]] = {
            "family": "lucj", "qubits": info["qubits"], "depth": info["depth"],
            "seed": LUCJ["seed"], "source": "crates/omega-bridges/python/lucj_gen.py",
            "generator": " ".join(["lucj_gen.py", str(LUCJ["norb"]), str(LUCJ["nalpha"]),
                                   LUCJ["file"], "--seed", str(LUCJ["seed"]),
                                   "--reps", str(LUCJ["reps"]),
                                   "--jastrow-scale", str(LUCJ["jastrow_scale"])]),
            "jastrow_scale": LUCJ["jastrow_scale"], "reps": LUCJ["reps"],
            "dialect": LUCJ["dialect"], "ingestion": LUCJ["ingestion"],
            "file": f"tools/emu_compare/qasm/{LUCJ['file']}",
            "gates": gate_counts(text), "sha256": sha256_of(path),
            "venv": lucj_versions(lucj_python),
        }
        print(f"wrote qasm/{LUCJ['file']}")
    elif LUCJ["id"] in prev:
        entries[LUCJ["id"]] = prev[LUCJ["id"]]
        print(f"kept qasm/{LUCJ['file']} (no --lucj-python given)")
    else:
        print(f"LUCJ-16 NOT generated: rerun with --lucj-python pointing at an ffsim venv")

    with open(MANIFEST, "w") as f:
        json.dump({
            "note": "Pinned workloads for PLAN-EMULATOR-COMPARISON §3. Regenerate with "
                    "tools/emu_compare/gen_workloads.py; verify with --check. Every row in "
                    "docs/EMULATOR-COMPARISON.md names one of these ids and its sha256.",
            "artifacts": dict(sorted(entries.items())),
        }, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote MANIFEST.json ({len(entries)} artifacts)")


def lucj_versions(python):
    code = ("import json;from importlib.metadata import version;"
            "print(json.dumps({p: version(p) for p in ('ffsim','qiskit','numpy','scipy')}))")
    return json.loads(subprocess.run([python, "-c", code], capture_output=True,
                                     text=True, check=True).stdout.strip())


def check():
    """Verify the committed artifacts against the manifest: the stdlib families
    are regenerated in memory and compared byte-for-byte, and every file's
    sha256 is re-hashed. LUCJ-16 is hash-only (it needs a venv to regenerate).
    Returns a process exit code."""
    with open(MANIFEST) as f:
        entries = json.load(f)["artifacts"]
    bad = []
    for rid, fname, text, _ in stdlib_artifacts():
        if rid not in entries:
            bad.append(f"{rid}: absent from MANIFEST.json")
            continue
        path = os.path.join(QASM_DIR, fname)
        if not os.path.exists(path):
            bad.append(f"{rid}: {fname} is not committed")
            continue
        with open(path) as f:
            on_disk = f.read()
        if on_disk != text:
            bad.append(f"{rid}: {fname} differs from what the generator writes")
    for rid, meta in entries.items():
        path = os.path.join(HERE, "..", "..", meta["file"])
        if not os.path.exists(path):
            bad.append(f"{rid}: {meta['file']} is not committed")
            continue
        got = sha256_of(path)
        if got != meta["sha256"]:
            bad.append(f"{rid}: sha256 {got[:12]} != manifest {meta['sha256'][:12]}")
    for line in bad:
        print(f"FAIL {line}", file=sys.stderr)
    if bad:
        return 1
    print(f"ok: {len(entries)} artifacts match MANIFEST.json")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--lucj-python", default=None,
                    help="python of a venv with ffsim+qiskit (see PREREQUISITES.md); "
                         "without it LUCJ-16 is left as committed")
    a = ap.parse_args()
    if a.check:
        return check()
    regenerate(a.lucj_python)
    return 0


if __name__ == "__main__":
    sys.exit(main())
