#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Re-parse the committed DITQASM fixtures under mqt.qudits and pin what Q0 learned.

PLAN-FERMIONIC-QUDIT Q0. Wired into ci.sh as a registered skip when no Python
imports mqt.qudits. Exit 1 on any mismatch; every check prints one line.

What a failure means:
  * dims / bytes differ           → upstream changed its emitter or parser.
                                     Bump requirements-mqt.txt on purpose and
                                     regenerate with gen_fixtures.py.
  * a pinned DEFECT stops firing  → upstream fixed it. Good news, but the
                                     README and PROVENANCE.json describe the
                                     old behaviour — update them, then the pin.
  * a semantics check fails       → the gate MQT calls `h`/`x`/`cx` changed
                                     meaning; Q1's grammar answers rest on
                                     these, re-read PLAN-OPEN §3e.1a.
"""

from __future__ import annotations

import importlib.metadata
import json
import pathlib
import sys

import numpy as np
from mqt.qudits.quantum_circuit import QuantumCircuit

ROOT = pathlib.Path(__file__).resolve().parents[2]
FIX = ROOT / "crates" / "omega-parser" / "tests" / "fixtures" / "ditqasm"

failures: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    print(f"  {'ok  ' if ok else 'FAIL'} {name}{(' — ' + detail) if detail else ''}")
    if not ok:
        failures.append(name)


def parse(text: str) -> QuantumCircuit:
    c = QuantumCircuit()
    c.from_qasm(text)
    return c


def main() -> int:
    prov = json.loads((FIX / "PROVENANCE.json").read_text())
    have = importlib.metadata.version("mqt.qudits")
    print(f"mqt.qudits {have}; fixtures generated by {prov['version']}")
    check("library version matches PROVENANCE", have == prov["version"], f"{have} vs {prov['version']}")

    # 1. Every MQT-emitted fixture re-parses to the recorded dimensions, and
    #    round-trips byte-identically exactly where PROVENANCE says it does.
    for name, meta in prov["files"].items():
        if "reparsed_dims" not in meta:
            continue
        text = (FIX / f"{name}.qasm").read_text()
        d = parse(text)
        check(f"{name}: dims", list(d.dimensions) == meta["dims"], f"{list(d.dimensions)} vs {meta['dims']}")
        check(f"{name}: n_gates", len(d.instructions) == meta["n_gates"])
        identical = d.to_qasm() == text
        check(
            f"{name}: round-trip identical == {meta['roundtrip_identical']}",
            identical == meta["roundtrip_identical"],
        )

    # 2. Bare `qreg name [n];` — the §3e.1a unknown. n qudits, each d = 2.
    bare = (FIX / "bare_qreg_input.qasm").read_text()
    e = parse(bare)
    meta = prov["files"]["bare_qreg_input"]
    check("bare qreg [2] → 2 qudits", e.num_qudits == meta["parsed_num_qudits"] == 2)
    check("bare qreg [2] → dims [2, 2]", list(e.dimensions) == meta["parsed_dims"] == [2, 2])
    check(
        "bare qreg re-emitted bytes",
        e.to_qasm() == (FIX / "bare_qreg_reemitted.qasm").read_text(),
    )

    # 3. D1 — the ctl writer defect, pinned. Must still raise.
    text = (FIX / "ctl_writer_defect.qasm").read_text()
    check("D1: writer emits target index for controls", "h q[1] ctl q[1] q[1] [2, 1];" in text)
    try:
        parse(text)
        check("D1: MQT cannot re-parse its own ctl output", False, "it parsed — upstream fixed D1")
    except IndexError as ex:
        check("D1: MQT cannot re-parse its own ctl output", "Controls overlap with targets" in str(ex), str(ex))

    # 4. ctl level list pairs positionally with the control-qudit list.
    g = parse((FIX / "ctl_hand_corrected.qasm").read_text()).instructions[0]
    want = prov["files"]["ctl_hand_corrected"]["parsed_controls"]
    check(
        "ctl: level list is per control, positional",
        list(g._controls_data.indices) == want["indices"] == [0, 2]
        and list(g._controls_data.ctrl_states) == want["ctrl_states"] == [2, 1],
        f"{list(g._controls_data.indices)} / {list(g._controls_data.ctrl_states)}",
    )

    # 5. D2 — rxy/rz parameters dropped on parse, cx's kept. Pinned.
    d = parse((FIX / "mixed_325.qasm").read_text())
    by_name = {type(x).__name__: x for x in d.instructions}
    check("D2: reparsed R has no params", by_name["R"]._params is None, f"{by_name['R']._params}")
    check("D2: reparsed Rz has no params", by_name["Rz"]._params is None, f"{by_name['Rz']._params}")
    check("D2: reparsed CEx keeps [0, 1, 1, 0.0]", list(by_name["CEx"]._params) == [0, 1, 1, 0.0])
    c = QuantumCircuit(1, [3], 0)
    check("D2 cause: R accepts a list", c.r(0, [0, 1, 1.2, 0.3])._params is not None)
    check("D2 cause: R silently drops a tuple", c.r(0, (0, 1, 1.2, 0.3))._params is None)

    # 6. Semantics of the shared names — the §3e.1a "generalised or embedded" unknown.
    c = QuantumCircuit(1, [3], 0)
    w = np.exp(2j * np.pi / 3)
    fourier = np.array([[w ** (j * k) for k in range(3)] for j in range(3)]) / np.sqrt(3)
    check("h on d=3 is the Fourier gate", np.allclose(np.array(c.h(0)), fourier))
    shift = np.roll(np.eye(3), 1, axis=0)
    check("x on d=3 is the cyclic shift X_d", np.allclose(np.array(c.x(0)), shift))
    check("z on d=3 is the clock Z_d", np.allclose(np.diag(np.array(c.z(0))), [1, w, w**2]))
    c = QuantumCircuit(2, [3, 2], 0)
    g = c.cx([0, 1])
    check("cx on [3,2] is a parametrised two-level gate (6x6, params [0,1,1,0.0])",
          np.array(g).shape == (6, 6) and list(g._params) == [0, 1, 1, 0.0])
    check("csum on [3,3] is the generalised CX (9x9, no params)",
          np.array(QuantumCircuit(2, [3, 3], 0).csum([0, 1])).shape == (9, 9))

    # 7. Header version lock.
    body = "\nqreg q [1][3];\ncreg meas[1];\nh q[0];\n"
    check("header DITQASM 2.0; accepted", len(parse("DITQASM 2.0;" + body).instructions) == 1)
    for hdr in ("DITQASM 3.0;", "DITQASM 2.1;", "OPENQASM 2.0;"):
        try:
            parse(hdr + body)
            check(f"header {hdr} rejected", False, "it parsed")
        except SyntaxError:
            check(f"header {hdr} rejected", True)

    if failures:
        print(f"\nFAILED {len(failures)}: " + "; ".join(failures))
        return 1
    print("\nOK: DITQASM fixtures re-parse under mqt.qudits; D1/D2 still pinned; header lock holds")
    return 0


if __name__ == "__main__":
    sys.exit(main())
