// SPDX-License-Identifier: Apache-2.0
//! **The same OPTICQASM source, executed by two independent backends, must
//! compute the same numbers.**
//!
//! This is the acceptance criterion for `PLAN-OPTICQASM-INTEGRITY.md` (O5), and
//! it is a stronger claim than anything the sibling tests make:
//!
//! * `aria-core`'s round trip proves the text survives *our* emitter and *our*
//!   reader — both of which could share a misconception.
//! * `opticqasm_readable_by_parser.rs` proves the seam between the two crates
//!   is closed — but a wrong beamsplitter convention crosses that seam happily.
//! * **This** test proves the text means the same thing to piquasso as it does
//!   to us. That is the only property that makes emitting a portable dialect
//!   worth anything: a file is a description of a computation, and a
//!   description whose meaning changes with the reader is not one.
//!
//! # What is actually independent here
//!
//! The reference numbers come from `tools/cv_cross_check/piquasso_fixture.jsonl`,
//! generated by piquasso 8.0.1 from its own `Squeezing` / `Displacement` /
//! `Kerr` / `Phaseshifter` instructions. This test does **not** re-derive them;
//! it drives the *other* path — OPTICQASM text → `omega_parser::lower_opticqasm_cv`
//! → `omega-backend-cv` — and demands the same answer.
//!
//! So the chain under test is:
//!
//! ```text
//!   fixture recipe ──> OPTICQASM text ──> lower_opticqasm_cv ──> FockState
//!         │                                                          │
//!         └────────── piquasso 8.0.1 (independent) ──────────────────┴──> compare
//! ```
//!
//! The link this adds is the middle one. Before the CV profile existed, that
//! arrow did not exist at all: OPTICQASM text naming `squeeze` could not be
//! imported by anything in this workspace.
//!
//! # The adapter is deliberately here and not shipped
//!
//! `omega-backend-cv` keeps a single runtime dependency (`num-complex`) so it
//! stays embeddable, so it cannot depend on the parser outside `[dev-dependencies]`.
//! Driving a `CvProgram` therefore happens on the consumer side. Shipping a
//! reusable adapter (CLI subcommand, bridge entry point) is follow-up work; this
//! test is the proof that the data path is correct, not the product surface.

use num_complex::Complex64;
use omega_backend_cv::FockState;
use omega_parser::{lower_opticqasm_cv, parse_opticqasm, CvOp};
use std::path::PathBuf;

/// Same tolerances, and for the same reason, as `piquasso_xcheck.rs`: both
/// sides evaluate the same analytic expressions in f64, so anything looser than
/// a few ulps would be a tolerance chosen to make the test pass rather than one
/// derived from the arithmetic.
const PROB_TOL: f64 = 1e-14;
const AMP_TOL: f64 = 1e-13;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("tools/cv_cross_check/piquasso_fixture.jsonl")
}

struct Case {
    name: String,
    cutoff: usize,
    ops: Vec<serde_json::Value>,
    probs: Vec<f64>,
    amps: Vec<Complex64>,
}

fn load() -> Vec<Case> {
    let raw = std::fs::read_to_string(fixture_path()).expect("piquasso fixture");
    let mut out = Vec::new();
    for line in raw.lines().filter(|l| !l.trim().is_empty()) {
        let v: serde_json::Value = serde_json::from_str(line).expect("fixture line is not JSON");
        if v.get("case").is_none() {
            continue; // the `meta` header line
        }
        out.push(Case {
            name: v["case"].as_str().unwrap().to_string(),
            cutoff: v["cutoff"].as_u64().unwrap() as usize,
            ops: v["ops"].as_array().unwrap().clone(),
            probs: v["probs"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_f64().unwrap())
                .collect(),
            amps: v["amps"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| {
                    let p = p.as_array().unwrap();
                    Complex64::new(p[0].as_f64().unwrap(), p[1].as_f64().unwrap())
                })
                .collect(),
        });
    }
    assert!(out.len() > 10, "fixture shrank to {} cases", out.len());
    out
}

/// Render a fixture recipe as OPTICQASM source.
///
/// `vacuum` produces no line: it is the implicit initial state of a `photon`
/// register, exactly as it is the implicit initial state of a `qreg`. Returns
/// `None` for a recipe OPTICQASM cannot spell, so those cases are reported as
/// skipped rather than silently passing.
fn to_opticqasm_source(ops: &[serde_json::Value]) -> Option<String> {
    let mut lines = vec!["OPTICQASM 1.0;".to_string(), "photon q[1];".to_string()];
    for op in ops {
        match op["op"].as_str()? {
            "vacuum" => {}
            "squeeze" => {
                // The fixture carries only `r`; OPTICQASM's `squeeze` takes
                // (r, phi) to match piquasso's `Squeezing(r, phi)`, so phi = 0
                // is what the fixture means.
                lines.push(format!("squeeze({}, 0) q[0];", op["r"].as_f64()?));
            }
            "displace" => lines.push(format!(
                "displace({}, {}) q[0];",
                op["re"].as_f64()?,
                op["im"].as_f64()?
            )),
            "kerr" => lines.push(format!("kerr({}) q[0];", op["chi"].as_f64()?)),
            "phase_shift" => lines.push(format!("ps({}) q[0];", op["phi"].as_f64()?)),
            _ => return None,
        }
    }
    Some(lines.join("\n") + "\n")
}

/// Execute an imported `CvProgram` on `omega-backend-cv`.
///
/// Preparation conventions match `piquasso_xcheck.rs::build` exactly, and they
/// are not arbitrary: on a pristine vacuum both `squeeze` and `displace` use the
/// **constructors**, which carry an exact analytic tail, while `displace` on a
/// state with structure uses the operator. Diverging from that here would make
/// this test disagree with its sibling for reasons having nothing to do with
/// OPTICQASM.
fn execute(program: &omega_parser::CvProgram, cutoff: usize) -> Result<FockState, String> {
    let mut state: Option<FockState> = None;
    let mut pristine = true;

    for (i, op) in program.ops.iter().enumerate() {
        match *op {
            CvOp::Squeeze { r, phi, .. } => {
                if !pristine {
                    return Err(format!("op {i}: squeeze after preparation"));
                }
                if phi != 0.0 {
                    return Err(format!("op {i}: squeezed_vacuum takes only r"));
                }
                state = Some(FockState::squeezed_vacuum(r, cutoff).map_err(|e| e.to_string())?);
                pristine = false;
            }
            CvOp::Displace { re, im, .. } => {
                let alpha = Complex64::new(re, im);
                match state.as_mut() {
                    None => {
                        state = Some(FockState::coherent(alpha, cutoff).map_err(|e| e.to_string())?)
                    }
                    Some(_) if pristine => {
                        state = Some(FockState::coherent(alpha, cutoff).map_err(|e| e.to_string())?)
                    }
                    Some(s) => s.displace(alpha).map_err(|e| e.to_string())?,
                }
                pristine = false;
            }
            CvOp::Kerr { chi, .. } => {
                state
                    .as_mut()
                    .ok_or("gate before preparation")?
                    .kerr(chi)
                    .map_err(|e| e.to_string())?;
                pristine = false;
            }
            CvOp::PhaseShift { phi, .. } => {
                state
                    .as_mut()
                    .ok_or("gate before preparation")?
                    .phase_shift(phi)
                    .map_err(|e| e.to_string())?;
                pristine = false;
            }
            CvOp::BeamSplitter { .. } => {
                return Err("two-mode: no beamsplitter on a single-mode backend".into())
            }
        }
    }
    // An empty op list means the vacuum, which is a legitimate program.
    Ok(match state {
        Some(s) => s,
        None => FockState::vacuum(cutoff).map_err(|e| e.to_string())?,
    })
}

fn probabilities(state: &FockState) -> Vec<f64> {
    let norm = state.norm_sqr();
    state
        .amplitudes()
        .iter()
        .map(|a| if norm > 0.0 { a.norm_sqr() / norm } else { 0.0 })
        .collect()
}

/// Global phase is unobservable, so it must be quotiented out before comparing
/// amplitudes — otherwise the test would be asserting a convention neither side
/// promises. Aligns on the largest-magnitude entry, which is the numerically
/// stable choice.
fn max_amp_diff_up_to_global_phase(ours: &[Complex64], theirs: &[Complex64]) -> f64 {
    let pivot = theirs
        .iter()
        .enumerate()
        .max_by(|a, b| a.1.norm().partial_cmp(&b.1.norm()).unwrap())
        .map(|(i, _)| i)
        .unwrap_or(0);
    let (a, b) = (ours[pivot], theirs[pivot]);
    let phase = if a.norm() > 1e-12 && b.norm() > 1e-12 {
        (b / b.norm()) * (a / a.norm()).conj()
    } else {
        Complex64::new(1.0, 0.0)
    };
    ours.iter()
        .zip(theirs.iter())
        .map(|(o, t)| (o * phase - t).norm())
        .fold(0.0, f64::max)
}

/// The claim: one OPTICQASM source, two backends, the same numbers.
#[test]
fn opticqasm_source_computes_the_same_state_on_our_backend_as_on_piquasso() {
    let cases = load();
    let mut compared = 0usize;
    let mut skipped: Vec<String> = Vec::new();

    for case in &cases {
        let Some(src) = to_opticqasm_source(&case.ops) else {
            skipped.push(format!("{} (recipe not spellable)", case.name));
            continue;
        };

        // The middle arrow: text -> program. A failure here is the D1 defect
        // returning, and it is a hard failure, never a skip.
        let parsed = parse_opticqasm(&src)
            .unwrap_or_else(|e| panic!("{}: OPTICQASM does not parse: {e}\n{src}", case.name));
        let program = lower_opticqasm_cv(&parsed)
            .unwrap_or_else(|e| panic!("{}: OPTICQASM does not import: {e}\n{src}", case.name));

        let state = match execute(&program, case.cutoff) {
            Ok(s) => s,
            // Executor limits (documented on `executable_on_builtin_cv`) are a
            // property of this backend, not of the language.
            Err(why) => {
                skipped.push(format!("{} ({why})", case.name));
                continue;
            }
        };

        let ours = probabilities(&state);
        let n = ours.len().min(case.probs.len());
        assert!(n > 0, "{}: empty comparison", case.name);

        // Normalise against the represented mass before comparing, exactly as
        // `probabilities()` does and as `piquasso_xcheck.rs` does. piquasso's
        // `state_vector` is normalised to 1; ours carries a truncation deficit
        // (`lost_norm`) at the cutoff. Comparing raw amplitudes therefore
        // measures the truncation, not a disagreement — it showed up as a
        // 1.7e-12 "failure" on `squeezed_r=0.3` while the probabilities, which
        // were already normalised, agreed to 1e-14.
        let norm = state.norm_sqr().sqrt();
        let ours_amps: Vec<Complex64> = state.amplitudes()[..n]
            .iter()
            .map(|a| if norm > 0.0 { a / norm } else { *a })
            .collect();
        let amp_diff = max_amp_diff_up_to_global_phase(&ours_amps, &case.amps[..n]);
        assert!(
            amp_diff <= AMP_TOL,
            "{}: amplitudes differ from piquasso by {amp_diff:.3e} (tolerance {AMP_TOL:.1e}) \
             after removing global phase.\nThe SAME OPTICQASM source was executed by both:\n{src}",
            case.name
        );

        let prob_diff = (0..n)
            .map(|i| (ours[i] - case.probs[i]).abs())
            .fold(0.0, f64::max);
        assert!(
            prob_diff <= PROB_TOL,
            "{}: Fock probabilities differ from piquasso by {prob_diff:.3e} \
             (tolerance {PROB_TOL:.1e}).\nSource:\n{src}",
            case.name
        );

        compared += 1;
    }

    // **A skip must not be able to launder a failure.**
    //
    // The first version of this assertion was `compared >= 10`, and it was the
    // recurring defect of this repository in its purest form. Of the 17 fixture
    // cases, 7 involve `squeeze` — so `17 - 7 = 10`, and the floor was set to
    // exactly the number that survives when squeezing is completely broken.
    //
    // Measured: swapping `r` and `phi` in `lower_cv_gate`'s `squeeze` arm made
    // every squeeze case fail `execute()`, which converted each into a *skip*,
    // and this test reported "10 cases agree, 7 skipped" and PASSED. The named
    // acceptance criterion of the whole plan was green while the operation it
    // was built to check produced nothing at all.
    //
    // So the count is pinned exactly and the skip list must be empty. Every
    // executor limitation this backend has (single-mode, squeeze-as-constructor)
    // is static and already avoided by the fixture, so a skip appearing is new
    // information and must fail rather than quietly shrink the coverage.
    assert!(
        skipped.is_empty(),
        "{} case(s) were skipped instead of compared: {skipped:?}\n\
         A skip is how a broken operation hides here — it is not a pass. If a \
         genuine new executor limit is being added, state it explicitly rather \
         than letting the case fall out of the comparison.",
        skipped.len()
    );
    assert_eq!(
        compared,
        cases.len(),
        "compared {compared} of {} fixture cases; every case must be driven \
         through OPTICQASM or the coverage claim is false",
        cases.len()
    );
    eprintln!(
        "OPTICQASM -> omega-backend-cv vs piquasso: {compared} cases agree \
         (amp {AMP_TOL:.0e}, prob {PROB_TOL:.0e}); {} skipped: {skipped:?}",
        skipped.len()
    );
}

/// Pins the property the comparison above *depends on*: that the amplitude
/// metric can see a diagonal gate at all.
///
/// The earlier docstring here claimed this guarded against `to_opticqasm_source`
/// emitting a constant circuit. It did not — it never calls that function — and
/// that hole does not exist anyway, since the reference numbers are fixed in the
/// fixture and a constant circuit would disagree with 16 of the 17 rows. The
/// real hole was the skip-swallowing above, which is now closed by asserting the
/// skip list is empty.
///
/// What this genuinely establishes: `kerr` moves ONLY phases, so a wrong angle
/// is invisible in the probability vector. If the comparison above used `probs`
/// alone, a no-op `kerr` would sail through it. That is why it compares
/// amplitudes, and this test fails if that reasoning ever stops holding.
#[test]
fn a_wrong_parameter_in_the_source_is_detected() {
    let cutoff = 20;
    let good = "OPTICQASM 1.0;\nphoton q[1];\nsqueeze(0.5, 0) q[0];\nkerr(0.3) q[0];\n";
    let bad = "OPTICQASM 1.0;\nphoton q[1];\nsqueeze(0.5, 0) q[0];\nkerr(0.4) q[0];\n";

    let run = |src: &str| {
        let p = lower_opticqasm_cv(&parse_opticqasm(src).unwrap()).unwrap();
        execute(&p, cutoff).unwrap()
    };
    let (a, b) = (run(good), run(bad));

    // Kerr is diagonal: it moves ONLY phases, so a wrong chi is invisible in
    // the probability vector. This is exactly why the test above compares
    // amplitudes and not just probabilities.
    let prob_diff = probabilities(&a)
        .iter()
        .zip(probabilities(&b).iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0, f64::max);
    assert!(
        prob_diff <= PROB_TOL,
        "a Kerr angle should be invisible in probabilities, but differs by {prob_diff:.3e} — \
         if this ever fails, the reasoning behind comparing amplitudes has changed"
    );

    let amp_diff = max_amp_diff_up_to_global_phase(a.amplitudes(), b.amplitudes());
    assert!(
        amp_diff > AMP_TOL,
        "a wrong Kerr angle produced identical amplitudes ({amp_diff:.3e}) — the \
         cross-backend comparison above cannot detect a parameter error"
    );
}
