[package]
name = "qaoa-qubo-self-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qaoa_qubo_self"
path = "src/main.rs"

[dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
