// SPDX-License-Identifier: Apache-2.0
//! spectra — the SPECTRA two-tier quantum-advantage certificate
//! (Mancilla–Tagliani, "The Fourier Wall", arXiv:2607.15815) run over
//! three datasets with known ground truth:
//!
//!   1. UCI Cleveland heart (open tabular)   → must be REFUSED,
//!   2. controlled sparse pocket (§6.2)      → must be REFUSED — the
//!      order-matched JOINT lane finds the single planted 3-way term
//!      and closes the gap (the panel-completeness calibration),
//!   3. disordered-Heisenberg substrate (§6.3, generated by the shipped
//!      spectra_heisenberg.aria circuit) → must be CERTIFIED — the
//!      dynamics-matched quantum lane beats every classical lane with a
//!      positive bootstrap lower bound AND passes the ON−OFF
//!      entanglement-ablation gate.
//!
//! WHAT: Tier 1 screens structure without training a quantum model
//!   (off-grid spectral ratio ρ_off, periodicity vs chance, qubit
//!   feasibility d ≤ 14). Tier 2 trains the quantum lane against five
//!   classical competitors on identical splits — LogReg, trained-
//!   frequency Fourier GAM, GA2M, boosted stumps, order-matched JOINT —
//!   and certifies iff CI_lo(AUC_QNN − max classical) > 0 under a paired
//!   stratified bootstrap, plus the ablation gate.
//! QUANTUM: the generic Fourier-encoding QNN (trainable non-integer
//!   frequencies + RBS entanglers) for tabular sets; the dynamics-
//!   matched lane (trainable Heisenberg couplings on the generator
//!   circuit) for the substrate. The substrate's probe row is verified
//!   against the independent statevector oracle, |Δ| ≤ 1e-9, and the
//!   |+⟩^⊗7 eigenstate invariant (⟨ΣZZ⟩ = 0 at φ = 0, Trotter-exact) is
//!   asserted.
//! CLASSICAL: the five-lane panel above; the certification arithmetic
//!   itself (AUC, bootstrap) is shared by both sides.
//! CHECK: oracle Δ ≤ 1e-9 AND heart refused AND pocket refused AND
//!   substrate certified.

pub mod arch;
pub mod evolve;
mod gen;
mod lanes;
pub mod noise;
mod qnn;
pub mod scale;

use aria_verify_core::data::{self, SplitMix64};
use aria_verify_core::{banner, harness, resolve, sim, Observable, Transport, Verdict};
use omega_backend_statevector::StatevectorBackend;

use gen::Dataset;
use lanes::{auc, bootstrap_delta_ci_lo, logreg_fit, logreg_score};

const SEED: u64 = 26071581;
const TROTTER_STEPS: i64 = 3;
const TOTAL_TIME: f64 = 2.0;
const N_SYNTH: usize = 480;
const BOOT_REPS: usize = 200;

/// Stratified half/half split; returns (train_idx, test_idx).
fn split(y: &[f64], seed: u64) -> (Vec<usize>, Vec<usize>) {
    let mut rng = SplitMix64(seed);
    let (mut tr, mut te) = (Vec::new(), Vec::new());
    for class in [1.0, -1.0] {
        let mut idx: Vec<usize> = (0..y.len()).filter(|&i| y[i] == class).collect();
        // Fisher–Yates with the shared deterministic generator.
        for k in (1..idx.len()).rev() {
            let j = (rng.next_f64() * (k + 1) as f64) as usize % (k + 1);
            idx.swap(k, j);
        }
        for (pos, i) in idx.into_iter().enumerate() {
            if pos % 2 == 0 {
                tr.push(i)
            } else {
                te.push(i)
            }
        }
    }
    (tr, te)
}

fn take(rows: &[Vec<f64>], idx: &[usize]) -> Vec<Vec<f64>> {
    idx.iter().map(|&i| rows[i].clone()).collect()
}
fn take1(v: &[f64], idx: &[usize]) -> Vec<f64> {
    idx.iter().map(|&i| v[i]).collect()
}

/// Tier-1 structural screen. Returns `None` if the dataset is a
/// candidate, `Some(reason)` if it is refused outright.
///
/// Gates (arXiv:2607.15815 Alg. 1, no quantum simulation involved):
///   g1 (C1)  ρ_off > 0.3 — off-grid share of the periodogram mass;
///   g2       (advisory) a trained-frequency Fourier GAM's holdout AUC —
///            printed for context but never refusing: a classifier at
///            chance is evidence of missing structure, not proof (the
///            paper's tier 1 refuses only on *provable* failures; pure
///            noise is safely refused at tier 2, where no quantum lane
///            can beat the panel with a positive CI bound);
///   g5       d ≤ 14 qubits feasibility.
fn tier1_screen(ds: &Dataset, seed: u64) -> Option<String> {
    let d = ds.phases[0].len();
    if d > 14 {
        return Some(format!("infeasible: d = {d} > 14 qubits"));
    }
    // g1: per-feature periodogram over the continuum grid; integer-grid
    // mass = power within ±0.075 of an integer frequency.
    let (mut total, mut integer) = (0.0, 0.0);
    for j in 0..d {
        let col: Vec<f64> = ds.phases.iter().map(|p| p[j]).collect();
        for f in lanes::freq_grid() {
            let p = lanes::periodogram_power(&col, &ds.y, f);
            total += p;
            if (f - f.round()).abs() < 0.075 {
                integer += p;
            }
        }
    }
    let rho_off = 1.0 - integer / total.max(1e-12);
    // C3 advisory (near-independence): max |off-diagonal Pearson
    // correlation| among the phase columns. The paper PCA-whitens the
    // encoded block; we report the measured residual correlation so a
    // correlated tabular set (heart) is visibly different from the
    // independent synthetics.
    let mut max_corr = 0.0f64;
    for a in 0..d {
        for b_ in (a + 1)..d {
            let (mut sa, mut sb, mut saa, mut sbb, mut sab) = (0.0, 0.0, 0.0, 0.0, 0.0);
            let m = ds.phases.len() as f64;
            for p in &ds.phases {
                sa += p[a] / m;
                sb += p[b_] / m;
                saa += p[a] * p[a] / m;
                sbb += p[b_] * p[b_] / m;
                sab += p[a] * p[b_] / m;
            }
            let cov = sab - sa * sb;
            let den = ((saa - sa * sa) * (sbb - sb * sb)).sqrt().max(1e-12);
            max_corr = max_corr.max((cov / den).abs());
        }
    }
    // g2: Fourier-GAM classifier vs chance on a held-out half.
    let (tr, te) = split(&ds.y, seed);
    let (trx, try_) = (take(&ds.phases, &tr), take1(&ds.y, &tr));
    let (tex, tey) = (take(&ds.phases, &te), take1(&ds.y, &te));
    let gam_map = lanes::gam_basis(&trx, &try_);
    let w = logreg_fit(
        &trx.iter().map(|p| gam_map(p)).collect::<Vec<_>>(),
        &try_,
        1e-3,
        250,
        0.4,
    );
    let scores: Vec<f64> = tex.iter().map(|p| logreg_score(&w, &gam_map(p))).collect();
    let gam_auc = auc(&scores, &tey);
    println!(
        "    tier-1[{}]: ρ_off = {rho_off:.3} (gate > 0.3), Fourier-GAM holdout AUC = \
         {gam_auc:.3} (advisory), C3 max |corr| = {max_corr:.3} (advisory), d = {d}",
        ds.name
    );
    if rho_off <= 0.3 {
        return Some(format!(
            "spectral mass on the integer grid (ρ_off = {rho_off:.3} ≤ 0.3)"
        ));
    }
    None
}

struct Tier2Outcome {
    certified: bool,
    detail: String,
}

/// Tier-2: five classical lanes vs a quantum lane on identical splits;
/// certification needs CI_lo(Δ) > 0 and (when an ablation is supplied)
/// CI_lo(ON − OFF) > 0.
#[allow(clippy::too_many_arguments)]
fn tier2_certify(
    name: &str,
    train_x: &[Vec<f64>],
    train_y: &[f64],
    test_x: &[Vec<f64>],
    test_y: &[f64],
    qnn_scores: &[f64],
    ablation_scores: Option<&[f64]>,
    seed: u64,
) -> Result<Tier2Outcome, String> {
    // --- classical panel ---
    let raw_fit = logreg_fit(train_x, train_y, 1e-3, 250, 0.4);
    let logreg: Vec<f64> = test_x.iter().map(|p| logreg_score(&raw_fit, p)).collect();

    let gam_map = lanes::gam_basis(train_x, train_y);
    let gam_w = logreg_fit(
        &train_x.iter().map(|p| gam_map(p)).collect::<Vec<_>>(),
        train_y,
        1e-3,
        250,
        0.4,
    );
    let gam: Vec<f64> = test_x
        .iter()
        .map(|p| logreg_score(&gam_w, &gam_map(p)))
        .collect();

    let ga2m_map = lanes::ga2m_basis(train_x, train_y);
    let ga2m_w = logreg_fit(
        &train_x.iter().map(|p| ga2m_map(p)).collect::<Vec<_>>(),
        train_y,
        1e-3,
        250,
        0.4,
    );
    let ga2m: Vec<f64> = test_x
        .iter()
        .map(|p| logreg_score(&ga2m_w, &ga2m_map(p)))
        .collect();

    let stumps = lanes::stumps_fit(train_x, train_y, 150, 0.1);
    let hgb: Vec<f64> = test_x
        .iter()
        .map(|p| lanes::stumps_score(&stumps, p))
        .collect();

    let joint_scan = lanes::joint_basis(train_x, train_y);
    if let Some(cap) = joint_scan.capped_features {
        println!(
            "    tier-2[{name}]: JOINT triple scan capped to the top {cap} features \
             (of {}) by periodogram power",
            train_x[0].len()
        );
    }
    println!(
        "    tier-2[{name}]: JOINT scan found features {:?} at f = ({:.2}, {:.2}, {:.2}), \
         power {:.4}",
        joint_scan.triple,
        joint_scan.freqs[0],
        joint_scan.freqs[1],
        joint_scan.freqs[2],
        joint_scan.best_triple_power
    );
    // C4 advisory (tree-breaking frequency): the joint coordinate
    // u = Σ f_i·φ_i completes Σ|f_i| cycles across the phase cube, so an
    // axis-aligned partitioner needs ≥ 2·Σ|f_i| cells PER FEATURE to
    // tile it — compare with the stump budget actually granted below.
    let joint_cycles: f64 = joint_scan.freqs.iter().map(|f| f.abs()).sum();
    println!(
        "    tier-2[{name}]: C4 advisory — joint coordinate oscillates ~{joint_cycles:.1} \
         cycles vs a 150-stump axis-aligned budget",
    );
    let joint_w = logreg_fit(
        &train_x
            .iter()
            .map(|p| (joint_scan.basis)(p))
            .collect::<Vec<_>>(),
        train_y,
        1e-3,
        250,
        0.4,
    );
    let joint: Vec<f64> = test_x
        .iter()
        .map(|p| logreg_score(&joint_w, &(joint_scan.basis)(p)))
        .collect();

    let lanes_scored: [(&str, &[f64]); 5] = [
        ("logreg", &logreg),
        ("gam", &gam),
        ("ga2m", &ga2m),
        ("stumps", &hgb),
        ("joint", &joint),
    ];
    let mut best: (&str, f64, &[f64]) = ("", -1.0, &logreg);
    for (lane, scores) in lanes_scored {
        let a = auc(scores, test_y);
        println!("    tier-2[{name}]: AUC {lane:>7} = {a:.4}");
        if a > best.1 {
            best = (lane, a, scores);
        }
    }
    let auc_q = auc(qnn_scores, test_y);
    println!(
        "    tier-2[{name}]: AUC quantum = {auc_q:.4}  (best classical: {} = {:.4})",
        best.0, best.1
    );

    let ci_lo = bootstrap_delta_ci_lo(qnn_scores, best.2, test_y, BOOT_REPS, seed);
    println!(
        "    tier-2[{name}]: paired bootstrap CI_lo(Δ = quantum − {}) = {ci_lo:+.4} \
         ({BOOT_REPS} reps; certify needs > 0)",
        best.0
    );

    let mut certified = ci_lo > 0.0;
    let mut detail = format!(
        "quantum {auc_q:.4} vs best classical {} {:.4}, CI_lo(Δ) = {ci_lo:+.4}",
        best.0, best.1
    );
    if let Some(off) = ablation_scores {
        let ci_ab = bootstrap_delta_ci_lo(qnn_scores, off, test_y, BOOT_REPS, seed ^ 0xAB);
        let auc_off = auc(off, test_y);
        println!(
            "    tier-2[{name}]: ablation (couplings OFF) AUC = {auc_off:.4}, \
             CI_lo(ON − OFF) = {ci_ab:+.4} (certify needs > 0)"
        );
        certified = certified && ci_ab > 0.0;
        detail.push_str(&format!(", ablation CI_lo = {ci_ab:+.4}"));
    }
    Ok(Tier2Outcome { certified, detail })
}

/// Rank-transform arbitrary real columns to phases in [−π, π] (the
/// paper's φ(X) map for raw tabular data).
fn rank_phases(rows: &[Vec<f64>]) -> Vec<Vec<f64>> {
    let n = rows.len();
    let d = rows[0].len();
    let mut out = vec![vec![0.0; d]; n];
    for j in 0..d {
        let mut order: Vec<usize> = (0..n).collect();
        order.sort_by(|&a, &b| rows[a][j].partial_cmp(&rows[b][j]).unwrap());
        for (rank, &i) in order.iter().enumerate() {
            out[i][j] =
                (rank as f64 + 0.5) / n as f64 * 2.0 * std::f64::consts::PI - std::f64::consts::PI;
        }
    }
    out
}

pub fn run(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "spectra",
        "SPECTRA certificate (arXiv:2607.15815): refuse advantage on open/enumerable data, \
         certify it on the quantum-generated Heisenberg substrate",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();

    // ---- The generator circuit + its verification. ----
    let lowered = harness::load_lowered(
        "spectra_heisenberg.aria",
        "SpectraHeisenberg",
        &[("steps", TROTTER_STEPS)],
    )?;
    let jt_ids: Vec<u32> = (0..6)
        .map(|k| {
            lowered
                .symbol_ids
                .get(&format!("jt_{k}"))
                .copied()
                .ok_or(format!("missing jt_{k}"))
        })
        .collect::<Result<_, _>>()?;
    let pt_ids: Vec<u32> = (0..7)
        .map(|i| {
            lowered
                .symbol_ids
                .get(&format!("pt_{i}"))
                .copied()
                .ok_or(format!("missing pt_{i}"))
        })
        .collect::<Result<_, _>>()?;
    let dt = TOTAL_TIME / TROTTER_STEPS as f64;
    let correlator =
        Observable::parse("1.0*Z0Z1 + 1.0*Z1Z2 + 1.0*Z2Z3 + 1.0*Z3Z4 + 1.0*Z4Z5 + 1.0*Z5Z6")?;
    let couplings = gen::heisenberg_couplings(SEED);
    println!(
        "  generator: 7-site disordered Heisenberg chain, J = [{}], T = {TOTAL_TIME}, \
         {TROTTER_STEPS} Trotter steps, seed {SEED}",
        couplings
            .iter()
            .map(|j| format!("{j:.3}"))
            .collect::<Vec<_>>()
            .join(", ")
    );

    // Eigenstate invariant: at φ = 0, |+⟩^⊗7 is a simultaneous
    // eigenstate of every Trotter slice → ⟨Σ ZZ⟩ = 0 exactly.
    let zero_corr = gen::heisenberg_correlator(
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &[0.0; 7],
        &correlator,
    )?;
    if zero_corr.abs() > 1e-9 {
        return Err(format!(
            "|+⟩ eigenstate invariant violated: ⟨ΣZZ⟩ = {zero_corr} at φ = 0"
        ));
    }
    println!("  |+⟩^⊗7 invariant: ⟨ΣZZ⟩ at φ = 0 is {zero_corr:.2e} (Trotter-exact 0) — OK");

    // Differential oracle check on a probe row THROUGH the transport.
    let mut rng = SplitMix64(SEED ^ 0x9E);
    let probe: Vec<f64> = (0..7)
        .map(|_| (rng.next_f64() * 2.0 - 1.0) * std::f64::consts::PI)
        .collect();
    let mut probe_params = vec![0.0; lowered.symbol_ids.len()];
    for (&id, &j) in jt_ids.iter().zip(&couplings) {
        probe_params[id as usize] = j * dt;
    }
    for (&id, &p) in pt_ids.iter().zip(&probe) {
        probe_params[id as usize] = p * dt;
    }
    let mut quantum_profile = Vec::with_capacity(7);
    for q in 0..7 {
        let obs = Observable::parse(&format!("1.0*Z{q}"))?;
        let (_payload, z) = harness::execute_report(
            transport,
            lowered.ir.clone(),
            harness::AppMode::Expectations(vec![obs]),
            &probe_params,
        )?;
        quantum_profile.push(z);
    }
    let oracle = sim::forward_z_expectations(&lowered.ir, &probe_params)?;
    let forward_verdict = banner::report_values(
        "spectra/forward",
        "omega ⟨Z_q⟩ profile, probe row",
        &quantum_profile,
        "independent in-tree statevector oracle",
        &oracle[..7],
        1e-9,
    );

    // ---- Dataset 1: UCI heart (open tabular; expect REFUSE). ----
    println!("\n  [1/3] UCI Cleveland heart (open tabular data)");
    let heart_rows = data::load_csv("heart_cleveland.csv")?;
    let mut hx = Vec::new();
    let mut hy = Vec::new();
    for row in &heart_rows {
        // 8 continuous-ish features (as the butterfly app), binary label
        // num > 0; rows with missing used-cells skipped.
        let cols = [0usize, 1, 2, 3, 4, 6, 8, 9];
        let feats: Option<Vec<f64>> = cols.iter().map(|&c| row[c]).collect();
        if let (Some(f), Some(num)) = (feats, row[13]) {
            hx.push(f);
            hy.push(if num > 0.0 { 1.0 } else { -1.0 });
        }
    }
    let heart = Dataset {
        phases: rank_phases(&hx),
        y: hy,
        name: "heart",
    };
    let heart_refused = match tier1_screen(&heart, SEED ^ 31) {
        Some(reason) => {
            println!("    → REFUSED at tier 1: {reason}");
            true
        }
        None => {
            let (tr, te) = split(&heart.y, SEED ^ 1);
            let (trx, try_) = (take(&heart.phases, &tr), take1(&heart.y, &tr));
            let (tex, tey) = (take(&heart.phases, &te), take1(&heart.y, &te));
            let mut q = qnn::TabularQnn::new(trx[0].len(), SEED ^ 11, true);
            q.fit(&backend, &trx, &try_, 25, 0.05)?;
            let qs = q.scores(&backend, &tex)?;
            // ON−OFF ablation lane (entanglers removed, same budget) —
            // the paper's mechanism gate applies to every certification
            // decision, refusals included.
            let mut q_off = qnn::TabularQnn::new(trx[0].len(), SEED ^ 11, false);
            q_off.fit(&backend, &trx, &try_, 25, 0.05)?;
            let offs = q_off.scores(&backend, &tex)?;
            let out = tier2_certify(
                "heart",
                &trx,
                &try_,
                &tex,
                &tey,
                &qs,
                Some(&offs),
                SEED ^ 21,
            )?;
            println!(
                "    → {} at tier 2: {}",
                if out.certified {
                    "CERTIFIED"
                } else {
                    "REFUSED"
                },
                out.detail
            );
            !out.certified
        }
    };

    // ---- Dataset 2: sparse pocket (expect REFUSE via JOINT). ----
    println!("\n  [2/3] controlled sparse pocket (planted 3-way term, §6.2)");
    let pocket = gen::sparse_pocket(N_SYNTH, SEED ^ 2);
    let pocket_refused = match tier1_screen(&pocket, SEED ^ 32) {
        Some(reason) => {
            println!("    → REFUSED at tier 1: {reason} (unexpected — pocket should reach tier 2)");
            true
        }
        None => {
            let (tr, te) = split(&pocket.y, SEED ^ 3);
            let (trx, try_) = (take(&pocket.phases, &tr), take1(&pocket.y, &tr));
            let (tex, tey) = (take(&pocket.phases, &te), take1(&pocket.y, &te));
            let mut q = qnn::TabularQnn::new(3, SEED ^ 12, true);
            q.fit(&backend, &trx, &try_, 25, 0.05)?;
            let qs = q.scores(&backend, &tex)?;
            let mut q_off = qnn::TabularQnn::new(3, SEED ^ 12, false);
            q_off.fit(&backend, &trx, &try_, 25, 0.05)?;
            let offs = q_off.scores(&backend, &tex)?;
            let out = tier2_certify(
                "pocket",
                &trx,
                &try_,
                &tex,
                &tey,
                &qs,
                Some(&offs),
                SEED ^ 22,
            )?;
            println!(
                "    → {} at tier 2: {}",
                if out.certified {
                    "CERTIFIED"
                } else {
                    "REFUSED"
                },
                out.detail
            );
            !out.certified
        }
    };

    // ---- Dataset 3: Heisenberg substrate (expect CERTIFY). ----
    println!("\n  [3/3] quantum-generated Heisenberg substrate (§6.3)");
    let dense = gen::heisenberg(
        N_SYNTH,
        SEED ^ 4,
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &correlator,
    )?;
    let dense_certified = match tier1_screen(&dense, SEED ^ 33) {
        Some(reason) => {
            println!("    → REFUSED at tier 1: {reason} (unexpected)");
            false
        }
        None => {
            let (tr, te) = split(&dense.y, SEED ^ 5);
            let (trx, try_) = (take(&dense.phases, &tr), take1(&dense.y, &tr));
            let (tex, tey) = (take(&dense.phases, &te), take1(&dense.y, &te));
            let mut dmq = qnn::DmqLane::new(&lowered.ir, &jt_ids, &pt_ids, dt, &correlator);
            dmq.fit(&backend, &trx, &try_, 30, 0.05)?;
            println!(
                "    DMQ learned couplings: [{}] (true: [{}])",
                dmq.couplings
                    .iter()
                    .map(|j| format!("{j:.3}"))
                    .collect::<Vec<_>>()
                    .join(", "),
                couplings
                    .iter()
                    .map(|j| format!("{j:.3}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            let qs = dmq.scores(&backend, &tex)?;
            let mut off = dmq.ablated();
            off.fit_head_only(&backend, &trx, &try_)?;
            let offs = off.scores(&backend, &tex)?;
            let out = tier2_certify(
                "substrate",
                &trx,
                &try_,
                &tex,
                &tey,
                &qs,
                Some(&offs),
                SEED ^ 23,
            )?;
            println!(
                "    → {} at tier 2: {}",
                if out.certified {
                    "CERTIFIED"
                } else {
                    "REFUSED"
                },
                out.detail
            );
            out.certified
        }
    };

    // ---- Verdict. ----
    println!(
        "\n  SPECTRA outcomes: heart {} | pocket {} | substrate {}",
        if heart_refused {
            "REFUSED ✓"
        } else {
            "certified ✗"
        },
        if pocket_refused {
            "REFUSED ✓"
        } else {
            "certified ✗"
        },
        if dense_certified {
            "CERTIFIED ✓"
        } else {
            "refused ✗"
        },
    );
    let pass = forward_verdict.pass && heart_refused && pocket_refused && dense_certified;
    Ok(Verdict {
        name: "spectra".into(),
        pass,
        max_abs_diff: forward_verdict.max_abs_diff,
        tol: forward_verdict.tol,
    })
}

/// arch_search — coupling-graph architecture search on the Heisenberg
/// substrate (see `arch.rs` for the space and training).
///
/// CHECK: (a) the programmatic circuit builder reproduces the lowered
/// spectra_heisenberg.aria on a probe row (|Δ| ≤ 1e-9); (b) the search,
/// given only the labelled data, selects the generator's CHAIN graph
/// under a parsimony-penalised score; (c) the winner's learned couplings
/// approximate the true disorder draw (max |ΔJ| ≤ 0.2) and its holdout
/// AUC ≥ 0.85.
pub fn arch_search(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "arch_search",
        "architecture search over coupling graphs: rediscover the Heisenberg chain \
         from labelled data alone",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();
    let lowered = harness::load_lowered(
        "spectra_heisenberg.aria",
        "SpectraHeisenberg",
        &[("steps", TROTTER_STEPS)],
    )?;
    let jt_ids: Vec<u32> = (0..6)
        .map(|k| {
            lowered
                .symbol_ids
                .get(&format!("jt_{k}"))
                .copied()
                .ok_or(format!("missing jt_{k}"))
        })
        .collect::<Result<_, _>>()?;
    let pt_ids: Vec<u32> = (0..7)
        .map(|i| {
            lowered
                .symbol_ids
                .get(&format!("pt_{i}"))
                .copied()
                .ok_or(format!("missing pt_{i}"))
        })
        .collect::<Result<_, _>>()?;
    let dt = TOTAL_TIME / TROTTER_STEPS as f64;
    let correlator =
        Observable::parse("1.0*Z0Z1 + 1.0*Z1Z2 + 1.0*Z2Z3 + 1.0*Z3Z4 + 1.0*Z4Z5 + 1.0*Z5Z6")?;
    let couplings = gen::heisenberg_couplings(SEED);

    // (a) builder ≡ shipped example on a probe row.
    let mut rng = SplitMix64(SEED ^ 0xA5C);
    let probe: Vec<f64> = (0..7)
        .map(|_| (rng.next_f64() * 2.0 - 1.0) * std::f64::consts::PI)
        .collect();
    let aria_val = gen::heisenberg_correlator(
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &probe,
        &correlator,
    )?;
    let chain = &arch::candidates()[0];
    let (built_ir, bjt, bpt) = arch::build_ir(&chain.bonds, TROTTER_STEPS as usize);
    let built_val = gen::heisenberg_correlator(
        &backend,
        &built_ir,
        &bjt,
        &bpt,
        &couplings,
        dt,
        &probe,
        &correlator,
    )?;
    let builder_verdict = banner::report_values(
        "arch_search/builder",
        "programmatic coupling-graph builder (chain)",
        &[built_val],
        "lowered spectra_heisenberg.aria",
        &[aria_val],
        1e-9,
    );

    // Dataset: the SAME substrate the spectra certificate uses.
    let dense = gen::heisenberg(
        N_SYNTH,
        SEED ^ 4,
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &correlator,
    )?;
    let (tr, te) = split(&dense.y, SEED ^ 41);
    // Cheap-evaluation budget: 200 train rows, 10 epochs per candidate
    // (printed — no silent caps).
    let tr = &tr[..200.min(tr.len())];
    let (trx, try_) = (take(&dense.phases, tr), take1(&dense.y, tr));
    let (tex, tey) = (take(&dense.phases, &te), take1(&dense.y, &te));
    println!(
        "  search budget: {} candidates × 10 epochs on {} train rows; holdout {} rows",
        arch::candidates().len(),
        trx.len(),
        tex.len()
    );

    // (b) exhaustive search with a parsimony penalty (0.005·bonds):
    // a strict superset graph (ring ⊃ chain) can always match the chain
    // by zeroing its extra bond, so ties break toward fewer parameters.
    let mut results = Vec::new();
    for cand in arch::candidates() {
        let trained = arch::train_candidate(
            &cand,
            &backend,
            TROTTER_STEPS as usize,
            dt,
            &correlator,
            &trx,
            &try_,
            &tex,
            &tey,
            10,
        )?;
        println!(
            "  candidate {:>8}: holdout AUC = {:.4}  (bonds: {}, penalised score {:.4})",
            trained.name,
            trained.auc,
            trained.bonds.len(),
            trained.auc - 0.005 * trained.bonds.len() as f64,
        );
        results.push(trained);
    }
    results.sort_by(|a, b| {
        let sa = a.auc - 0.005 * a.bonds.len() as f64;
        let sb = b.auc - 0.005 * b.bonds.len() as f64;
        sb.partial_cmp(&sa).unwrap()
    });
    let winner = &results[0];
    println!(
        "  WINNER: '{}' — holdout AUC {:.4}, learned J = [{}] (true chain J = [{}])",
        winner.name,
        winner.auc,
        winner
            .couplings
            .iter()
            .map(|j| format!("{j:.3}"))
            .collect::<Vec<_>>()
            .join(", "),
        couplings
            .iter()
            .map(|j| format!("{j:.3}"))
            .collect::<Vec<_>>()
            .join(", ")
    );

    // (c) ground-truth checks.
    let chain_won = winner.name == "chain";
    let auc_ok = winner.auc >= 0.85;
    let j_close = chain_won
        && winner
            .couplings
            .iter()
            .zip(&couplings)
            .all(|(a, b)| (a - b).abs() <= 0.2);
    if !chain_won {
        println!(
            "  FAIL: search selected '{}', not the generator's chain",
            winner.name
        );
    }
    if !auc_ok {
        println!("  FAIL: winner AUC {:.4} < 0.85", winner.auc);
    }
    if chain_won && !j_close {
        println!("  FAIL: learned couplings deviate > 0.2 from the true draw");
    }

    // The deliverable: the discovered architecture as Aria source.
    let src = arch::to_aria_source(winner, TROTTER_STEPS as usize);
    println!("\n  discovered architecture (Aria source, first lines):");
    for line in src.lines().take(8) {
        println!("    {line}");
    }
    println!("    … ({} lines total)", src.lines().count());

    Ok(Verdict {
        name: "arch_search".into(),
        pass: builder_verdict.pass && chain_won && auc_ok && j_close,
        max_abs_diff: builder_verdict.max_abs_diff,
        tol: builder_verdict.tol,
    })
}

/// arch_evolve — evolutionary search over layered RBS masks on the
/// heart-imputation task (see `evolve.rs`).
///
/// CHECK: (a) determinism — re-evaluating the winning genome reproduces
/// its fitness exactly; (b) expert parity — the evolved architecture's
/// held-out MSE is within 0.02 of the hand-built butterfly genome
/// evaluated under the identical protocol; (c) the winner is no worse
/// than the no-entanglement ablation genome.
pub fn arch_evolve(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "arch_evolve",
        "evolutionary search over layered RBS connectivity masks vs the hand-built \
         butterfly (UCI heart imputation)",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();

    // Heart data, prepared exactly like the butterfly app: 8 features →
    // standardized → atan angles; target thalach → tanh-squashed.
    let rows = data::load_csv("heart_cleveland.csv")?;
    let (means, stds) = data::column_stats(&rows);
    let cols = [0usize, 1, 2, 3, 4, 6, 8, 9];
    let target_col = 7;
    let mut xs = Vec::new();
    let mut ty = Vec::new();
    for row in &rows {
        let feats: Option<Vec<f64>> = cols.iter().map(|&c| row[c]).collect();
        let (Some(feats), Some(target)) = (feats, row[target_col]) else {
            continue;
        };
        xs.push(
            cols.iter()
                .zip(&feats)
                .map(|(&c, &v)| ((v - means[c]) / stds[c]).atan())
                .collect::<Vec<f64>>(),
        );
        ty.push(((target - means[target_col]) / stds[target_col]).tanh());
    }
    let n = xs.len();
    let mut rng = SplitMix64(SEED ^ 0xE0);
    let masked: Vec<bool> = (0..n).map(|_| rng.next_f64() < 0.30).collect();
    let tr: Vec<usize> = (0..n).filter(|&i| !masked[i]).collect();
    let te: Vec<usize> = (0..n).filter(|&i| masked[i]).collect();
    let tr = &tr[..160.min(tr.len())]; // search budget cap (printed)
    let (trx, try_) = (take(&xs, tr), take1(&ty, tr));
    let (tex, tey) = (take(&xs, &te), take1(&ty, &te));
    let (epochs, pop, gens) = (8, 8, 4);
    println!(
        "  budget: population {pop} × {gens} generations, {epochs} epochs each, \
         {} train / {} holdout rows (seed {SEED})",
        trx.len(),
        tex.len()
    );

    // References evaluated under the identical protocol, outside the search.
    let butterfly_mse = evolve::evaluate(
        &evolve::BUTTERFLY_GENOME,
        &backend,
        &trx,
        &try_,
        &tex,
        &tey,
        epochs,
        SEED,
    )?;
    let none_mse = evolve::evaluate(
        &evolve::NONE_GENOME,
        &backend,
        &trx,
        &try_,
        &tex,
        &tey,
        epochs,
        SEED,
    )?;
    println!(
        "  references: hand-built butterfly [{}] MSE = {butterfly_mse:.5}; \
         no-entanglement MSE = {none_mse:.5}",
        evolve::genome_name(&evolve::BUTTERFLY_GENOME)
    );
    // Show the regulariser has teeth: the overlapping chain-full mask
    // loses the one-execution trailing-block property (engine-measured).
    let chain_full = [5usize; evolve::LAYERS];
    let cf_tr = evolve::trainability(&chain_full, &backend, &xs[0])?;
    println!(
        "  regulariser reference: [{}] trainability = {cf_tr:.2} \
         (pays λ·{:.2} = {:.4} in fitness)",
        evolve::genome_name(&chain_full),
        1.0 - cf_tr,
        evolve::TRAINABILITY_LAMBDA * (1.0 - cf_tr),
    );

    let (winner, (fitness, winner_tr, _score), cache) =
        evolve::evolve(&backend, &trx, &try_, &tex, &tey, epochs, SEED, pop, gens)?;
    println!(
        "  EVOLVED: [{}] MSE = {fitness:.5}, trainability = {winner_tr:.2} \
         ({} unique genomes evaluated of {} in the space; λ = {})",
        evolve::genome_name(&winner),
        cache.len(),
        evolve::mask_menu().len().pow(evolve::LAYERS as u32),
        evolve::TRAINABILITY_LAMBDA,
    );

    // (a) determinism.
    let re_eval = evolve::evaluate(&winner, &backend, &trx, &try_, &tex, &tey, epochs, SEED)?;
    let deterministic = re_eval == fitness;
    if !deterministic {
        println!("  FAIL: winner re-evaluation {re_eval} ≠ cached {fitness}");
    }
    // (b) expert parity, (c) entanglement sanity.
    let parity = fitness <= butterfly_mse + 0.02;
    if !parity {
        println!("  FAIL: evolved MSE {fitness:.5} worse than butterfly {butterfly_mse:.5} + 0.02");
    }
    let beats_none = fitness <= none_mse + 1e-9;
    if !beats_none {
        println!("  FAIL: evolved MSE {fitness:.5} worse than no-entanglement {none_mse:.5}");
    }
    // Trainability gate: the regulariser must have kept the winner fully
    // parallel-shift-trainable (every gradient from the one-execution
    // trailing-block rule) despite the overlapping chain-full mask being
    // in the menu.
    let fully_parallel = winner_tr >= 1.0 - 1e-9;
    if !fully_parallel {
        println!(
            "  FAIL: winner trainability {winner_tr:.2} < 1.0 — the regulariser \
             failed to keep the parallel-shift property"
        );
    }
    println!(
        "  verdict inputs: deterministic {deterministic}, expert parity {parity} \
         (Δ = {:+.5}), ≥ ablation {beats_none}",
        fitness - butterfly_mse
    );

    Ok(Verdict {
        name: "arch_evolve".into(),
        pass: deterministic && parity && beats_none && fully_parallel,
        max_abs_diff: (fitness - butterfly_mse).max(0.0),
        tol: 0.02,
    })
}

/// arch_priors — SPECTRA statistics as search priors (QML_ROADMAP).
///
/// The classical supervised joint-periodogram scan (the JOINT lane's
/// Tier-2 statistic — zero quantum evaluations) discovers the sparse
/// pocket's interaction triple and its off-grid frequencies. Seeding
/// the tabular QNN's trainable frequency scalars with those values,
/// instead of a flat init, is the roadmap's "Tier-1/2 statistics →
/// prior over frequencies" step.
///
/// CHECK: with an identical training budget, the prior-informed QNN's
/// holdout AUC exceeds the flat-init QNN's by ≥ 0.03 on the pocket,
/// and the prior itself came from the classical scan (frequencies
/// within 0.25 of the planted (3.7, 5.1, 6.8) after sorting).
pub fn arch_priors(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "arch_priors",
        "classical periodogram statistics as QNN frequency priors on the sparse pocket",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();
    let pocket = gen::sparse_pocket(N_SYNTH, SEED ^ 2);
    let (tr, te) = split(&pocket.y, SEED ^ 51);
    let (trx, try_) = (take(&pocket.phases, &tr), take1(&pocket.y, &tr));
    let (tex, tey) = (take(&pocket.phases, &te), take1(&pocket.y, &te));

    // The classical prior: supervised joint scan on the TRAIN split.
    let scan = lanes::joint_basis(&trx, &try_);
    println!(
        "  classical joint scan (no quantum evaluations): features {:?}, \
         f = ({:.2}, {:.2}, {:.2}), power {:.4}",
        scan.triple, scan.freqs[0], scan.freqs[1], scan.freqs[2], scan.best_triple_power
    );
    // Per-feature prior vector: the scan frequency for each feature in
    // the triple; features outside it (none here, d = 3) keep flat init.
    let mut prior = vec![0.0f64; 3];
    for (k, &feat) in scan.triple.iter().enumerate() {
        prior[feat] = scan.freqs[k];
    }
    let mut sorted = scan.freqs;
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let planted = [3.7, 5.1, 6.8];
    let prior_close = sorted
        .iter()
        .zip(&planted)
        .all(|(a, b)| (a - b).abs() <= 0.25);
    if !prior_close {
        println!("  FAIL: scan frequencies {sorted:?} not within 0.25 of planted {planted:?}");
    }

    // Identical training budget, same seed: flat vs prior-informed.
    // Both lanes get the rich Z-string readout (weight ≤ 3 correlators —
    // where joint harmonics live); ONLY the init differs.
    let epochs = 25;
    let mut flat = qnn::TabularQnn::new(3, SEED ^ 12, true)
        .rich_readout()
        .upload_blocks(1);
    flat.fit(&backend, &trx, &try_, epochs, 0.05)?;
    let auc_flat = lanes::auc(&flat.scores(&backend, &tex)?, &tey);
    let mut informed = qnn::TabularQnn::with_freq_prior(3, SEED ^ 12, true, Some(&prior))
        .rich_readout()
        .upload_blocks(1);
    informed.fit(&backend, &trx, &try_, epochs, 0.05)?;
    let auc_prior = lanes::auc(&informed.scores(&backend, &tex)?, &tey);
    println!(
        "  holdout AUC: flat init = {auc_flat:.4}, periodogram-prior init = {auc_prior:.4} \
         (identical {epochs}-epoch budget, same seed)"
    );
    let improved = auc_prior >= auc_flat + 0.03;
    if !improved {
        println!("  FAIL: prior init did not improve AUC by ≥ 0.03");
    }
    println!(
        "  (context: the classical JOINT lane itself reaches ~0.90 here — the pocket is \
         REFUSED territory regardless; this demo is about the *search signal*, not advantage.)"
    );

    Ok(Verdict {
        name: "arch_priors".into(),
        pass: prior_close && improved,
        max_abs_diff: (auc_flat - auc_prior).max(0.0),
        tol: 0.03,
    })
}

/// spectra_scaling — the substrate at n = 7 … 13 sites (see `scale.rs`).
///
/// CHECK: the |+⟩^⊗n invariant holds (≤ 1e-9) at every size, and the
/// DMQ-vs-classical AUC gap persists (≥ 0.15) at every gap-checked
/// size. The cost curve (deterministic work model + measured wall-clock
/// with fitted exponent and crossover extrapolation) is advisory —
/// timings never gate the verdict.
pub fn spectra_scaling(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "spectra_scaling",
        "the quantum-generated substrate at 7…13 sites: correctness invariants, \
         persistent quantum-classical gap, exponential classical-cost curve",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();
    let dt = TOTAL_TIME / TROTTER_STEPS as f64;

    // (n_sites, samples, gap_check, dmq_epochs) — budgets shrink as the
    // exact simulation cost grows (printed, not silent).
    let plan = [
        (7usize, 320usize, true, 20usize),
        (9, 140, true, 8),
        (11, 120, true, 8),
        (13, 80, false, 0),
    ];
    let mut reports = Vec::new();
    for &(n, samples, gap, epochs) in &plan {
        let rep = scale::run_size(
            n,
            TROTTER_STEPS as usize,
            dt,
            &backend,
            SEED,
            samples,
            gap,
            epochs,
        )?;
        match rep.gap {
            Some((dmq, classical)) => println!(
                "  n = {n:>2}: invariant {:+.1e}, {:.1} ms/sample (work {:.2e}), \
                 DMQ AUC {dmq:.3} vs classical {classical:.3} (gap {:+.3}) \
                 [{samples} samples, {epochs} DMQ epochs]",
                rep.invariant,
                rep.secs_per_sample * 1e3,
                rep.work_per_sample,
                dmq - classical,
            ),
            None => println!(
                "  n = {n:>2}: invariant {:+.1e}, {:.1} ms/sample (work {:.2e}) \
                 [{samples} samples, generation + invariant only]",
                rep.invariant,
                rep.secs_per_sample * 1e3,
                rep.work_per_sample,
            ),
        }
        reports.push(rep);
    }

    // Cost-curve fit (advisory): slope of log2(seconds) vs n.
    let pts: Vec<(f64, f64)> = reports
        .iter()
        .map(|r| (r.n_sites as f64, r.secs_per_sample.max(1e-9).log2()))
        .collect();
    let n_pts = pts.len() as f64;
    let (sx, sy): (f64, f64) = (pts.iter().map(|p| p.0).sum(), pts.iter().map(|p| p.1).sum());
    let sxx: f64 = pts.iter().map(|p| p.0 * p.0).sum();
    let sxy: f64 = pts.iter().map(|p| p.0 * p.1).sum();
    let gamma = (n_pts * sxy - sx * sy) / (n_pts * sxx - sx * sx);
    let intercept = (sy - gamma * sx) / n_pts;
    // Paper-style crossover extrapolation: hardware cost per sample is
    // linear in gate count (~ ops(n) · t_gate); classical exact cost is
    // 2^{γ·n}·c. Illustrative constants: t_gate = 1 µs, shots = 1000.
    let ops_13 = reports.last().unwrap().work_per_sample / (1u64 << 13) as f64;
    let hardware_secs = |n: f64| (ops_13 / 13.0) * n * 1e-6 * 1000.0;
    let classical_secs = |n: f64| (2f64).powf(gamma * n + intercept);
    let mut crossover = 30.0;
    for n10 in 130..300 {
        let n = n10 as f64 / 10.0;
        if classical_secs(n) > hardware_secs(n) {
            crossover = n;
            break;
        }
    }
    println!(
        "  cost curve (advisory): seconds/sample ≈ 2^({gamma:.2}·n {intercept:+.1}); \
         with illustrative hardware constants (1 µs gates × 1000 shots) the \
         exact-simulation crossover lands near n* ≈ {crossover:.0} sites \
         (paper's range: 13–19)",
    );

    let invariants_ok = reports.iter().all(|r| r.invariant.abs() <= 1e-9);
    if !invariants_ok {
        println!("  FAIL: |+⟩^⊗n invariant violated at some size");
    }
    let gaps_ok = reports
        .iter()
        .filter_map(|r| r.gap)
        .all(|(dmq, classical)| dmq - classical >= 0.15);
    if !gaps_ok {
        println!("  FAIL: quantum-classical gap fell below 0.15 at some size");
    }
    let max_inv = reports
        .iter()
        .map(|r| r.invariant.abs())
        .fold(0.0f64, f64::max);
    Ok(Verdict {
        name: "spectra_scaling".into(),
        pass: invariants_ok && gaps_ok,
        max_abs_diff: max_inv,
        tol: 1e-9,
    })
}

/// spectra_noise — noise-robustness scan of the Heisenberg certification.
///
/// The `spectra` harness certifies a genuine advantage on the substrate under
/// an ideal simulator. This asks the follow-up every advantage claim owes:
/// does it survive noise? The dynamics-matched quantum lane is trained once on
/// the ideal simulator (the deployed model), then re-scored through the
/// PauliProp backend — which folds each channel's Heisenberg adjoint into the
/// expectation *exactly* — across a sweep of error rates, for three channels
/// (per-gate depolarizing, amplitude damping, phase damping). All shrink the
/// Pauli expectations toward zero, so the quantum score's discriminating power decays
/// while the classical lanes (scored on the same rows) hold; the gate
/// CI_lo(Δ AUC) > 0 flips CERTIFIED → REFUSED at a crossover rate — the
/// reported robustness margin.
///
/// A final sweep adds finite-shot (measurement/sampling) noise: the correlator
/// is estimated from a shrinking number of Z-basis shots, giving the minimum
/// shot budget the advantage needs.
///
/// A final ADVISORY step probes zero-noise extrapolation (Richardson over
/// depolarizing scales 1/2/3×) and reports — honestly — that 3-point rate
/// scaling gives negligible recovery on this deep circuit; it never gates the
/// verdict.
///
/// CHECK: (a) at zero noise PauliProp reproduces the statevector quantum scores
/// (|Δ| ≤ 1e-6); (b) for EACH channel the substrate CERTIFIES at zero noise and
/// the advantage is destroyed (REFUSED) at the largest swept rate; (c) the shot
/// sweep CERTIFIES at the largest budget and is REFUSED at the smallest.
pub fn spectra_noise(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "spectra_noise",
        "does the certified Heisenberg-substrate advantage survive per-gate noise (depolarizing, \
         amplitude damping, phase damping), and at what rate does it vanish?",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();

    // --- substrate setup (same generator circuit as `spectra`) ---
    let lowered = harness::load_lowered(
        "spectra_heisenberg.aria",
        "SpectraHeisenberg",
        &[("steps", TROTTER_STEPS)],
    )?;
    let jt_ids: Vec<u32> = (0..6)
        .map(|k| {
            lowered
                .symbol_ids
                .get(&format!("jt_{k}"))
                .copied()
                .ok_or(format!("missing jt_{k}"))
        })
        .collect::<Result<_, _>>()?;
    let pt_ids: Vec<u32> = (0..7)
        .map(|i| {
            lowered
                .symbol_ids
                .get(&format!("pt_{i}"))
                .copied()
                .ok_or(format!("missing pt_{i}"))
        })
        .collect::<Result<_, _>>()?;
    let dt = TOTAL_TIME / TROTTER_STEPS as f64;
    let correlator =
        Observable::parse("1.0*Z0Z1 + 1.0*Z1Z2 + 1.0*Z2Z3 + 1.0*Z3Z4 + 1.0*Z4Z5 + 1.0*Z5Z6")?;
    let couplings = gen::heisenberg_couplings(SEED);

    // --- dataset + stratified split (identical to the substrate lane) ---
    let dense = gen::heisenberg(
        N_SYNTH,
        SEED ^ 4,
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &correlator,
    )?;
    let (tr, te) = split(&dense.y, SEED ^ 5);
    let (trx, try_) = (take(&dense.phases, &tr), take1(&dense.y, &tr));
    // The noisy PauliProp expectation is ~seconds per row, so cap the test set
    // for the sweep; the classical lanes are scored on the SAME rows, keeping
    // the paired bootstrap valid. `te` is ordered [positives…, negatives…], so
    // take a class-BALANCED subset — a plain prefix would be single-class and
    // collapse every AUC to the 0.5 tie value.
    const PER_CLASS: usize = 48;
    let mut te_eval: Vec<usize> = te
        .iter()
        .filter(|&&i| dense.y[i] > 0.0)
        .take(PER_CLASS)
        .copied()
        .collect();
    te_eval.extend(
        te.iter()
            .filter(|&&i| dense.y[i] < 0.0)
            .take(PER_CLASS)
            .copied(),
    );
    let (tex, tey) = (take(&dense.phases, &te_eval), take1(&dense.y, &te_eval));

    // --- train the deployed model on the ideal simulator ---
    let mut dmq = qnn::DmqLane::new(&lowered.ir, &jt_ids, &pt_ids, dt, &correlator);
    dmq.fit(&backend, &trx, &try_, 30, 0.05)?;
    let classical = noise::classical_best(&trx, &try_, &tex, &tey);
    println!(
        "  best classical lane on the {} eval rows: {} (AUC {:.4})",
        tex.len(),
        classical.name,
        classical.auc
    );

    // --- zero-noise sanity: PauliProp reproduces the statevector scores ---
    let sv_scores = dmq.scores(&backend, &tex)?;
    let auc_sv = auc(&sv_scores, &tey);
    let pp0_scores = dmq.scores_par(
        &noise::channel_backend(noise::Channel::Depolarizing, 0.0),
        &tex,
    )?;
    let max_diff = sv_scores
        .iter()
        .zip(&pp0_scores)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f64, f64::max);
    println!(
        "  noiseless quantum AUC {auc_sv:.4}; PauliProp(0) − statevector max score Δ = {max_diff:.2e}"
    );

    // --- sweep each channel; report its crossover and gate the verdict ---
    // One decoherence model can flatter or punish a lane; running several shows
    // the margin isn't an artifact of the channel choice.
    let channels = [
        (
            noise::Channel::Depolarizing,
            &[0.0, 0.0025, 0.005, 0.01, 0.02, 0.04][..],
        ),
        (
            noise::Channel::AmplitudeDamping,
            &[0.0, 0.005, 0.01, 0.02, 0.04, 0.08][..],
        ),
        // Phase damping hits only X/Y (Z untouched), so it degrades a Z-basis
        // correlator more slowly — a wider grid to reach the crossover.
        (
            noise::Channel::PhaseDamping,
            &[0.0, 0.02, 0.05, 0.1, 0.2, 0.4][..],
        ),
    ];
    let mut all_channels_ok = true;
    for (channel, rates) in channels {
        println!(
            "  {} sweep ({BOOT_REPS} bootstrap reps; certify needs CI_lo(Δ) > 0):",
            channel.label()
        );
        let mut points = Vec::new();
        for &r in rates {
            // rate 0 is noiseless for EVERY channel, so reuse the one full-term
            // PauliProp(0) evaluation (the slowest call — nonzero rates shrink
            // coefficients and prune faster) instead of recomputing it per channel.
            let qs = if r == 0.0 {
                pp0_scores.clone()
            } else {
                dmq.scores_par(&noise::channel_backend(channel, r), &tex)?
            };
            let pt = noise::certify_point(r, &qs, &classical, &tey, BOOT_REPS, SEED ^ 0x51);
            println!(
                "    rate {:.4}: quantum AUC {:.4}, CI_lo(Δ vs {}) = {:+.4}  → {}",
                pt.rate,
                pt.auc_q,
                classical.name,
                pt.ci_lo,
                if pt.certified { "CERTIFIED" } else { "REFUSED" }
            );
            points.push(pt);
        }
        let cert_at_zero = points[0].certified;
        let refused_at_max = !points.last().unwrap().certified;
        if let Some(crossover) = noise::crossover_rate(&points) {
            println!(
                "  → margin: advantage certified up to a {} rate ≈ {crossover:.4} \
                 (CI_lo(Δ) crosses 0, linearly interpolated)",
                channel.label()
            );
        }
        if !cert_at_zero {
            println!("  FAIL[{}]: did not certify at zero noise", channel.label());
        }
        if !refused_at_max {
            println!(
                "  FAIL[{}]: still certified at the largest swept rate — widen the sweep",
                channel.label()
            );
        }
        all_channels_ok &= cert_at_zero && refused_at_max;
    }

    // --- finite-shot (measurement/sampling) noise ---
    // The channel sweeps use exact expectations (infinite shots). Real hardware
    // also has sampling noise: the correlator is estimated from a finite number
    // of Z-basis measurements. Sweep the shot budget (descending, good → bad) to
    // find how many shots/row the advantage needs.
    println!("  finite-shot sweep (Z-basis sampling of the exact-trained lane; certify needs CI_lo(Δ) > 0):");
    let shot_grid = [16384u32, 1024, 256, 64, 16, 4];
    let mut shot_points = Vec::new();
    for &s in &shot_grid {
        let qs = dmq.scores_shots(&backend, &tex, s, SEED ^ 0x5407)?;
        let pt = noise::certify_point(s as f64, &qs, &classical, &tey, BOOT_REPS, SEED ^ 0x51);
        println!(
            "    {:>5} shots: quantum AUC {:.4}, CI_lo(Δ vs {}) = {:+.4}  → {}",
            s,
            pt.auc_q,
            classical.name,
            pt.ci_lo,
            if pt.certified { "CERTIFIED" } else { "REFUSED" }
        );
        shot_points.push(pt);
    }
    // Descending grid, so crossover_rate finds the CERTIFIED→REFUSED edge and
    // interpolates the minimum shot budget that still certifies.
    if let Some(min_shots) = noise::crossover_rate(&shot_points) {
        println!("  → shot margin: advantage needs ≳ {min_shots:.0} shots/row to certify");
    }
    let shots_ok = shot_points[0].certified && !shot_points.last().unwrap().certified;
    if !shot_points[0].certified {
        println!("  FAIL: did not certify even at the largest shot budget");
    }
    if shot_points.last().unwrap().certified {
        println!("  FAIL: still certified at the smallest shot budget — lower the floor");
    }

    // --- error-mitigation probe: zero-noise extrapolation (ADVISORY) ---
    // Run the depolarizing channel at noise scales {1,2,3}×base and Richardson-
    // extrapolate the correlator to zero: E0 = 3·E1 − 3·E2 + E3. The head is
    // affine and the coefficients sum to 1, so extrapolating the SCORES equals
    // extrapolating the correlator then applying the head — no new estimator.
    // This NEVER gates the verdict: on this deep Trotter circuit the correlator
    // is a high-degree polynomial in the noise rate, so a 3-point extrapolation
    // cannot recover it. We report the (negligible) CI_lo change honestly rather
    // than claim a mitigation win — the reported margin is the raw crossover.
    println!("  zero-noise-extrapolation probe (depolarizing, Richardson 1/2/3×base; ADVISORY):");
    let mut best_gain = f64::NEG_INFINITY;
    for &base in &[0.02, 0.04] {
        let s1 = dmq.scores_par(
            &noise::channel_backend(noise::Channel::Depolarizing, base),
            &tex,
        )?;
        let s2 = dmq.scores_par(
            &noise::channel_backend(noise::Channel::Depolarizing, 2.0 * base),
            &tex,
        )?;
        let s3 = dmq.scores_par(
            &noise::channel_backend(noise::Channel::Depolarizing, 3.0 * base),
            &tex,
        )?;
        let zne: Vec<f64> = (0..tex.len())
            .map(|i| 3.0 * s1[i] - 3.0 * s2[i] + s3[i])
            .collect();
        let raw = noise::certify_point(base, &s1, &classical, &tey, BOOT_REPS, SEED ^ 0x51);
        let mit = noise::certify_point(base, &zne, &classical, &tey, BOOT_REPS, SEED ^ 0x51);
        best_gain = best_gain.max(mit.ci_lo - raw.ci_lo);
        println!(
            "    base {base:.4}: raw AUC {:.4} CI_lo {:+.4} {:9} | ZNE AUC {:.4} CI_lo {:+.4} {}",
            raw.auc_q,
            raw.ci_lo,
            if raw.certified {
                "CERTIFIED"
            } else {
                "REFUSED"
            },
            mit.auc_q,
            mit.ci_lo,
            if mit.certified {
                "CERTIFIED"
            } else {
                "REFUSED"
            }
        );
    }
    println!(
        "  → ZNE probe: best CI_lo(Δ) change = {best_gain:+.4} — 3-point rate-scaling gives \
         negligible recovery on this deep circuit (high-order noise dependence), so the honest \
         margin is the raw crossover, not a mitigated one",
    );

    let sanity_ok = max_diff <= 1e-6;
    if !sanity_ok {
        println!("  FAIL: PauliProp diverged from statevector at zero noise (Δ {max_diff:.2e})");
    }
    Ok(Verdict {
        name: "spectra_noise".into(),
        pass: sanity_ok && all_channels_ok && shots_ok,
        max_abs_diff: max_diff,
        tol: 1e-6,
    })
}
