// SPDX-License-Identifier: Apache-2.0
//! spectra — the SPECTRA two-tier quantum-advantage certificate
//! (Mancilla–Tagliani, "The Fourier Wall", arXiv:2607.15815) run over
//! three datasets with known ground truth:
//!
//!   1. UCI Cleveland heart (open tabular)   → must be REFUSED,
//!   2. controlled sparse pocket (§6.2)      → must be REFUSED — the
//!      order-matched JOINT lane finds the single planted 3-way term
//!      and closes the gap (the panel-completeness calibration),
//!   3. disordered-Heisenberg substrate (§6.3, generated by the shipped
//!      spectra_heisenberg.aria circuit) → must be CERTIFIED — the
//!      dynamics-matched quantum lane beats every classical lane with a
//!      positive bootstrap lower bound AND passes the ON−OFF
//!      entanglement-ablation gate.
//!
//! WHAT: Tier 1 screens structure without training a quantum model
//!   (off-grid spectral ratio ρ_off, periodicity vs chance, qubit
//!   feasibility d ≤ 14). Tier 2 trains the quantum lane against five
//!   classical competitors on identical splits — LogReg, trained-
//!   frequency Fourier GAM, GA2M, boosted stumps, order-matched JOINT —
//!   and certifies iff CI_lo(AUC_QNN − max classical) > 0 under a paired
//!   stratified bootstrap, plus the ablation gate.
//! QUANTUM: the generic Fourier-encoding QNN (trainable non-integer
//!   frequencies + RBS entanglers) for tabular sets; the dynamics-
//!   matched lane (trainable Heisenberg couplings on the generator
//!   circuit) for the substrate. The substrate's probe row is verified
//!   against the independent statevector oracle, |Δ| ≤ 1e-9, and the
//!   |+⟩^⊗7 eigenstate invariant (⟨ΣZZ⟩ = 0 at φ = 0, Trotter-exact) is
//!   asserted.
//! CLASSICAL: the five-lane panel above; the certification arithmetic
//!   itself (AUC, bootstrap) is shared by both sides.
//! CHECK: oracle Δ ≤ 1e-9 AND heart refused AND pocket refused AND
//!   substrate certified.

pub mod arch;
pub mod evolve;
mod gen;
mod lanes;
mod qnn;

use aria_verify_core::data::{self, SplitMix64};
use aria_verify_core::{banner, harness, resolve, sim, Observable, Transport, Verdict};
use omega_backend_statevector::StatevectorBackend;

use gen::Dataset;
use lanes::{auc, bootstrap_delta_ci_lo, logreg_fit, logreg_score};

const SEED: u64 = 26071581;
const TROTTER_STEPS: i64 = 3;
const TOTAL_TIME: f64 = 2.0;
const N_SYNTH: usize = 480;
const BOOT_REPS: usize = 200;

/// Stratified half/half split; returns (train_idx, test_idx).
fn split(y: &[f64], seed: u64) -> (Vec<usize>, Vec<usize>) {
    let mut rng = SplitMix64(seed);
    let (mut tr, mut te) = (Vec::new(), Vec::new());
    for class in [1.0, -1.0] {
        let mut idx: Vec<usize> = (0..y.len()).filter(|&i| y[i] == class).collect();
        // Fisher–Yates with the shared deterministic generator.
        for k in (1..idx.len()).rev() {
            let j = (rng.next_f64() * (k + 1) as f64) as usize % (k + 1);
            idx.swap(k, j);
        }
        for (pos, i) in idx.into_iter().enumerate() {
            if pos % 2 == 0 {
                tr.push(i)
            } else {
                te.push(i)
            }
        }
    }
    (tr, te)
}

fn take(rows: &[Vec<f64>], idx: &[usize]) -> Vec<Vec<f64>> {
    idx.iter().map(|&i| rows[i].clone()).collect()
}
fn take1(v: &[f64], idx: &[usize]) -> Vec<f64> {
    idx.iter().map(|&i| v[i]).collect()
}

/// Tier-1 structural screen. Returns `None` if the dataset is a
/// candidate, `Some(reason)` if it is refused outright.
///
/// Gates (arXiv:2607.15815 Alg. 1, no quantum simulation involved):
///   g1 (C1)  ρ_off > 0.3 — off-grid share of the periodogram mass;
///   g2       (advisory) a trained-frequency Fourier GAM's holdout AUC —
///            printed for context but never refusing: a classifier at
///            chance is evidence of missing structure, not proof (the
///            paper's tier 1 refuses only on *provable* failures; pure
///            noise is safely refused at tier 2, where no quantum lane
///            can beat the panel with a positive CI bound);
///   g5       d ≤ 14 qubits feasibility.
fn tier1_screen(ds: &Dataset, seed: u64) -> Option<String> {
    let d = ds.phases[0].len();
    if d > 14 {
        return Some(format!("infeasible: d = {d} > 14 qubits"));
    }
    // g1: per-feature periodogram over the continuum grid; integer-grid
    // mass = power within ±0.075 of an integer frequency.
    let (mut total, mut integer) = (0.0, 0.0);
    for j in 0..d {
        let col: Vec<f64> = ds.phases.iter().map(|p| p[j]).collect();
        for f in lanes::freq_grid() {
            let p = lanes::periodogram_power(&col, &ds.y, f);
            total += p;
            if (f - f.round()).abs() < 0.075 {
                integer += p;
            }
        }
    }
    let rho_off = 1.0 - integer / total.max(1e-12);
    // g2: Fourier-GAM classifier vs chance on a held-out half.
    let (tr, te) = split(&ds.y, seed);
    let (trx, try_) = (take(&ds.phases, &tr), take1(&ds.y, &tr));
    let (tex, tey) = (take(&ds.phases, &te), take1(&ds.y, &te));
    let gam_map = lanes::gam_basis(&trx, &try_);
    let w = logreg_fit(
        &trx.iter().map(|p| gam_map(p)).collect::<Vec<_>>(),
        &try_,
        1e-3,
        250,
        0.4,
    );
    let scores: Vec<f64> = tex.iter().map(|p| logreg_score(&w, &gam_map(p))).collect();
    let gam_auc = auc(&scores, &tey);
    println!(
        "    tier-1[{}]: ρ_off = {rho_off:.3} (gate > 0.3), Fourier-GAM holdout AUC = \
         {gam_auc:.3} (advisory), d = {d}",
        ds.name
    );
    if rho_off <= 0.3 {
        return Some(format!(
            "spectral mass on the integer grid (ρ_off = {rho_off:.3} ≤ 0.3)"
        ));
    }
    None
}

struct Tier2Outcome {
    certified: bool,
    detail: String,
}

/// Tier-2: five classical lanes vs a quantum lane on identical splits;
/// certification needs CI_lo(Δ) > 0 and (when an ablation is supplied)
/// CI_lo(ON − OFF) > 0.
#[allow(clippy::too_many_arguments)]
fn tier2_certify(
    name: &str,
    train_x: &[Vec<f64>],
    train_y: &[f64],
    test_x: &[Vec<f64>],
    test_y: &[f64],
    qnn_scores: &[f64],
    ablation_scores: Option<&[f64]>,
    seed: u64,
) -> Result<Tier2Outcome, String> {
    // --- classical panel ---
    let raw_fit = logreg_fit(train_x, train_y, 1e-3, 250, 0.4);
    let logreg: Vec<f64> = test_x.iter().map(|p| logreg_score(&raw_fit, p)).collect();

    let gam_map = lanes::gam_basis(train_x, train_y);
    let gam_w = logreg_fit(
        &train_x.iter().map(|p| gam_map(p)).collect::<Vec<_>>(),
        train_y,
        1e-3,
        250,
        0.4,
    );
    let gam: Vec<f64> = test_x
        .iter()
        .map(|p| logreg_score(&gam_w, &gam_map(p)))
        .collect();

    let ga2m_map = lanes::ga2m_basis(train_x, train_y);
    let ga2m_w = logreg_fit(
        &train_x.iter().map(|p| ga2m_map(p)).collect::<Vec<_>>(),
        train_y,
        1e-3,
        250,
        0.4,
    );
    let ga2m: Vec<f64> = test_x
        .iter()
        .map(|p| logreg_score(&ga2m_w, &ga2m_map(p)))
        .collect();

    let stumps = lanes::stumps_fit(train_x, train_y, 150, 0.1);
    let hgb: Vec<f64> = test_x
        .iter()
        .map(|p| lanes::stumps_score(&stumps, p))
        .collect();

    let joint_scan = lanes::joint_basis(train_x, train_y);
    if let Some(cap) = joint_scan.capped_features {
        println!(
            "    tier-2[{name}]: JOINT triple scan capped to the top {cap} features \
             (of {}) by periodogram power",
            train_x[0].len()
        );
    }
    println!(
        "    tier-2[{name}]: JOINT scan found features {:?} at f = ({:.2}, {:.2}, {:.2}), \
         power {:.4}",
        joint_scan.triple,
        joint_scan.freqs[0],
        joint_scan.freqs[1],
        joint_scan.freqs[2],
        joint_scan.best_triple_power
    );
    let joint_w = logreg_fit(
        &train_x
            .iter()
            .map(|p| (joint_scan.basis)(p))
            .collect::<Vec<_>>(),
        train_y,
        1e-3,
        250,
        0.4,
    );
    let joint: Vec<f64> = test_x
        .iter()
        .map(|p| logreg_score(&joint_w, &(joint_scan.basis)(p)))
        .collect();

    let lanes_scored: [(&str, &[f64]); 5] = [
        ("logreg", &logreg),
        ("gam", &gam),
        ("ga2m", &ga2m),
        ("stumps", &hgb),
        ("joint", &joint),
    ];
    let mut best: (&str, f64, &[f64]) = ("", -1.0, &logreg);
    for (lane, scores) in lanes_scored {
        let a = auc(scores, test_y);
        println!("    tier-2[{name}]: AUC {lane:>7} = {a:.4}");
        if a > best.1 {
            best = (lane, a, scores);
        }
    }
    let auc_q = auc(qnn_scores, test_y);
    println!(
        "    tier-2[{name}]: AUC quantum = {auc_q:.4}  (best classical: {} = {:.4})",
        best.0, best.1
    );

    let ci_lo = bootstrap_delta_ci_lo(qnn_scores, best.2, test_y, BOOT_REPS, seed);
    println!(
        "    tier-2[{name}]: paired bootstrap CI_lo(Δ = quantum − {}) = {ci_lo:+.4} \
         ({BOOT_REPS} reps; certify needs > 0)",
        best.0
    );

    let mut certified = ci_lo > 0.0;
    let mut detail = format!(
        "quantum {auc_q:.4} vs best classical {} {:.4}, CI_lo(Δ) = {ci_lo:+.4}",
        best.0, best.1
    );
    if let Some(off) = ablation_scores {
        let ci_ab = bootstrap_delta_ci_lo(qnn_scores, off, test_y, BOOT_REPS, seed ^ 0xAB);
        let auc_off = auc(off, test_y);
        println!(
            "    tier-2[{name}]: ablation (couplings OFF) AUC = {auc_off:.4}, \
             CI_lo(ON − OFF) = {ci_ab:+.4} (certify needs > 0)"
        );
        certified = certified && ci_ab > 0.0;
        detail.push_str(&format!(", ablation CI_lo = {ci_ab:+.4}"));
    }
    Ok(Tier2Outcome { certified, detail })
}

/// Rank-transform arbitrary real columns to phases in [−π, π] (the
/// paper's φ(X) map for raw tabular data).
fn rank_phases(rows: &[Vec<f64>]) -> Vec<Vec<f64>> {
    let n = rows.len();
    let d = rows[0].len();
    let mut out = vec![vec![0.0; d]; n];
    for j in 0..d {
        let mut order: Vec<usize> = (0..n).collect();
        order.sort_by(|&a, &b| rows[a][j].partial_cmp(&rows[b][j]).unwrap());
        for (rank, &i) in order.iter().enumerate() {
            out[i][j] =
                (rank as f64 + 0.5) / n as f64 * 2.0 * std::f64::consts::PI - std::f64::consts::PI;
        }
    }
    out
}

pub fn run(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "spectra",
        "SPECTRA certificate (arXiv:2607.15815): refuse advantage on open/enumerable data, \
         certify it on the quantum-generated Heisenberg substrate",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();

    // ---- The generator circuit + its verification. ----
    let lowered = harness::load_lowered(
        "spectra_heisenberg.aria",
        "SpectraHeisenberg",
        &[("steps", TROTTER_STEPS)],
    )?;
    let jt_ids: Vec<u32> = (0..6)
        .map(|k| {
            lowered
                .symbol_ids
                .get(&format!("jt_{k}"))
                .copied()
                .ok_or(format!("missing jt_{k}"))
        })
        .collect::<Result<_, _>>()?;
    let pt_ids: Vec<u32> = (0..7)
        .map(|i| {
            lowered
                .symbol_ids
                .get(&format!("pt_{i}"))
                .copied()
                .ok_or(format!("missing pt_{i}"))
        })
        .collect::<Result<_, _>>()?;
    let dt = TOTAL_TIME / TROTTER_STEPS as f64;
    let correlator =
        Observable::parse("1.0*Z0Z1 + 1.0*Z1Z2 + 1.0*Z2Z3 + 1.0*Z3Z4 + 1.0*Z4Z5 + 1.0*Z5Z6")?;
    let couplings = gen::heisenberg_couplings(SEED);
    println!(
        "  generator: 7-site disordered Heisenberg chain, J = [{}], T = {TOTAL_TIME}, \
         {TROTTER_STEPS} Trotter steps, seed {SEED}",
        couplings
            .iter()
            .map(|j| format!("{j:.3}"))
            .collect::<Vec<_>>()
            .join(", ")
    );

    // Eigenstate invariant: at φ = 0, |+⟩^⊗7 is a simultaneous
    // eigenstate of every Trotter slice → ⟨Σ ZZ⟩ = 0 exactly.
    let zero_corr = gen::heisenberg_correlator(
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &[0.0; 7],
        &correlator,
    )?;
    if zero_corr.abs() > 1e-9 {
        return Err(format!(
            "|+⟩ eigenstate invariant violated: ⟨ΣZZ⟩ = {zero_corr} at φ = 0"
        ));
    }
    println!("  |+⟩^⊗7 invariant: ⟨ΣZZ⟩ at φ = 0 is {zero_corr:.2e} (Trotter-exact 0) — OK");

    // Differential oracle check on a probe row THROUGH the transport.
    let mut rng = SplitMix64(SEED ^ 0x9E);
    let probe: Vec<f64> = (0..7)
        .map(|_| (rng.next_f64() * 2.0 - 1.0) * std::f64::consts::PI)
        .collect();
    let mut probe_params = vec![0.0; lowered.symbol_ids.len()];
    for (&id, &j) in jt_ids.iter().zip(&couplings) {
        probe_params[id as usize] = j * dt;
    }
    for (&id, &p) in pt_ids.iter().zip(&probe) {
        probe_params[id as usize] = p * dt;
    }
    let mut quantum_profile = Vec::with_capacity(7);
    for q in 0..7 {
        let obs = Observable::parse(&format!("1.0*Z{q}"))?;
        let (_payload, z) = harness::execute_report(
            transport,
            lowered.ir.clone(),
            harness::AppMode::Expectations(vec![obs]),
            &probe_params,
        )?;
        quantum_profile.push(z);
    }
    let oracle = sim::forward_z_expectations(&lowered.ir, &probe_params)?;
    let forward_verdict = banner::report_values(
        "spectra/forward",
        "omega ⟨Z_q⟩ profile, probe row",
        &quantum_profile,
        "independent in-tree statevector oracle",
        &oracle[..7],
        1e-9,
    );

    // ---- Dataset 1: UCI heart (open tabular; expect REFUSE). ----
    println!("\n  [1/3] UCI Cleveland heart (open tabular data)");
    let heart_rows = data::load_csv("heart_cleveland.csv")?;
    let mut hx = Vec::new();
    let mut hy = Vec::new();
    for row in &heart_rows {
        // 8 continuous-ish features (as the butterfly app), binary label
        // num > 0; rows with missing used-cells skipped.
        let cols = [0usize, 1, 2, 3, 4, 6, 8, 9];
        let feats: Option<Vec<f64>> = cols.iter().map(|&c| row[c]).collect();
        if let (Some(f), Some(num)) = (feats, row[13]) {
            hx.push(f);
            hy.push(if num > 0.0 { 1.0 } else { -1.0 });
        }
    }
    let heart = Dataset {
        phases: rank_phases(&hx),
        y: hy,
        name: "heart",
    };
    let heart_refused = match tier1_screen(&heart, SEED ^ 31) {
        Some(reason) => {
            println!("    → REFUSED at tier 1: {reason}");
            true
        }
        None => {
            let (tr, te) = split(&heart.y, SEED ^ 1);
            let (trx, try_) = (take(&heart.phases, &tr), take1(&heart.y, &tr));
            let (tex, tey) = (take(&heart.phases, &te), take1(&heart.y, &te));
            let mut q = qnn::TabularQnn::new(trx[0].len(), SEED ^ 11, true);
            q.fit(&backend, &trx, &try_, 25, 0.05)?;
            let qs = q.scores(&backend, &tex)?;
            let out = tier2_certify("heart", &trx, &try_, &tex, &tey, &qs, None, SEED ^ 21)?;
            println!(
                "    → {} at tier 2: {}",
                if out.certified {
                    "CERTIFIED"
                } else {
                    "REFUSED"
                },
                out.detail
            );
            !out.certified
        }
    };

    // ---- Dataset 2: sparse pocket (expect REFUSE via JOINT). ----
    println!("\n  [2/3] controlled sparse pocket (planted 3-way term, §6.2)");
    let pocket = gen::sparse_pocket(N_SYNTH, SEED ^ 2);
    let pocket_refused = match tier1_screen(&pocket, SEED ^ 32) {
        Some(reason) => {
            println!("    → REFUSED at tier 1: {reason} (unexpected — pocket should reach tier 2)");
            true
        }
        None => {
            let (tr, te) = split(&pocket.y, SEED ^ 3);
            let (trx, try_) = (take(&pocket.phases, &tr), take1(&pocket.y, &tr));
            let (tex, tey) = (take(&pocket.phases, &te), take1(&pocket.y, &te));
            let mut q = qnn::TabularQnn::new(3, SEED ^ 12, true);
            q.fit(&backend, &trx, &try_, 25, 0.05)?;
            let qs = q.scores(&backend, &tex)?;
            let out = tier2_certify("pocket", &trx, &try_, &tex, &tey, &qs, None, SEED ^ 22)?;
            println!(
                "    → {} at tier 2: {}",
                if out.certified {
                    "CERTIFIED"
                } else {
                    "REFUSED"
                },
                out.detail
            );
            !out.certified
        }
    };

    // ---- Dataset 3: Heisenberg substrate (expect CERTIFY). ----
    println!("\n  [3/3] quantum-generated Heisenberg substrate (§6.3)");
    let dense = gen::heisenberg(
        N_SYNTH,
        SEED ^ 4,
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &correlator,
    )?;
    let dense_certified = match tier1_screen(&dense, SEED ^ 33) {
        Some(reason) => {
            println!("    → REFUSED at tier 1: {reason} (unexpected)");
            false
        }
        None => {
            let (tr, te) = split(&dense.y, SEED ^ 5);
            let (trx, try_) = (take(&dense.phases, &tr), take1(&dense.y, &tr));
            let (tex, tey) = (take(&dense.phases, &te), take1(&dense.y, &te));
            let mut dmq = qnn::DmqLane::new(&lowered.ir, &jt_ids, &pt_ids, dt, &correlator);
            dmq.fit(&backend, &trx, &try_, 30, 0.05)?;
            println!(
                "    DMQ learned couplings: [{}] (true: [{}])",
                dmq.couplings
                    .iter()
                    .map(|j| format!("{j:.3}"))
                    .collect::<Vec<_>>()
                    .join(", "),
                couplings
                    .iter()
                    .map(|j| format!("{j:.3}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            let qs = dmq.scores(&backend, &tex)?;
            let mut off = dmq.ablated();
            off.fit_head_only(&backend, &trx, &try_)?;
            let offs = off.scores(&backend, &tex)?;
            let out = tier2_certify(
                "substrate",
                &trx,
                &try_,
                &tex,
                &tey,
                &qs,
                Some(&offs),
                SEED ^ 23,
            )?;
            println!(
                "    → {} at tier 2: {}",
                if out.certified {
                    "CERTIFIED"
                } else {
                    "REFUSED"
                },
                out.detail
            );
            out.certified
        }
    };

    // ---- Verdict. ----
    println!(
        "\n  SPECTRA outcomes: heart {} | pocket {} | substrate {}",
        if heart_refused {
            "REFUSED ✓"
        } else {
            "certified ✗"
        },
        if pocket_refused {
            "REFUSED ✓"
        } else {
            "certified ✗"
        },
        if dense_certified {
            "CERTIFIED ✓"
        } else {
            "refused ✗"
        },
    );
    let pass = forward_verdict.pass && heart_refused && pocket_refused && dense_certified;
    Ok(Verdict {
        name: "spectra".into(),
        pass,
        max_abs_diff: forward_verdict.max_abs_diff,
        tol: forward_verdict.tol,
    })
}

/// arch_search — coupling-graph architecture search on the Heisenberg
/// substrate (see `arch.rs` for the space and training).
///
/// CHECK: (a) the programmatic circuit builder reproduces the lowered
/// spectra_heisenberg.aria on a probe row (|Δ| ≤ 1e-9); (b) the search,
/// given only the labelled data, selects the generator's CHAIN graph
/// under a parsimony-penalised score; (c) the winner's learned couplings
/// approximate the true disorder draw (max |ΔJ| ≤ 0.2) and its holdout
/// AUC ≥ 0.85.
pub fn arch_search(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "arch_search",
        "architecture search over coupling graphs: rediscover the Heisenberg chain \
         from labelled data alone",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();
    let lowered = harness::load_lowered(
        "spectra_heisenberg.aria",
        "SpectraHeisenberg",
        &[("steps", TROTTER_STEPS)],
    )?;
    let jt_ids: Vec<u32> = (0..6)
        .map(|k| {
            lowered
                .symbol_ids
                .get(&format!("jt_{k}"))
                .copied()
                .ok_or(format!("missing jt_{k}"))
        })
        .collect::<Result<_, _>>()?;
    let pt_ids: Vec<u32> = (0..7)
        .map(|i| {
            lowered
                .symbol_ids
                .get(&format!("pt_{i}"))
                .copied()
                .ok_or(format!("missing pt_{i}"))
        })
        .collect::<Result<_, _>>()?;
    let dt = TOTAL_TIME / TROTTER_STEPS as f64;
    let correlator =
        Observable::parse("1.0*Z0Z1 + 1.0*Z1Z2 + 1.0*Z2Z3 + 1.0*Z3Z4 + 1.0*Z4Z5 + 1.0*Z5Z6")?;
    let couplings = gen::heisenberg_couplings(SEED);

    // (a) builder ≡ shipped example on a probe row.
    let mut rng = SplitMix64(SEED ^ 0xA5C);
    let probe: Vec<f64> = (0..7)
        .map(|_| (rng.next_f64() * 2.0 - 1.0) * std::f64::consts::PI)
        .collect();
    let aria_val = gen::heisenberg_correlator(
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &probe,
        &correlator,
    )?;
    let chain = &arch::candidates()[0];
    let (built_ir, bjt, bpt) = arch::build_ir(&chain.bonds, TROTTER_STEPS as usize);
    let built_val = gen::heisenberg_correlator(
        &backend,
        &built_ir,
        &bjt,
        &bpt,
        &couplings,
        dt,
        &probe,
        &correlator,
    )?;
    let builder_verdict = banner::report_values(
        "arch_search/builder",
        "programmatic coupling-graph builder (chain)",
        &[built_val],
        "lowered spectra_heisenberg.aria",
        &[aria_val],
        1e-9,
    );

    // Dataset: the SAME substrate the spectra certificate uses.
    let dense = gen::heisenberg(
        N_SYNTH,
        SEED ^ 4,
        &backend,
        &lowered.ir,
        &jt_ids,
        &pt_ids,
        &couplings,
        dt,
        &correlator,
    )?;
    let (tr, te) = split(&dense.y, SEED ^ 41);
    // Cheap-evaluation budget: 200 train rows, 10 epochs per candidate
    // (printed — no silent caps).
    let tr = &tr[..200.min(tr.len())];
    let (trx, try_) = (take(&dense.phases, tr), take1(&dense.y, tr));
    let (tex, tey) = (take(&dense.phases, &te), take1(&dense.y, &te));
    println!(
        "  search budget: {} candidates × 10 epochs on {} train rows; holdout {} rows",
        arch::candidates().len(),
        trx.len(),
        tex.len()
    );

    // (b) exhaustive search with a parsimony penalty (0.005·bonds):
    // a strict superset graph (ring ⊃ chain) can always match the chain
    // by zeroing its extra bond, so ties break toward fewer parameters.
    let mut results = Vec::new();
    for cand in arch::candidates() {
        let trained = arch::train_candidate(
            &cand,
            &backend,
            TROTTER_STEPS as usize,
            dt,
            &correlator,
            &trx,
            &try_,
            &tex,
            &tey,
            10,
        )?;
        println!(
            "  candidate {:>8}: holdout AUC = {:.4}  (bonds: {}, penalised score {:.4})",
            trained.name,
            trained.auc,
            trained.bonds.len(),
            trained.auc - 0.005 * trained.bonds.len() as f64,
        );
        results.push(trained);
    }
    results.sort_by(|a, b| {
        let sa = a.auc - 0.005 * a.bonds.len() as f64;
        let sb = b.auc - 0.005 * b.bonds.len() as f64;
        sb.partial_cmp(&sa).unwrap()
    });
    let winner = &results[0];
    println!(
        "  WINNER: '{}' — holdout AUC {:.4}, learned J = [{}] (true chain J = [{}])",
        winner.name,
        winner.auc,
        winner
            .couplings
            .iter()
            .map(|j| format!("{j:.3}"))
            .collect::<Vec<_>>()
            .join(", "),
        couplings
            .iter()
            .map(|j| format!("{j:.3}"))
            .collect::<Vec<_>>()
            .join(", ")
    );

    // (c) ground-truth checks.
    let chain_won = winner.name == "chain";
    let auc_ok = winner.auc >= 0.85;
    let j_close = chain_won
        && winner
            .couplings
            .iter()
            .zip(&couplings)
            .all(|(a, b)| (a - b).abs() <= 0.2);
    if !chain_won {
        println!(
            "  FAIL: search selected '{}', not the generator's chain",
            winner.name
        );
    }
    if !auc_ok {
        println!("  FAIL: winner AUC {:.4} < 0.85", winner.auc);
    }
    if chain_won && !j_close {
        println!("  FAIL: learned couplings deviate > 0.2 from the true draw");
    }

    // The deliverable: the discovered architecture as Aria source.
    let src = arch::to_aria_source(winner, TROTTER_STEPS as usize);
    println!("\n  discovered architecture (Aria source, first lines):");
    for line in src.lines().take(8) {
        println!("    {line}");
    }
    println!("    … ({} lines total)", src.lines().count());

    Ok(Verdict {
        name: "arch_search".into(),
        pass: builder_verdict.pass && chain_won && auc_ok && j_close,
        max_abs_diff: builder_verdict.max_abs_diff,
        tol: builder_verdict.tol,
    })
}

/// arch_evolve — evolutionary search over layered RBS masks on the
/// heart-imputation task (see `evolve.rs`).
///
/// CHECK: (a) determinism — re-evaluating the winning genome reproduces
/// its fitness exactly; (b) expert parity — the evolved architecture's
/// held-out MSE is within 0.02 of the hand-built butterfly genome
/// evaluated under the identical protocol; (c) the winner is no worse
/// than the no-entanglement ablation genome.
pub fn arch_evolve(transport_override: Transport) -> Result<Verdict, String> {
    let guest = "omega_app";
    let transport = resolve(transport_override, guest);
    banner::header(
        "arch_evolve",
        "evolutionary search over layered RBS connectivity masks vs the hand-built \
         butterfly (UCI heart imputation)",
        &transport.label(guest),
    );
    let backend = StatevectorBackend::new();

    // Heart data, prepared exactly like the butterfly app: 8 features →
    // standardized → atan angles; target thalach → tanh-squashed.
    let rows = data::load_csv("heart_cleveland.csv")?;
    let (means, stds) = data::column_stats(&rows);
    let cols = [0usize, 1, 2, 3, 4, 6, 8, 9];
    let target_col = 7;
    let mut xs = Vec::new();
    let mut ty = Vec::new();
    for row in &rows {
        let feats: Option<Vec<f64>> = cols.iter().map(|&c| row[c]).collect();
        let (Some(feats), Some(target)) = (feats, row[target_col]) else {
            continue;
        };
        xs.push(
            cols.iter()
                .zip(&feats)
                .map(|(&c, &v)| ((v - means[c]) / stds[c]).atan())
                .collect::<Vec<f64>>(),
        );
        ty.push(((target - means[target_col]) / stds[target_col]).tanh());
    }
    let n = xs.len();
    let mut rng = SplitMix64(SEED ^ 0xE0);
    let masked: Vec<bool> = (0..n).map(|_| rng.next_f64() < 0.30).collect();
    let tr: Vec<usize> = (0..n).filter(|&i| !masked[i]).collect();
    let te: Vec<usize> = (0..n).filter(|&i| masked[i]).collect();
    let tr = &tr[..160.min(tr.len())]; // search budget cap (printed)
    let (trx, try_) = (take(&xs, tr), take1(&ty, tr));
    let (tex, tey) = (take(&xs, &te), take1(&ty, &te));
    let (epochs, pop, gens) = (8, 8, 4);
    println!(
        "  budget: population {pop} × {gens} generations, {epochs} epochs each, \
         {} train / {} holdout rows (seed {SEED})",
        trx.len(),
        tex.len()
    );

    // References evaluated under the identical protocol, outside the search.
    let butterfly_mse = evolve::evaluate(
        &evolve::BUTTERFLY_GENOME,
        &backend,
        &trx,
        &try_,
        &tex,
        &tey,
        epochs,
        SEED,
    )?;
    let none_mse = evolve::evaluate(
        &evolve::NONE_GENOME,
        &backend,
        &trx,
        &try_,
        &tex,
        &tey,
        epochs,
        SEED,
    )?;
    println!(
        "  references: hand-built butterfly [{}] MSE = {butterfly_mse:.5}; \
         no-entanglement MSE = {none_mse:.5}",
        evolve::genome_name(&evolve::BUTTERFLY_GENOME)
    );

    let (winner, fitness, cache) =
        evolve::evolve(&backend, &trx, &try_, &tex, &tey, epochs, SEED, pop, gens)?;
    println!(
        "  EVOLVED: [{}] MSE = {fitness:.5} ({} unique genomes evaluated of {} in the space)",
        evolve::genome_name(&winner),
        cache.len(),
        evolve::mask_menu().len().pow(evolve::LAYERS as u32)
    );

    // (a) determinism.
    let re_eval = evolve::evaluate(&winner, &backend, &trx, &try_, &tex, &tey, epochs, SEED)?;
    let deterministic = re_eval == fitness;
    if !deterministic {
        println!("  FAIL: winner re-evaluation {re_eval} ≠ cached {fitness}");
    }
    // (b) expert parity, (c) entanglement sanity.
    let parity = fitness <= butterfly_mse + 0.02;
    if !parity {
        println!("  FAIL: evolved MSE {fitness:.5} worse than butterfly {butterfly_mse:.5} + 0.02");
    }
    let beats_none = fitness <= none_mse + 1e-9;
    if !beats_none {
        println!("  FAIL: evolved MSE {fitness:.5} worse than no-entanglement {none_mse:.5}");
    }
    println!(
        "  verdict inputs: deterministic {deterministic}, expert parity {parity} \
         (Δ = {:+.5}), ≥ ablation {beats_none}",
        fitness - butterfly_mse
    );

    Ok(Verdict {
        name: "arch_evolve".into(),
        pass: deterministic && parity && beats_none,
        max_abs_diff: (fitness - butterfly_mse).max(0.0),
        tol: 0.02,
    })
}
